### ISSUE TITLE
Support Guild Scheduled Events

### ISSUE THREAD

**Issue by darichey** [Discord4J/Discord4J#1000]
**Feature Description:**
Support everything described in https://github.com/discord/discord-api-docs/pull/3586.

Should wait for that to be merged before we merge anything, but someone can start on this if they want.

**Comment by TheAwesomeGuy47** [comment]
Issue 1000 👀

**Comment by quanticc** [comment]
Are we supposed to cache these?

**Comment by NovaFox161** [comment]
This has finally been merged into the docs and should be open for bots now, or at least very soon in the future. I'm going to get to work on getting this into d4j
