### ISSUE TITLE
Add getResolved methods to context menu interactions

### ISSUE THREAD

**Issue by quanticc** [Discord4J/Discord4J#1007]
**Feature Description:** Some interaction events contain a `resolved` object that was implemented in #980. After context menus, we receive a member, user or message depending on the interaction, and it could be added as API to the appropriate event, removing the need of going through `getInteraction()` and `getResolved()`. Targeting 3.2.x branch.

For example, adding to user contexts a method like this:

```java
public User getResolvedUser() {
    return getInteraction()
            .getCommandInteraction()
            .flatMap(ApplicationCommandInteraction::getResolved)
            .flatMap(it -> it.getUser(getTargetId()))
            .orElseThrow(IllegalStateException::new);
}
```

And a similar one can be added to Member if present.

For message contexts, we need an update to `ApplicationCommandInteractionResolvedData` as `messages` field is not present at the moment. https://discord.com/developers/docs/interactions/application-commands#message-commands-example-interaction

**Justification:** Avoid depending on the cache to get data if Discord provides it.

**Comment by NovaFox161** [comment]
Merged into 3.2.1 and 3.3.x
