### ISSUE TITLE
PermissionOverwrite vs ExtendedPermissionOverwrite Discrepancy

### ISSUE THREAD

**Issue by Laarryy** [Discord4J/Discord4J#1009]
**To Reproduce:** 

`textChannel#getPermissionOverwrites` returns a Set\<ExtendedPermissionOverwrite\>, while `textChannel#addAllPermissionOverwrites` requires a Set\<PermissionOverwrite\>. This means that there is no straightforward way to get the list of permission overwrites for a channel, add n overwrites to it, and then send them off to discord.

**Expected Behavior:** 

After discussion with Panso, the method should potentially relax the type parameter there to allow `List<? extends PermissionOverwrite>` instead of strictly PermissionOverwrite.

**Actual Behavior:** 

Method permits only PermissionOverwrite and not ExtendedPermissionOverwrite as is provided elsewhere.

**Version:** 

3.2.0-RC3

**Other:**

**Comment by darichey** [comment]
As explained in the issue, I think this is really as simple as 
```diff
- Possible<List<PermissionOverwrite>> permissionOverwrites();
+ Possible<List<? extends PermissionOverwrite>> permissionOverwrites();
```
in all of the `XChannelEditGenerator`. We should still be able to read at least `PermissionOverwrite` from the list.

**Comment by skykatik** [comment]
It's not as simple as it seems, Immutables can't handle `List<? extends PermissionOverwrite>` and throws exception with message _"Wildcard as array element is not allowed: ? extends discord4j.core.object.PermissionOverwrite"_
