### ISSUE TITLE
Include generated sources for specs in jar

### ISSUE THREAD

**Issue by darichey** [Discord4J/Discord4J#1017]
**Feature Description:**
We should include the generated sources for specs in the jar, so people don't have have to decompile the class files to look at them. 

**Justification:**
This will make it easier for users to use the classes. 

I can't immediately find any information on how to do this, but I think it should be possible with Gradle.

**Comment by NovaFox161** [comment]
If we can do this, that would be fantastic. I have no idea on how to do this either
