### ISSUE TITLE
Application command type "user" crash list command

### ISSUE THREAD

**Issue by ph1823** [Discord4J/Discord4J#1034]
Discord4J Version: 3.2.0

Exception: ```Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `discord4j.discordjson.json.ImmutableApplicationCommandData`, problem: Cannot build ApplicationCommandData, some of required attributes are not set [description]```
Full log: https://www.toptal.com/developers/hastebin/agaxagidon.less

How to reproduce this error: create a command with type is "USER", and discord doest'n accept description for command type USER.

Code: 
```java
    public ApplicationCommandRequest createCommand(String name, String description, int type, ApplicationCommandOptionData... optionsData) {
        return ApplicationCommandRequest.builder()
                .name(name)
                .description(description)
                .addAllOptions(Arrays.asList(optionsData))
                .type(type)
                .build();
    }

        ApplicationCommandRequest muteUserRequest = main.createCommand("Information utilisateur",
                "",
                USER.getValue());

        Map<String, ApplicationCommandData> discordCommands = gateway.rest()
                .getApplicationService()
                .getGuildApplicationCommands(applicationId, 465460952784044032L)
                .filter(applicationCommandData -> !applicationCommandData.description().isEmpty()) //try to fix, but not work :(
                .collectMap(ApplicationCommandData::name)
                .block();//crash her
```

I have try to filter my map, with id of command or on check if the description is empty, but doest work :(
How to get list without this command ?

To fix this error, i have get the id of command with UserInteractionEvent and delete with code give by discord4j doc.
But a why ApplicationCommandData require description if command type of user doest require description ??
Its a bug or a intentional feature ??

Thank for your help !

**Comment by Alex1304** [comment]
it's a bug on Discord's end, I reported it earlier today https://github.com/discord/discord-api-docs/issues/4017

**Comment by ph1823** [comment]
> it's a bug on Discord's end, I reported it earlier today [discord/discord-api-docs#4017](https://github.com/discord/discord-api-docs/issues/4017)

Thank you ! So we just have to wait for discord to resolve this error :( This is not from discord4j ..

**Comment by NovaFox161** [comment]
Yeah, it'll be automatically fixed once discord fixes it on their side.

I'm closing this issue, please refer to the issue linked by Alex for further info.
