### ISSUE TITLE
Bot stays online but randomly does not respond

### ISSUE THREAD

**Issue by Nagispace** [Discord4J/Discord4J#1049]
**To Reproduce:** Follow the simple bot template, implement various commands such as, the basic ping and greet command, commands that request data to a DB. Run it on a dedicated server

**Expected Behavior:** bot always responding when it is online

**Actual Behavior:** bot randomly stop working and will start working again for a short time at random with no intervention

**Version:** 3.2.0

# Other

## ON DEV PC:
Generated the jar with maven install
## Content of pom.xml : 

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.5.6</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>net.nagispace</groupId>
    <artifactId>NiqueV7</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>NiqueV7</name>
    <description>NiqueV7</description>
    <properties>
        <java.version>17</java.version>
        <maven.test.skip>true</maven.test.skip>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>2.7.3</version>
        </dependency>
        <dependency>
            <groupId>org.graalvm.js</groupId>
            <artifactId>js-scriptengine</artifactId>
            <version>21.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.graalvm.truffle</groupId>
            <artifactId>truffle-api</artifactId>
            <version>21.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.graalvm.js</groupId>
            <artifactId>js</artifactId>
            <version>21.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.discord4j</groupId>
            <artifactId>discord4j-core</artifactId>
            <version>3.2.0</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.8.1</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>

```

## ON SERVER : 
The generated jar started with 
`nohup java -jar my_bot_jar-SNAPSHOT.jar &`
on a Raspberry Pi 4
java -version output
```
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-39)
OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)

```
[nohup.out.txt](https://github.com/Discord4J/Discord4J/files/7617496/nohup.out.txt), the bot still receive commands and treats them (we can see the request to my DB) but will not respond in the channel

**Comment by NovaFox161** [comment]
It looks like a combination of blocking the main thread and not handling errors gracefully. If the bot ever just "stops doing something" its usually an unhandled error causing the subscription to terminate. 

Quantic:
> If you listen to events using `on(class).subscribe(event -> x)` you are exposed to this issue if `x` throws an exception

Without your actual source code there's no way for us to know for sure what is causing the issue here as "implement various commands and db queries" could mean quite a number of possibilities (my own bot does this and doesn't have issues). You could be running blocking operations inside of a reactive thread and causing the connection to timeout (from the looks of the errors that appears to be happening)

I'd recommend you reach out in our [support server](https://discord.gg/d4j) so that we can help if you still need assistance.
