### ISSUE TITLE
GUILD_APPLICATION_COMMAND_INDEX_UPDATE event is missing

### ISSUE THREAD

**Issue by quinoaa** [Discord4J/Discord4J#1077]
**To Reproduce:** 
Create new commands with ApplicationService.bulkOverwriteGuildApplicationCommand()

**Expected Behavior:** 
I'd expect to not receive any error

**Actual Behavior:** 
`GUILD_APPLICATION_COMMAND_INDEX_UPDATE` is not handled and a warning appears in the console

Warning in console:
`[ WARN] (reactor-http-nio-5) Error while decoding JSON (java.lang.IllegalArgumentException: Attempt to deserialize payload with unknown event type: GUILD_APPLICATION_COMMAND_INDEX_UPDATE): {"t":"GUILD_APPLICATION_COMMAND_INDEX_UPDATE","s":3,"op":0,"d":{"hashes":{"version":1,"roles":{"hash":"2xDFx9cOxQ4"},"metadata":{"hash":"vO6mZsk/exY"},"channels":{"hash":"xqc7IvKsvf8"}},"guild_hashes":{"version":1,"roles":{"hash":"2xDFx9cOxQ4"},"metadata":{"hash":"vO6mZsk/exY"},"channels":{"hash":"xqc7IvKsvf8"}},"application_command_counts":{"1":1},"guild_id":"921116720075251712"}}`

**Version:** 
3.2.2

**Comment by NovaFox161** [comment]
This can be ignored. It is an event meant for clients, but Discord still sends it to bots.
