### ISSUE TITLE
Get the thread from the message

### ISSUE THREAD

**Issue by Johnny850807** [Discord4J/Discord4J#1078]
**Feature Description:** 
Can I get the Discord Thread from a message?

**Justification:**
I need to count all the messages in a text channel, including all the messages in the threads in that channel.

I've checked all the APIs that a message object exposes. Still can't find any workaround.

**Comment by SimonIT** [comment]
> The created thread and the message it was started from will share the same id
 
[Docs](https://discord.com/developers/docs/topics/threads)
So could just get the thread by the message id

**Comment by Johnny850807** [comment]
> > The created thread and the message it was started from will share the same id
> 
> [Docs](https://discord.com/developers/docs/topics/threads#public-private-threads) So you could get the thread by the message id

Sorry, but how can I use Discord4J library to achieve this? It looks like it needs me to call the RESTFul API myself?

**Comment by SimonIT** [comment]
I think something like `getChannelById(message.getId()).cast(ThreadChannel.class)` should work (Didn't test it)

**Comment by NovaFox161** [comment]
Thread support is limited to the in-dev version 3.3.x on the master branch and can be used in projects with the 3.3.0-SNAPSHOT version (further info on using snapshots is in our docs). 

I personally have not been involved in the thread support development, but I believe you can do something like Simon suggested above. Code contributions are much appreciated as we know threads are a high demand feature, we've all just been incredibly busy or burnt out.

**Comment by Gregory-Widmer** [comment]
Hello,

I'm digging up issues as I have to time to spare.

I confirm that the `Message#getChannel()` method can get the channel for you. If you need to know if you are in a Thread channel, use the instanceof operator or the `Flux#ofType` method to "filter" channels that are ThreadChannels.

As @NovaFox161 said, it is a 3.3.X feature only as Thread channels (and forums in a future version) are provided in those versions. 

Here is a code sample printing the thread channel name when a message is posted in a thread.

``Java
                    Mono<Void> onMessageCreate = client.on(MessageCreateEvent.class)
                            .map(MessageCreateEvent::getMessage) // Let's use the Message object as a start point
                            .flatMap(Message::getChannel) // Get the channel from the message
                            .ofType(ThreadChannel.class) // Filter objects that are castable as ThreadChannel 
                            .doOnNext(threadChannel -> System.out.format("A message has been posted in a ThreadChannel named %s !\n", threadChannel.getName()))
                            .then();```

You need to get familiar with Project Reactor to understand each operator, if you need help you can ask.
