### ISSUE TITLE
Select guilds of a user

### ISSUE THREAD

**Issue by knyttl** [Discord4J/Discord4J#1085]
Say I have an authorized user for a bot application: I have its `discordId` and `accessTokens`.

I also have a the bot token.

I can see I can list all guilds associated to a bot with:

```kotlin
    val client = DiscordClient.create(discordBotToken)
    for (guildData in client.guilds.collectList().block()!!) {
        println(guildData)
    }
```

However I am unable to list only guilds owned/created by certain user (with its discordId). Is there a way to list these?

**Comment by NovaFox161** [comment]
You can use `.filter()` to filter the guilds in the Flux by a condition. But that will only get mutual guilds with that user.

If you want all guilds the user is in, you'll need to implement that http call yourself, since d4j currently does not have support for oauth2 (there's work being done #715)

**Comment by knyttl** [comment]
superb, thanks for a super-quick response!
