### ISSUE TITLE
Android Bot not Logging In (Version 3.2.3)

### ISSUE THREAD

**Issue by crossflame22** [Discord4J/Discord4J#1090]
**To Reproduce:** Android studio app that runs discord4j as a background worker. Code:

    import android.util.Log;

    import discord4j.core.DiscordClient;
    import discord4j.core.GatewayDiscordClient;
    import discord4j.core.event.domain.lifecycle.ReadyEvent;
    import discord4j.core.object.entity.User;
    import reactor.core.publisher.Mono;

    public class DiscordListener {

        public static void main() {
            DiscordClient client = DiscordClient.create("TOKEN REDACTED");
            Log.d("aiusjdoiajs", "uhh so the key exists");
            // logs bot in
            Mono<Void> login = client.withGateway((GatewayDiscordClient gateway) ->
                    gateway.on(ReadyEvent.class, event ->
                            Mono.fromRunnable(() -> {
                                final User self = event.getSelf();
                                Log.d("asjdaosd", "Logged in as %s#%s%n");
                            })));
            Log.d("aisuhdaisd", "istg if we're not logged in");
        }
    }

**Expected Behavior:** I expect the bot to come online and for "Logged in as %s#%s%n" to be printed to Android Studio console.

**Actual Behavior:** `I/System.out: [ INFO] (androidx.work-1) Discord4J 3.2.3 (https://discord4j.com)
D/aiusjdoiajs: uhh so the key exists
D/aisuhdaisd: istg if we're not logged in
I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=eef27e88-a684-4d49-bc96-241cb6b29446, tags={ com.example.uhhdiscordvcchecker.DiscordWorker } ]
I/WM-SystemFgDispatcher: Stopping foreground service`

**Version:** 3.2.3

**Other:** N/A

**Comment by NovaFox161** [comment]
You aren't subscribing to the login call, so nothing will ever happen (akin to preparing all your ingredients for your dinner, but never actually turning on the oven)

Reactor quick start: https://docs.discord4j.com/reactive-reactor-tutorial

Our help server: https://discord.gg/d4j
