### ISSUE TITLE
There should be a ApplicationCommandInteractionOptionValue.asAttachment() method

### ISSUE THREAD

**Issue by Nyde42** [Discord4J/Discord4J#1091]
**Feature Description:** 
There should be a `ApplicationCommandInteractionOptionValue.asAttachment()` method for the values of command options that have the type 11 (`ATTACHMENT`).

**Justification:** 
With all the support for attachment options that came in 3.2.2, I find it weird that it's not possible to get the attachment directly from an option's value, while this is possible for all other option types that have values. For both consistency and convenience, I see no reason why this method should not exist.

**Comment by NovaFox161** [comment]
Closing as added in `3.2.4-SNAPSHOT` and `3.3.0-SNAPSHOT`.
