### ISSUE TITLE
Move getRateLimitPerUser from TextChannel

### ISSUE THREAD

**Issue by Doc94** [Discord4J/Discord4J#1111]
**Feature Description:** Make the edit/view of rate limit per user can be used in any channel with text. this currently is only allowed in the TextChannel and cannot set/get this value for VoiceChannel

**Comment by quanticc** [comment]
Does it also work with NewsChannel? if so, then the target class would be `BaseTopLevelGuildMessageChannel`. What do you think?

**Comment by Doc94** [comment]
> Does it also work with NewsChannel? if so, then the target class would be `BaseTopLevelGuildMessageChannel`. What do you think?

Okay i think you cannot set that field in a news channel based in the GUI.. but testing with postman i can and looks like works.
![image](https://github.com/Discord4J/Discord4J/assets/3602279/3d713c42-9896-4ae3-917e-3c47896d5498)
![image](https://github.com/Discord4J/Discord4J/assets/3602279/d2e2d575-e604-421c-a325-1bcfb90fbf34)
then yeah i think all channels support that thing
