### ISSUE TITLE
Add support for GUILD_AUDIT_LOG_ENTRY_CREATE event

### ISSUE THREAD

**Issue by Azn9** [Discord4J/Discord4J#1112]
**Justification:** https://github.com/discord/discord-api-docs/pull/5849

**Comment by Doc94** [comment]
Created PR for implement this.... not fully tested and waiting for the final release in discord docs.

**Comment by Doc94** [comment]
not sure why the PR not link with this issue.. but the experimental 3.2.4-SNAPSHOT has the event for the audit logs.

**Comment by quanticc** [comment]
I think the merge commit message has to include the close keyword and I forgot to include it. Closing via #1113
