### ISSUE TITLE
Response withComponents generare lasts forever

### ISSUE THREAD

**Issue by OpusMagnus5** [Discord4J/Discord4J#1123]
**To Reproduce:** 

Response to event withComponents where ActionRow.of() takes empty list, lasts forever and bot doesn't respond.
`List<Button> buttonsList = new ArrayList<>();
InteractionApplicationCommandCallbackSpec response = InteractionApplicationCommandCallbackSpec.builder().build();
return response.withComponents(ActionRow.of(buttonsList))
`
**Expected Behavior:** 
Bot answers
**Actual Behavior:** 
Bot is not responding
**Version:** 
3.2.3
**Other:**

**Comment by darichey** [comment]
Hi, we need more context to help you debug. What do you do with the returned Mono?

**Comment by OpusMagnus5** [comment]
Register event listeners
```
for (EventListener<T> listener : eventListeners) {
            gateway.on(listener.getEventType()).flatMap(listener::processCommand).subscribe();
        }
```
Event Handler
```
public Mono<Void> processCommand(ChatInputInteractionEvent event) {
        String eventName = event.getCommandName();
        switch (eventName){
            case "hero" :
                return event.reply(buildRespondForHeroCommand(event)).onErrorResume(this::handleError);
```
Error Handler 
```
public Mono<Void> handleError(Throwable error) {
        return Mono.empty();
    }

```

**Comment by quanticc** [comment]
I can't reproduce any issue but I think you should add some logging in your error handler instead of ignoring the exception.

Also, I recommend moving your event listener code to:

```java
gateway.on(listener.getEventType(), event -> listener.processCommand(event)).subscribe();
```

that `on` variant can catch errors without cancelling the subscription which could be happening.
