### ISSUE TITLE
Support for SKU/Entitlements (Premium Apps)

### ISSUE THREAD

**Issue by Buuz135** [Discord4J/Discord4J#1169]
**Feature Description:** Add support for the new features added to make premium apps (described [here](https://discord.com/developers/docs/monetization/overview))

**Justification:**  It's a neat feature to easily monetize your bot.

**Comment by Azn9** [comment]
I started working on it ;)
- Discord-json PR : https://github.com/Discord4J/discord-json/pull/160
- Discord4J PR : TODO
