### ISSUE TITLE
Long response to buttons

### ISSUE THREAD

**Issue by epilepticseizureee** [Discord4J/Discord4J#1172]
When interacting with buttons, the response from them takes a very long time. Conventionally, I have a message with verification of users by gender type and buttons, as well as a corresponding event.

But when you press them, the response from the buttons is long

`private void registerListeners() {
        this.gateway.on(new ReactiveEventAdapter() {
            @Override
            public Publisher<?> onButtonInteraction(ButtonInteractionEvent event) {
                String customId = event.getCustomId();
                Member interactedMember = event.getInteraction().getMember().get();

                Guild targetGuild = gateway.getGuildById(Snowflake.of(config.misc.guildId)).block();

                if (targetGuild != null) {
                    Role maleRole = targetGuild.getRoleById(Snowflake.of(config.roles.maleRoleId)).block();
                    Role femaleRole = targetGuild.getRoleById(Snowflake.of(config.roles.femaleRoleId)).block();
                    Role joinRole = targetGuild.getRoleById(Snowflake.of(config.roles.joinRoleId)).block();

                    List<Role> roles = interactedMember.getRoles().collectList().block();

                    if ("male".equals(customId)) {
                        if (roles != null) {
                            if (roles.contains(maleRole) || roles.contains(femaleRole)) {
                                return event.reply(InteractionApplicationCommandCallbackSpec.builder()
                                        .addEmbed(EmbedCreator.createWarn("У вас уже есть роль верификации!")).build());
                            }

                            interactedMember.addRole(maleRole.getId()).block();
                            interactedMember.removeRole(joinRole.getId()).block();

                            return event.reply(InteractionApplicationCommandCallbackSpec.builder()
                                    .addEmbed(EmbedCreator.createSuccess("Вы успешно прошли верификацию как Мальчик!")).build());
                        } else {
                            return event.reply("На сервере не настроены роли верификации!").withEphemeral(true);
                        }
                    } else if ("female".equals(customId)) {
                        if (roles != null) {
                            if (roles.contains(maleRole) || roles.contains(femaleRole)) {
                                return event.reply(InteractionApplicationCommandCallbackSpec.builder()
                                        .addEmbed(EmbedCreator.createWarn("У вас уже есть роль верификации!")).build());
                            }

                            interactedMember.addRole(femaleRole.getId()).block();
                            interactedMember.removeRole(joinRole.getId()).block();

                            return event.reply(InteractionApplicationCommandCallbackSpec.builder()
                                    .addEmbed(EmbedCreator.createSuccess("Вы успешно прошли верификацию как Девочка!")).build());
                        } else {
                            return event.reply("На сервере не настроены роли верификации!").withEphemeral(true);
                        }
                    }
                }

                return Mono.empty();
            }
        }).subscribe();
    }`

**Comment by Gregory-Widmer** [comment]
From what I can read, you should consider refactoring your Reactive chains.

You are doing multiple `.block()` calls instead of chaining them into a reactive chain. The issue here is that you subscribe all this block, so you are making blocking calls inside a non-blocking call which will be scheduled on some multi-threading ressources. This, depending on your multi-threading reactor configuration could lead to thread starvation.

That means you are waiting for ressources to free and this could be the root cause of your 
issue.

More info here : https://docs.discord4j.com/threading

On the other possible root causes subject, consider double-checking your network latency, as this will definitively affect the timing. If the client pressing the button has a bad connection, it will lag. Same for your bot.

**Comment by epilepticseizureee** [comment]
okay, but i'm changed api to jda (java discord api), this is fastet api
