### ISSUE TITLE
getParent in a ThreadChannel return a cast error

### ISSUE THREAD

**Issue by Doc94** [Discord4J/Discord4J#1173]
**To Reproduce:**  Call the getParent in a thread channel from a forum.

**Actual Behavior:** Try to return a [TopLevelGuildChannel](https://www.javadoc.io/static/com.discord4j/discord4j-core/3.3.0-RC1/discord4j/core/object/entity/channel/TopLevelGuildChannel.html) but the Forum is a [TopLevelGuildMessageChannel](https://www.javadoc.io/static/com.discord4j/discord4j-core/3.3.0-RC1/discord4j/core/object/entity/channel/TopLevelGuildMessageChannel.html)

**Version:** 3.3.0-SNAPSHOT

**Comment by Doc94** [comment]
> Oops, probably my bad when I wrote #1126 even after review.
> 
> ~However, that is kinda weird because I am using this to perform some actions in my bots, maybe it has been updated ?~ _Edit: No, I'm using ID only, so nevermind_
> 
> I am going to write a PR for this as it seems to be kinda boring.

yeah that was my workarround using the method byId for get the channel xd

**Comment by Gregory-Widmer** [comment]
I'm publishing a snapshot on my own nexus and writing the PR, the easiest solution is updating the ThreadChannel#getParent method signature, that would introduce a breaking change but as 
3.3.0 is still pre-released I think it won't matter that much.

**Comment by Gregory-Widmer** [comment]
Here is a simple reproduction code with some minor logging to check it out : 

```Java
import discord4j.core.DiscordClient;
import discord4j.core.event.domain.message.MessageCreateEvent;
import discord4j.core.object.entity.channel.ThreadChannel;
import reactor.core.publisher.Mono;

import java.util.Optional;

public class Main {


    public static void main(String[] args) {
        DiscordClient.create(Optional.ofNullable(System.getenv("DISCORD_TOKEN")).or(() -> Optional.ofNullable(args.length > 0 ? args[0] : null)).orElseThrow())
                .withGateway(gatewayDiscordClient -> {
                    Mono<Void> forumThreadListener = gatewayDiscordClient.on(MessageCreateEvent.class, messageCreateEvent -> messageCreateEvent.getMessage().getChannel()
                            .doOnNext(messageChannel -> System.out.printf("Received message in channel ID %s of type %s\n", messageChannel.getId().asString(), messageChannel.getType().name()))
                            .ofType(ThreadChannel.class)
                            .doOnNext(threadChannel -> System.out.printf("Channel ID %s is a ThreadChannel, getting its parent\n", threadChannel.getId().asString()))
                            .flatMap(ThreadChannel::getParent)
                            .doOnNext(topLevelGuildMessageChannel -> System.out.printf("Parent channel ID is %s, its type is %s\n", topLevelGuildMessageChannel.getId().asString(), topLevelGuildMessageChannel.getType().name()))
                            .onErrorResume(throwable -> {
                                System.err.println("Cannot handle event");
                                throwable.printStackTrace();
                                return Mono.empty();
                            })).then();

                    return Mono.zipDelayError(
                            gatewayDiscordClient.onDisconnect(),
                            forumThreadListener
                    );
                })
                .block();
    }

}```

We can see pretty well the kind of issue (first message is in a text channel, second one in a :

**Comment by Doc94** [comment]
Closed by https://github.com/Discord4J/Discord4J/commit/6395a9b7adf22d285dca92f865921a33fa0c10c4
