### ISSUE TITLE
Rename the sticker pack route as it is no longer required to have a nitro subscription

### ISSUE THREAD

**Issue by Azn9** [Discord4J/Discord4J#1192]
Just a small cosmetic change 😇 

https://github.com/Discord4J/Discord4J/blob/765560b5cda3ec1562bad175218cead52cfdb05f/rest/src/main/java/discord4j/rest/route/Routes.java#L435

**Comment by mennafabio** [comment]
Hey @Azn9 i created a PR for this quick issue :) https://github.com/Discord4J/Discord4J/pull/1218
