### ISSUE TITLE
Add some utilities to mention the guild navigation channels

### ISSUE THREAD

**Issue by Azn9** [Discord4J/Discord4J#1194]
**Feature Description:** Add some utility methods to the `Guild` objects, to get the guild navigation channels mentions easily (`<id:customize>`, `<id:browse>` and `<id:guide>`)

https://github.com/discord/discord-api-docs/pull/6105

**Comment by Azn9** [comment]
Work needed:
- Add three methods `public String getCustomizeChannelMention()`, `public String getBrowseChannelMention()` and `public String getGuideChannelMention()` to the `core/src/main/java/discord4j/core/object/entity/Guild.java` and `rest/src/main/java/discord4j/rest/entity/RestGuild.java` classes

**Comment by Doc94** [comment]
Maybe just a enum like NavigationChannel and that has the static things?

**Comment by Azn9** [comment]
> Maybe just a enum like NavigationChannel and that has the static things?

Yeah, that's a better idea, I'll edit my initial answer 👍
