### ISSUE TITLE
Add a "getUser" method on the Interaction events

### ISSUE THREAD

**Issue by Azn9** [Discord4J/Discord4J#1216]
To get the user, you need to call `event.getInteraction().getUser()`. To simplify developers' experience, we could expose the `getUser` method to the event classes, allowing them to use `event.getUser()`.

**Comment by jasonmokk** [comment]
Hi, can I work on this issue?

**Comment by Azn9** [comment]
> Hi, can I work on this issue?

Hey, feel free to do so! Any contribution is welcome and (as far as I know) no one is working on this!
