### ISSUE TITLE
Commands are not registered as user integration

### ISSUE THREAD

**Issue by raven4444** [Discord4J/Discord4J#1255]
**To Reproduce:** Create a command which uses integration type _user_ and _guild_ then try to register it. 

**Expected Behavior:** Command should be registered as guild and user integration

**Actual Behavior:** Command registered as guild only. Values are lost during serialization. Check the screens below.

**Version:** 3.3.0-RC1-114-gc280e74

**Other:** 
JSON with command declaration to load:
`{
  "name": "burza",
  "description": "Sprawdź czy Zeus napierdala w okolicy",
  "integration_types": [0, 1]
}`
Parsed file:
![idea64_vPxfcx01Zk](https://github.com/user-attachments/assets/6243277d-0e2b-4529-92be-149730248932)
Serialization in ApplicationService.bulkOverwriteGuildApplicationCommand/bulkOverwriteGlobalApplicationCommand:
![idea64_EXdcauv2bj](https://github.com/user-attachments/assets/e3908141-c38d-446f-845c-074e7eb759bf)

Loading commands from jsons - here **request** contains values:
```Java
final JacksonResources d4jMapper = JacksonResources.create();
        PathMatchingResourcePatternResolver matcher = new PathMatchingResourcePatternResolver();
        final ApplicationService applicationService = client.getApplicationService();
        final long applicationId = client.getApplicationId().block();
        List<ApplicationCommandRequest> commands = new ArrayList<>();
        for (Resource resource : matcher.getResources("commands/*.json")) {
            LOGGER.info("Processing command from " + resource.getFilename());
            ApplicationCommandRequest request = d4jMapper.getObjectMapper()
                    .readValue(resource.getInputStream(), ApplicationCommandRequest.class);

            commands.add(request);
        }
        if (activeProfile.equalsIgnoreCase("dev")) {
            LOGGER.warn("Test env will use guild commands, production will swap to global");
            applicationService.bulkOverwriteGuildApplicationCommand(applicationId, 289087038941036545L, commands)
                    .doOnNext(ignore -> LOGGER.info("Successfully registered guild command " + ignore.name()))
                    .doOnError(e -> LOGGER.error("Failed to register global command", e))
                    .subscribe();
        } else {
            applicationService.bulkOverwriteGlobalApplicationCommand(applicationId, commands)
                    .doOnNext(ignore -> LOGGER.info("Successfully registered global command " + ignore.name()))
                    .doOnError(e -> LOGGER.error("Failed to register global command ", e))
                    .subscribe();
        }
```

**Comment by Azn9** [comment]
This was caused by the use of `bulkOverwriteGuildApplicationCommand`, as guild commands cannot be used for user-installed apps
