### ISSUE TITLE
ThreadChannelEditMono: add support for appliedTags

### ISSUE THREAD

**Issue by nikolayKeniston** [Discord4J/Discord4J#1268]
**Feature Description:** ThreadChannel has the appliedTags field (only in the raw data field data btw, in the discord documentation the appliced_tags field is described as "the IDs of the set of tags that have been applied to a thread in a GUILD_FORUM or a GUILD_MEDIA channel": https://discord.com/developers/docs/resources/channel#channel-object), however, in ThreadChannelEditMono (сlass result of the ThreadChannel.edit() method) there is no method to edit it. As a result, the bot does not have the ability to edit the tags of the forum channels. It would be great to have a method like ThreadChannel.edit().withAppliedTags(List\<Id\>).

**Justification:** Tag editing is quite an important and useful feature, and I would like to be able to use it.

Additionally, I would like to express my gratitude to this project, before that I had never seen an api library more complicated than the representation of json objects in the form of java classes, the developers really did a lot of work.

**Comment by Azn9** [comment]
Oops that's my bad, I forgot this, I'll fix it asap!

**Comment by Azn9** [comment]
Hey @nikolayKeniston after checking, it seems that this method is already present 🤔 
![image](https://github.com/user-attachments/assets/e8cb76f2-a9b0-440a-8138-105f9b26dd20)

Also, thanks a lot for your message, it is quite a lot of work indeed!

**Comment by nikolayKeniston** [comment]
Thanks for the quick response! On github, there really are methods for appliedTags that are not in https://mvnrepository.com/artifact/com.discord4j/discord4j-core/3.3.0-RC1. Apparently, there is an outdated version in the maven central, but I did not find any more recent releases in the repository or documentation. Where can I get them?

**Comment by Doc94** [comment]
> Thanks for the quick response! On github, there really are methods for appliedTags that are not in https://mvnrepository.com/artifact/com.discord4j/discord4j-core/3.3.0-RC1. Apparently, there is an outdated version in the maven central, but I did not find any more recent releases in the repository or documentation. Where can I get them?

you can try `3.3.0-SNAPSHOT` what handle all the current changes from master.

**Comment by Azn9** [comment]
> Thanks for the quick response! On github, there really are methods for appliedTags that are not in https://mvnrepository.com/artifact/com.discord4j/discord4j-core/3.3.0-RC1. Apparently, there is an outdated version in the maven central, but I did not find any more recent releases in the repository or documentation. Where can I get them?

My bad, indeed the RC1 version is a bit outdated now. As Doc said, you can use the snapshot to access all new features and fixes (see https://docs.discord4j.com/using-snapshots)

**Comment by nikolayKeniston** [comment]
it works, thank you very much!

**Comment by Azn9** [comment]
You're welcome!
