### ISSUE TITLE
Full Deprecated & Removal of Voice Connection Encryption Mode Discord 4J uses, beyond November 18th, 2024

### ISSUE THREAD

**Issue by MJRLegends** [Discord4J/Discord4J#1278]
As per

3.3.x: https://github.com/Discord4J/Discord4J/blob/master/voice/src/main/java/discord4j/voice/VoiceSocket.java#L54
3.2.x: https://github.com/Discord4J/Discord4J/blob/3.2.x/voice/src/main/java/discord4j/voice/VoiceSocket.java#L54

You can see Discord 4J is still using xsalsa20_poly1305_lite, this mode aswell as others are being fully deprecated to the point they will not be able to be used past November 18th, 2024

`The deprecated encryption modes above will be discontinued as of November 18th, 2024. As of this date the voice gateway will not allow you to connect with one of the deprecated encryption modes.`

![6ee79b41415f7971d5bf73582e2a27e4](https://github.com/user-attachments/assets/6e3ae899-494e-4bdc-93dd-ae9a5d3cd404)

**Version:** All Branches, 3.2.x, 3.3.x

**Other:**

**Comment by MJRLegends** [comment]
Discord4J will need updating to the following modes to be able to use past the date, for voice connections
![159569386bfaf33f1bcb060bb5382371](https://github.com/user-attachments/assets/a8008618-5fab-4579-a268-772a146b73af)

**Comment by Doc94** [comment]
Just to add the note this its not just change the value defined this probably need handle the new mode encryption for the session.
