### ISSUE TITLE
Upgrade reactor-netty-http and reactor-netty-core to >=1.1.13

### ISSUE THREAD

**Issue by EternalDeiwos** [Discord4J/Discord4J#1293]
<details>
<summary>Dependency maven:io.projectreactor.netty:reactor-netty-http:1.0.33 is vulnerable</summary>

Upgrade to 1.1.13

GHSA-xjhv-p3fv-x24r,  Score: 7.5

In Reactor Netty HTTP Server, versions 1.1.x prior to 1.1.13 and versions 1.0.x prior to 1.0.39, a malicious user can send a request using a specially crafted URL that can lead to a directory traversal attack.
Specifically, an application is vulnerable if Reactor Netty HTTP Server is configured to serve static resources.

Read More: https://osv.dev/vulnerability/GHSA-xjhv-p3fv-x24r

</details>

<details>
<summary>Dependency maven:io.projectreactor.netty:reactor-netty-core:1.0.33 is vulnerable</summary>

Upgrade to 1.1.13

GHSA-q24v-hpg3-v3jp,  Score: 7.5

In Reactor Netty HTTP Server, versions 1.1.x prior to 1.1.13 and versions 1.0.x prior to 1.0.39, it is possible for a user to provide specially crafted HTTP requests that may cause a denial-of-service (DoS) condition.
Specifically, an application is vulnerable if Reactor Netty HTTP Server built-in integration with Micrometer is enabled.

Read More: https://osv.dev/vulnerability/GHSA-q24v-hpg3-v3jp

</details>

**To Reproduce:** N/A

**Expected Behavior:** Upgrade dependencies to version where CVE is patched.

**Actual Behavior:** Applications are vulnerable to the CVEs linked above.

**Version:** 3.2.7

**Comment by Azn9** [comment]
We don't use the server part, only the client
