### ISSUE TITLE
Error on Bot logout

### ISSUE THREAD

**Issue by ModdyLP** [Discord4J/Discord4J#318]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [Not Sure] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
Sometimes on Logout the Bot Instance I get this errer: 
```
Error while shutting down websocket:
java.lang.NullPointerException
        at sx.blah.discord.api.internal.DiscordWS.shutdown(DiscordWS.java:225)
        at sx.blah.discord.api.internal.ShardImpl.logout(ShardImpl.java:93)
        at sx.blah.discord.api.internal.DiscordClientImpl.logout(DiscordClientImpl.java:348)
        at main.MoMuOSBMain.shutdown(MoMuOSBMain.java:49)
        at main.MoMuOSBMain.access$000(MoMuOSBMain.java:12)
        at main.MoMuOSBMain$1.run(MoMuOSBMain.java:31)
```

### Steps to Reproduce
I cant reproduce, because the error apears random I think.

...

**Expected behavior:** No Error

**Actual behavior:** This Error

**Stacktrace (if applicable):** See top

**Version affected:** 2.8.4

### Additional Information
None

**Comment by Shadorc** [comment]
Steps to reproduce :
1. Log in
2. Wait for client to be ready
3. Wait 5 seconds
4. Call `System.exit(0)` with this shutdown hook : 
```java
Runtime.getRuntime().addShutdownHook(new Thread() {
	@Override
	public void run() {
		client.logout();
	}
});
```

**Comment by danthonywalker** [comment]
You should not logout on shutdown hook for a multitude of reasons. Unfortunately Jetty will actually automatically logout for you anyway on a shutdown hook, but other reasons include that there is no guarantee a shutdown hook is ever called. To properly shutdown just simply logout, any non-daemon threads D4J creates should automatically stop; so assuming you have no other, external non-daemon threads, your process should just shutdown.
