### ISSUE TITLE
Turning off Caching causes NullPointer at Login

### ISSUE THREAD

**Issue by SirSkaro** [Discord4J/Discord4J#322]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
(background)
I'm newly using 2.8.3. I'm having issues getting my bot with 4000+ guilds to boot up. After connecting to a little over 3500 guilds, I get a heap space error (https://hastebin.com/egihiqutel.lua). This issue did not exist with 2.7.x. 

(issue at hand)
It was recommended that I use `setCacheProvider(Cache.IGNORING_PROVIDER)` with my IClientBuilder. However, using this caused me to get this error repeatedly upon booting: https://hastebin.com/pakecimeke.sql. After some discussion on the Discord4J server, I was told I should open a ticket about it.

### Steps to Reproduce
1. `new ClientBuilder().setCacheProvider(Cache.IGNORING_PROVIDER)...login();` when creating the ClientBuilder instance.
2. run

**Expected behavior:** Bot should have attempted to login as normal.

**Actual behavior:** Repeated the same error continuously and no login progress.

**Stacktrace (if applicable):** https://hastebin.com/pakecimeke.sql

**Version affected:** 2.8.3

### Additional Information
I don't allocate resources for guilds in my GuildCreateEvent.

**Comment by phantamanta44** [comment]
The stacktrace paste seems to have expired

**Comment by feldim2425** [comment]
I have the same issue.
Setting the Cache Provider to Cache.IGNORING_PROVIDER throws a NullPointerException at Login
Stacktrace: https://pastebin.com/VHa7tagW
