### ISSUE TITLE
Message could not be sent (Discord didn't return a response)

### ISSUE THREAD

**Issue by ghost** [Discord4J/Discord4J#372]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
Sending a message (IChannel.sendMessage()) after a certain amount of time since the last time (around 15 min in my experience) throws a DiscordException with the message "Message could not be sent (Discord didn't return a response)".

### Steps to Reproduce
1. Register a MessageReceived listener
2. Call MessageReceivedEvent.getChannel().sendMessage()
3. Invoke the command that sends the message, and repeat after 15 minutes

**Expected behavior:** Expected message to send

**Actual behavior:** Throws DiscordException if IChannel.sendMessage() is called after 15 minutes(ish) of non-activity

**Version affected:** 2.9.2

### Additional Information
Not much, but I've always had this issue with Discord4J. Using Java 8 and IntelliJ IDEA 2017.

**Comment by Techtony96** [comment]
I leave my bot running 24/7 and it is only in a few personal guilds, so it only gets used occasionally and I have not had this issue. Can you reproduce this issue on multiple different version of D4J?

**Comment by Techtony96** [comment]
Where are you hosting/running your bot? Is it in a data center (VPS/Dedicated Server)? Or from home?

**Comment by jassiexkanz666** [comment]
I can reproduce it on 2.9.1 with the same steps. I'm hosting it on my computer & RPi3.

**Comment by Techtony96** [comment]
I just tested this on 2.9.1 and was unable to reproduce. @xaanit has said that he has had this problem before and is going to run trace logs to help see what the issue is.

If you know how to run trace logs with D4J, try to reproduce the issue and post the logs here.

**Comment by austinv11** [comment]
I don't personally believe this is anything more than intermittent internet issues. However, configuring your SLF4J logger to log at the TRACE log level along with the "org.apache.http.wire" logger explicitly enabled would be helpful.

**Comment by jassiexkanz666** [comment]
Definitely don't have any internet issues here. Anyway, this just recently started happening, and I find it very weird: https://pastebin.com/4RQPzvfw

**Comment by austinv11** [comment]
It depends totally on your slf4j logger implementation.

**Comment by xaanit** [comment]
https://anna.is-my-waifu.com/35f57a2.png - Average system usage while running
Servers: 1
Bot: Brand new
Version:  fc15b0a
http://beta.speedtest.net/result/6806345037.png - Internet (no one else on)
https://anna.is-my-waifu.com/267e1a5.png - Comp
https://gist.github.com/xaanit/fb8508add31b9f9396906b153259e848 - Logs

**Comment by MrMaleficus** [comment]
Any news on this ?
Here some error logs : https://pastebin.com/6kebsbSe

**Comment by ArsenArsen** [comment]
`java.net.SocketException: Operation timed out (Read failed)` your internet likely snapped.

**Comment by MrMaleficus** [comment]
My internet works fine, i've a the optical fibre
Does the bot needs the opening of certain ports ?

**Comment by ArsenArsen** [comment]
It doesn't. It was either your internet temporarily cutting out or discord, or anything inbetween

**Comment by NorbiPeti** [comment]
I'm consistently having this issue on my PC after a couple minutes. All messages fail to send until it times out (which is another 5-10 minutes), then messages are sent again. I'm on Ubuntu 18.04 x64 with a 100/10 Mbps internet.
However, on our DigitalOcean server running Ubuntu 17.10 x64, this issue isn't present.
Discord4J version is 2.10.1 on both, tried running the same version of my application locally as it is on the server and I still have the issue locally.

**Comment by OrangeFlare** [comment]
I am Also Experiencing this Issue and it is quite annoying
except mine seems to be within Minutes of inactivity like almost 30-60 seconds
My Server is running Java 8 Update 171 64bit
And I am using the latest version
Windows Server 2016 I also had issues with this on Linux Ubuntu 18.04 x64 on Azure but Windows Seems to be having this issue less
This server has a 2Gb/s connection So I HIGHLY doubt it is network connectivity issues
[Here](https://github.com/OrangeFlare/ShrokJava) is a link for my bot's repository in case it helps
Occasionally a message won't send even if the Console is giving output saying that it would and other times it's Discord didn't return a response

**Comment by GrandPanda** [comment]
If you have experienced this issue, please feel free to test the changes made in #463 and provide feedback there if it persists.

**Comment by NorbiPeti** [comment]
#463 seems to resolve this issue for me.
