### ISSUE TITLE
Discord ABNORMAL_CLOSE: firing GuildCreateEvent upon re-establishment?

### ISSUE THREAD

**Issue by Manevolent** [Discord4J/Discord4J#378]
### Prerequisites
* [ ] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [ ] This issue specifically has something to do with Discord4J
* [ ] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
I am using GuildCreateEvent to listen for Guild construction upon start-up.  I'm also using GuildUnavailableEvent to listen for guild connection tear-down on a per-shard basis.  Upon receiving ABNORMAL_CLOSE, this cascades to all of my guilds on that shard disconnecting as I want them to.  However, when ReconnectSuccessEvent fires, I do not receive a GuildCreateEvent.  Is this intended?  I am looking to see if a GuildAvailableEvent could be fired (or GuildCreateEvent).

### Steps to Reproduce
1. Connect to Discord using the D4J API normally.
2. Cause a ABNORMAL_CLOSE event, indicating the reconnect process is supposed to start.
3. Do not receive GuildCreateEvent.

...

**Expected behavior:** [What was supposed to happen]
A GuildCreateEvent should be fired, since we are notified that guilds are unavailable, but never that they become available again.

**Actual behavior:** [What actually happened]
GuildCreateEvent is not fired

**Stacktrace (if applicable):** [PASTEBIN or HASTEBIN link to the stacktrace]

**Version affected:** [The version of Discord4J]
2.9.2

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by danthonywalker** [comment]
Discord does not send GuildCreateEvents when you resume. So this is intended behavior in accordance to replicating Discord's behavior.
That being said it is not unprecedented for us to bend our API to be more convenient and make more semantic sense than what Discord offers.

**Comment by Manevolent** [comment]
I had an ABNORMAL_CLOSE followed by a ReconnectSuccessEvent just now.  I was attempting to reconstruct the guild subsystem I have (specifically, trying to leave a voice channel), and I received the following:

sx.blah.discord.util.DiscordException: Attempt to leave voice channel before shard is ready!
at sx.blah.discord.api.IShard.checkReady(IShard.java:73)
at sx.blah.discord.handle.impl.obj.VoiceChannel.leave(VoiceChannel.java:144)
...
at <my package>.onShardReconnectSucceeded(DiscordPlugin.java:253)
at sx.blah.discord.api.events.EventDispatcher$MethodEventHandler.handle(EventDispatcher.java:680)

Should I be using onShardReadyEvent?  Don't know if I query the list of guilds in that event's shard, that list will be unique to that shard or not.  Also, not sure if that's fired consistently upon both connection and re-connection.
