### ISSUE TITLE
Support for Voice API v3

### ISSUE THREAD

**Issue by kenzierocks** [Discord4J/Discord4J#387]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
Voice API v3, the latest according to Discord documentation, is not supported by Discord4J. This leads to problems with connecting to voice channels that the bot is already in, like on restart, as some opcodes are not properly handled.

### Steps to Reproduce
1. Join a channel with Discord4J
2. Kill the bot
3. Quickly restart the bot and join the channel again, before Discord automatically kicks it.
4. The bot will not send out the proper voice channel connection events.

...

**Expected behavior:** Rejoining a channel after a bot restart works.

**Actual behavior:**  Rejoining a channel does not work entirely, see 4 above.

**Version affected:** 2.9.3

### Additional Information
The specific error I'm getting is this:
`Received unknown voice opcode, {"op":8,"d":{"heartbeat_interval":55000}}`. This is the "hello" opcode in API v3, and I presume what is being incorrectly handled.

**Comment by GrandPanda** [comment]
Voice gateway v3 will likely not be implemented in D4J 2.x. The OP you are seeing is not related to VGW v3 and is instead an undocumented OP for v1.
