### ISSUE TITLE
Threads get stuck in RequestBuffer

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#398]
### Prerequisites
* [X] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [X] This issue specifically has something to do with Discord4J
* [X] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
This issue follows https://github.com/austinv11/Discord4J/issues/390.
After 5h or more on a bot with 5700+ guilds, threads submitted to RequestBuffer stop being executed.

Code used to diagnostic this issue:
```java
Discord4J.LOGGER.trace(LogMarkers.MESSAGES, "Request buffer message. (Channel ID: " + message.getChannel().getLongID() + ")");
return RequestBuffer.request(() -> {
    try {
        Discord4J.LOGGER.trace(LogMarkers.MESSAGES, "Sending message. (Channel ID: " + message.getChannel().getLongID() + ")");
        IMessage request = message.send();
        Discord4J.LOGGER.trace(LogMarkers.MESSAGES, "Message sent. (Channel ID: " + message.getChannel().getLongID() + ")");
        return request;
    } catch (MissingPermissionsException err) {
        //Some error management
    }
    return null;
});
```
`Request buffer message` appeared but not `Sending message`.

This issue is (dirtyly) fixed by replacing in RequestBuffer
```java
 ExecutorService initialExecutor = Executors.newFixedThreadPool(2, DiscordUtils.createDaemonThreadFactory("RequestBuffer Initial Executor"));
```
by
```java
ExecutorService initialExecutor = Executors.newCachedThreadPool(DiscordUtils.createDaemonThreadFactory("RequestBuffer Initial Executor"));
```

### Steps to Reproduce
1. Start a bot (with many guilds ?)
2. Wait a few hours

**Expected behavior:** Tasks submitted to RequestBuffer keep being executed

**Actual behavior:** Tasks submitted to RequestBuffer stop being executed

**Version affected:** dev branch (6c5ebe8)

**Comment by danthonywalker** [comment]
My issue with the fix is that for some reason the RequestBuffer is getting stuck, but why? Adding more threads just delays the problem as eventually you'll have so many stuck threads that creating another one will just OOME.

**Comment by Shadorc** [comment]
Yes, this is why I didn't make a pull request for this, I didn't find the real cause...
