### ISSUE TITLE
Race condition in DispatchHandler leading to NullPointerException on startup

### ISSUE THREAD

**Issue by mstein** [Discord4J/Discord4J#405]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
The change made in baa771529c0083ee482d8534923407e8d9d2bc0d to increase concurrency in the `DispatchHandler` seems to have introduced a race condition on (at least) the client's `ourUser` property.

This property is fetched by the `ready` method upon receiving the `READY` event from Discord, but because some other events can now be executed concurrently, it will sometimes happen that another method will try to access and use the `ourUser` property (with `client.getOurUser()`) before it was being populated by the `ready` method, which will lead to a `NullPointerException`.

It will often happen on `GUILD_CREATE` events when the `guild.loadWebhooks();` instruction is called, because this method will check the permissions on the bot user, and fail if the `client.ourUser` property was not fetched yet.

### Steps to Reproduce
1. Restart the bot until the race condition happen

**Expected behavior:** The `ourUser` property is available to all events happening after `READY`

**Actual behavior:** `GUILD_CREATE` event will sometime throw `NullPointerException` on the `ourUser` access

**Stacktrace (if applicable):** https://pastebin.com/6LL7gVM8

**Version affected:** 2.10.0

**Comment by j0rdanit0** [comment]
I'm experiencing this issue as well. Seems to still be an issue in version 2.10.1

**Comment by SuperJedi224** [comment]
I'm getting this ocassionally as well.

**Comment by SizableShrimp** [comment]
I actually made a PR for this. https://github.com/Discord4J/Discord4J/pull/459
