### ISSUE TITLE
Ban Reason Can't be obtained from the Audit Log.

### ISSUE THREAD

**Issue by ProxyNeko** [Discord4J/Discord4J#411]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/Discord4J/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description  
On user ban an embed is sent to a channel but the reason a user is banned can't be obtained from the audit log even though one is given by the user who performed the ban.

### Steps to Reproduce  
A class was created for the event to send an embed with details of the ban to a channel in Discord [EventUserBanned.java](https://hastebin.com/avefepisox.cs) where I get the reason the user is banned on line 9 and then put that info into the embed on line 23 but when the embed is sent it shows as no reason given every time with and without the timer.

**Expected behavior:**  
I expected the reason the user was banned to show up in the embed but it does not.  
Only a message saying no reason was given displays.  
After I was advised on another Discord4J channel elsewhere that a timer might fix the issue as the reason is not put into the audit log instantly I tried that but it didn't fix the issue.  
(Not sure how true that is as it shows instantly when I check the log but it was worth trying at this rate)

**Actual behavior:**  
The ban reason in the final embed shoes that no reason was given for the user being banned even though a reason was given on multiple attempts.

**Stacktrace (if applicable):**  
No stacktrace was given when issues occurred.

**Version affected:**  
2.10.1 possibly 2.10.0 since I only yesterday updated.

### Additional Information

**Comment by GrandPanda** [comment]
With the following code, "Panda" is printed when [banning my test bot](https://i.imgur.com/qW3vnpP.png ):
```java
public class BanListener implements IListener<UserBanEvent> {
    @Override
    public void handle(UserBanEvent e) {
        String bannedBy = e.getGuild().getAuditLog(ActionType.MEMBER_BAN_ADD).getEntriesByTarget(e.getUser().getLongID()).get(0).getResponsibleUser().getName();
        System.out.println(bannedBy);
    }
}
```

**Comment by mstein** [comment]
@ProxyNeko Your code always call `.get(0)` on the returned list of `getEntriesByTarget`, but the list returned is not sorted so the first element of the list is not guaranteed to be "the most recent targeted entry". The issue may be that you're getting an older TargetedEntry that does not have a reason on it. If you're testing your code by banning the same user over and over again, that's likely the problem.

Can you try by sorting the list returned by `getEntriesByTarget` on the entry longID in desc order before getting the first entry ? Something that would look like (untested code, but that's for the example) : 

```groovy
TargetedEntry entry = event.getGuild().getAuditLog(ActionType.MEMBER_BAN_ADD)
    .getEntriesByTarget(event.getUser().getLongID())
    .stream()
    .sorted(Comparator.comparing(TargetedEntry::getLongID).reversed())
    .findFirst()
    .get();
String banReason = entry.getReason().orElse("No reason");
String bannedBy = entry.getResponsibleUser().getName();
```

**Comment by ProxyNeko** [comment]
I have tried editing my class to look a little like @GrandPanda's and the error still persists even in a console but still nothing yet [EventUserBan.java](https://hastebin.com/evokofofoj.java) I'll give the one above a try and see if that prevents the issue because I am using a test user of mine.

**Comment by ProxyNeko** [comment]
Using @mstein's suggestion worked so I assume that this is an error that no one has seen before then. Is it likely this is all on my end or can this be improved upon in any way? Doubt so as it seems all on me here :s

**Comment by GrandPanda** [comment]
We should order it on our side.

**Comment by ProxyNeko** [comment]
I failed to notice one thing somehow but this 
```java
TargetedEntry entry = event.getGuild().getAuditLog(ActionType.MEMBER_BAN_ADD)
    .getEntriesByTarget(event.getUser().getLongID())
    .stream()
    .sorted(Comparator.comparing(TargetedEntry::getLongID).reversed())
    .findFirst()
    .get();
```
gets the second last ban reason in each of the three times I tested it just now not sure how.

**Comment by mstein** [comment]
From what you're describing, your `getEntriesByTarget` seems to skip the first element of your list. That's why you get an error on a user you ban for the first time, because `findFirst()` returns an `Optional`, so if there was no entry in the list (as, the only entry of the list was somehow skipped), calling `get` will throw that exception (you should use `.orElse(<value>)` instead by the way, my sample code was just for testing). 

I'm not sure why you have an entry being skipped though, I can't reproduce that on my side, I always get the latest entry with the right ban reason.

**Comment by ProxyNeko** [comment]
That's where I got confused as I use orElse for the banReason String below
```java
String banReason = entry.getReason().orElse(bannedBy + " banned " + event.getUser().mention() + " without a reason.");
```
[Full event class](https://hastebin.com/arixezarof.swift)

**Comment by mstein** [comment]
Yes, you got that part covered, but I was talking about the `.findFirst()` on the TargetedEntry stream.
```groovy
TargetedEntry entry = event.getGuild().getAuditLog(ActionType.MEMBER_BAN_ADD).getEntriesByTarget(event.getUser().getLongID())
    .stream()
    .sorted(Comparator.comparing(TargetedEntry::getLongID).reversed())
    .findFirst() // return an Optional<TargetedEntry>
    .get(); // if the source list was empty, this will throw a "no value" error, so you'd want to use a .orElse(null) or something here
```
But the main issue is that it's missing an entry. Maybe look at all the returned entries from the `getEntriesByTarget` (loop on each entry and print their reason for example, or use a debugger) to check if the one you're looking for is in the list, if it's not then I don't know why :p
