### ISSUE TITLE
Ability to retrieve 'recommended' shard count (v3)

### ISSUE THREAD

**Issue by FerusGrim** [Discord4J/Discord4J#421]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/Discord4J/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
Currently, while building your client(s), there's no way built-in way to query Discord for the recommended shard count that your bot should be using.

This issue has been talked about a bit on the D4J Discord server and it seems that the particular issue facing this feature is, quoted from @GrandPanda:

>right, the easiest way it will be achievable is by constructing the RestClient, making the request using the stuff we have built there, and then giving that RestClient to the client builder so it can reuse it. **That last step isnt possible yet**

Obviously this is a known issue that needs to be resolved, I'm just posting it here so that the people interested in this feature can more easily receive updates about it.

...

**Version affected:** Every v3 build, so far, as to the posting of this issue (specifically: 7fed595 )

**Comment by ArsenArsen** [comment]
I don't think doing it manually is such a problem, especially if it requires big refactoring in D4J, since Discord does provide an endpoint to determine the count.

**Comment by FerusGrim** [comment]
@ArsenArsen I haven't made a suggestion one way or another as to whether D4J should, or even can realistically, provide this as just another builder method. I was just providing context for the current obstacle as described by one of the major maintainers of the project.

Personally I don't care if I have to make this call outside of the normal building scope, so long as D4J provides the tools to do so.

It seems over the top that I should have to build a JSON object to define my request, send if off using whatever _other_ none D4J library there is to make requests over an API, and parse the response for a single but extremely important integer.

**Comment by quanticc** [comment]
Closed via 1875aeb8000eead4a3da49c1f12139290176808e

Look for this test files for now for examples: https://github.com/Discord4J/Discord4J/blob/v3/core/src/test/java/discord4j/core/RetryBotTest.java#L82-L99
