### ISSUE TITLE
Fully Implement rest Service methods in core

### ISSUE THREAD

**Issue by GrandPanda** [Discord4J/Discord4J#424]
The following methods should be accessible to users of core through the appropriate entities:

### Application
- [x] getCurrentApplicationInfo

### Audit Log
- [x] getAuditLog 

### Channel
- [x] getChannel
- [x] modifyChannel
- [x] deleteChannel
- [x] getMessages
- [x] getMessage
- [x] createMessage
- [x] createReaction
- [x] deleteOwnReaction
- [x] deleteReaction
- [x] getReactions
- [x] deleteAllReactions
- [x] editMessage
- [x] deleteMessage
- [x] bulkDeleteMessages
- [x] editChannelPermissions
- [x] getChannelInvites
- [x] createChannelInvite
- [x] deleteChannelPermission
- [x] triggerTypingIndicator
- [x] getPinnedMessages
- [x] addPinnedMessage
- [x] deletePinnedMessage
- [x] ~~addGroupDMRecipient~~
- [x] ~~deleteGroupDMRecipient~~

### Emoji
- [ ] getGuildEmojis
- [x] getGuildEmoji
- [x] createGuildEmoji
- [x] modifyGuildEmoji
- [x] deleteGuildEmoji

### Gateway
- [x] getGateway
- [ ] getGatewayBot (Related: #421)

### Guild
- [x] createGuild
- [x] getGuild
- [x] modifyGuild
- [x] deleteGuild
- [x] getGuildChannels
- [x] createGuildChannel
- [ ] modifyGuildChannelPositions
- [x] getGuildMember
- [x] getGuildMembers
- [x] addGuildMember
- [x] modifyGuildMember
- [x] modifyOwnNickname
- [x] addGuildMemberRole
- [x] removeGuildMemberRole
- [x] removeGuildMember
- [x] getGuildBans
- [x] getGuildBan
- [x] createGuildBan
- [x] removeGuildBan
- [x] getGuildRoles
- [x] createGuildRole
- [x] modifyGuildRolePositions
- [x] modifyGuildRole
- [x] deleteGuildRole
- [x] getGuildPruneCount
- [x] beginGuildPrune
- [x] getGuildVoiceRegions
- [x] getGuildInvites
- [x] ~~getGuildIntegrations~~
- [x] ~~createGuildIntegration~~
- [x] ~~modifyGuildIntegration~~
- [x] ~~deleteGuildIntegration~~
- [x] ~~syncGuildIntegration~~
- [x] ~~getGuildEmbed~~
- [x] ~~modifyGuildEmbed~~

### Invite
- [x] getInvite
- [x] deleteInvite

### User
- [x] getCurrentUser
- [x] getUser
- [ ] modifyCurrentUser
- [x] getCurrentUserGuilds
- [x] leaveGuild
- [ ] ~~getUserDMs~~
- [x] createDM
- [ ] ~~createGroupDM~~
- [ ] ~~getUserConnections~~

### Voice
- [x] getVoiceRegions

### Webhook
- [x] createWebhook
- [x] getChannelWebhooks
- [x] getGuildWebhooks
- [x] getWebhook
- [x] modifyWebhook
- [x] deleteWebhook

**Comment by danthonywalker** [comment]
`getGuildEmojis` is impossible without a `findAll` added to Stores. The reasoning is because we need to be able to bulk-retrieve by IDs, checking if they all exist in Stores and if not, we can hit the endpoint. Otherwise we get what the current solution is now, and just going one-by-one grabbing IDs.

**Comment by danthonywalker** [comment]
Closing this issue as everything that isn't currently implemented is either outside of core's/Discord4J's functionality or doesn't impact core's functionality (`getGuildEmojis`).
