### ISSUE TITLE
Working on Wiki

### ISSUE THREAD

**Issue by quanticc** [Discord4J/Discord4J#425]
## Main articles
- [x] Getting Started
- [x] Lambda tutorial
- [x] Migration guide
- [x] Specs
- [x] Using Jitpack
- [x] Making a bot
- [x] Reactive tutorial
- [x] Logging
- [x] Sharding
- [x] Threading
- [x] FAQ
- [x] Update sidebar
- [x] Error handling
- [ ] Stores primer

## Cookbook items
- [ ] Sending a message from DiscordClient
- [ ] Working with permissions

**Comment by quanticc** [comment]
We have a sidebar section called WIP or incubating pages, currently including:

- Getting Started
- Basic bot
- Reactor (Reactive) Tutorial
- Logging
- Sharding
- Threading
- FAQ

We should move them into the normal categories, what do you think? @danthonywalker @xaanit

**Comment by danthonywalker** [comment]
Getting Started and Basic Bot I will probably scrap when I finish [Music Bot Tutorial](https://github.com/Discord4J/Discord4J/wiki/Music-Bot-Tutorial) as I feel this in particular encompasses everything those two pages are after.

Reactor Tutorial needs an overall. Personally wouldn't promote in a while.

Logging, sharding, and threading are not my topics. If you feel they're ready then that's that.

FAQ is sparse. Needs more things and just a cleaner overall standard.

In general the wiki should be a very pristine high standard of documentation on our part.

**Comment by quanticc** [comment]
Adding some tasks
- [ ] Improve Sharding page with v3.1 API and details about supported distributed architectures
- [ ] Update BOM instructions now that Gradle has native support for it

**Comment by quanticc** [comment]
We have to update many sections of our current Wiki in preparation for v3.1

so far we have new pages:
https://github.com/Discord4J/Discord4J/wiki/Migrating-from-v3.0-to-v3.1
https://github.com/Discord4J/Discord4J/wiki/What's-new-in-v3.1

But some require a refresher to keep them up to date with the new version. These will be tracked as separate tickets.
