### ISSUE TITLE
Ergonomics of Optional

### ISSUE THREAD

**Issue by GrandPanda** [Discord4J/Discord4J#430]
There has been some concerns about the use of `java.util.Optional` throughout v3 and its user-friendliness. I thought I would make this issue to provide a common place for discussion and document some of these concerns.

## The Problem
Let's take the example from the readme:
```java
client.getEventDispatcher().on(MessageCreateEvent.class)
        .map(MessageCreateEvent::getMessage)
        .filter(msg -> msg.getContent().map(content -> content.equals("!ping")).orElse(false))
        ...
```
The complaints center around the complexity of the predicate:
```java
msg -> msg.getContent().map(content -> content.equals("!ping")).orElse(false)
```
This is a lot of boilerplate for the idea we really want to express: `content.equals("!ping")`. However, we gain safety in the comfort of knowing that our code functions properly when a message has no content. 

Can we achieve this safety in a more ergonomic fashion?

### ~~Null~~
Just use `null` instead! Regardless of the many arguments against null in general (no need to go all "billion dollar mistake" on us, we've heard it all before), this simply isn't a viable option when working with Reactor. Every input into Reactor types is null checked and will fail fast. This means even simple constructions like this are unsafe, with no error or even warning:
```java
on(MessageCreateEvent.class)
  .map(e -> e.getMessage().getContent())
```
This limitation completely disqualifies this solution in my opinion.

### Empty values
Just use `""` instead! I think this solution gets further than `null`, but not by much. For many things it works quite nicely. We can express our message content predicate simply as `msg.getContent().equals("!ping")` which is what we wanted! 

However, this is really only viable for certain things. It's really a happy coincidence that for Discord there is no difference between "message has empty content" and "message no content." This does not hold for all situations and not all types have empty values.

Perhaps this solution could be applied to a few select, commonly used methods, but mixing two philosophies of handling empty return can be confusing for users. Can we do better?

### Higher level utilities
Reactor is quite extensible. It provides many techniques through one can create quite elegant-looking code. One such technique is through the method `transform()`.

Using this method, we can write functions which look almost like built in operators. One could define a method:
```java
public static <T, U> Function<? super Flux<T>, ? extends Publisher<T>> filterOrEmpty(Function<T, Optional<U>> extractor, Predicate<U> predicate) {
    return flux -> flux.filter(t -> extractor.apply(t).filter(predicate).isPresent());
}
```
and use it like so:
```java
client.getEventDispatcher().on(MessageCreateEvent.class)
        .map(MessageCreateEvent::getMessage)
        .transform(filterOrEmpty(Message::getContent, "!ping"::equals))
        ...
```
This effectively factors out some of the use-site boilerplate and brings the actual logic more to center stage.

While this solution is not perfect, it gives back control to the user and allows us to retain a subjectively more "correct" type.

**Comment by danthonywalker** [comment]
`null` is out of the question.

I think it's intuitive to use empty content instead of Optional in cases where that logic applies and I think it is reasonable to mix the two philosophies. As you said, it is a coincidence that for all intents and purposes an empty content is the same as no content. As an user, I think making any such distinction in our API is needless complexity, however, if it *does* make a difference then Optional is clearly superior. The only two places I think there truly is no such distinction is Message#getContent and TextChannel#getTopic. Maybe should make a list on qualifying methods.

I think the bigger worry is the distinction doesn't exist in receiving but it does for sending. IIRC, sending empty string in message creates and edits does results in errors from Discord, which may not be intuitive logically of it works for receiving, but not sending. I don't think this is as big of an issue, however.

**Comment by JamesGallicchio** [comment]
If I might contribute my two cents...

Having special rules for common methods to "fix" this is honestly very bleh. I hate memorizing little things like "Oh it returns an empty string if the content isn't there." And if someone really wants to handle it as an empty string, they can simply `.orElse("")` followed by whatever logic they want to have:
```java
client.getEventDispatcher().on(MessageCreateEvent.class)
        .map(MessageCreateEvent::getMessage)
        .filter(msg -> msg.getContent().orElse("").equals("!ping"))```

Building on what Panda said, we can use Reactor to our advantage even without `.transform`. Reactor supports some integration with Java Iterables; we could implement our own Option class that extends Iterable (more on that below), and then do something like this:
```java
client.getEventDispatcher().on(MessageCreateEvent.class)
        .map(MessageCreateEvent::getMessage)
        .flatMapIterable(Message::getContent)
        .filter("!ping"::equals)
        ...```

This is very elegant, in my opinion.

And to me, this kills two birds with one stone. Optional in Java is lowkey broken. Java 9 [adds multiple Optional utility methods](http://www.baeldung.com/java-9-optional) to alleviate some of the ouch of using it, but the class is poorly designed in general. Instead we can use our own implementation, whether taken from somewhere or our own "homebrew" Option. It's an easy class to implement, really:

```java
public class Option<T> implements Iterable { // Could be implement other collection interfaces
    private final T value; // nullable
    private Option(T value) { this.value = value; }

    public static <T> Option<T> ofNullable(T value) {
        if (value == null) return emptyObj;
        else return new Option<T>(value);
    }
    public static <T> Option<T> of(T value) {
        if (value == null) throw new IllegalArgumentException();
        else return new Option<T>(value);
    }

    private static final Option<Object> emptyObj = new Option(null);
    public static <T> Option<T> empty() {
        return emptyObj;
    }

    // Now all the methods that can be called on Options
    public boolean isEmpty() { return value == null; }
    public boolean isDefined() { return value != null; }

    // Important: distinct from orElse
    public T getOrElse(Supplier<T> s) { // Can have an overloaded version to accept just T
        if (isEmpty()) return s.get();
        else return value;
    }

    public Option<T> orElse(Supplier<Option<T>> s) { // Can have an overload to accept Option<T>
        if (isEmpty()) return s.get();
        else return this;
    }

    // All your monadic ops
    public <U> Option<U> map(Function<T, U> func) {
        if (isEmpty()) return emptyObj;
        else return new Option<U>(func.accept(value));
    }
    public <U> Option<U> flatMap(Function<T, Option<U>> func) {
        if (isEmpty()) return emptyObj;
        else return func.accept(value);
    }
    public Option<T> filter(Predicate<T> p) {
        if (isEmpty() || !p.accept(value)) return emptyObj;
        else return this;
    }   

    // For users who aren't used to monads (you can get the same behavior from map)
    // Notice that it still allows for chaining
    public <T> Option<T> ifPresent(Consumer<T> c) {
        if (isDefined()) c.accept(value);
        return this;
    }

    public <T> Option<T> ifAbsent(Runnable<T> r) {
        if (isEmpty()) r.run();
        return this;
    }

    // Iterable stuff
    public void forEach(Consumer<T> action) {
        this.map(action);
    }
    public Iterator<T> iterator() {
        return new Iterator<T> {
                private T t = value;
                public boolean hasNext() { return t != null; }
                public T next() {
                    if (t != null) {
                        return t;
                        t = null;
                    } else throw new NoSuchElementException();
                }
            }
    } 
}```

**Comment by danthonywalker** [comment]
I am going to have to highly disagree on it being elegant. We would have to construct this entire class, which wouldn't be compatible with other APIs `Optional`, replace all instances of `Optional` with this, just so we can play a bit nicer with Reactor.

Empty content makes just as much sense as `Optional`. If your system wouldn't parse a present `Optional` it wouldn't parse an empty `String` either.

**Comment by quanticc** [comment]
I'm okay with Optional. Static utilities are good too and they help teaching about `transform` operator.

**Comment by austinv11** [comment]
I think optional makes sense in this context, static utility "operators" are fine, but I think they would be a little too obscure for most users.

**Comment by GrandPanda** [comment]
We'll continue on with Optional and add static utilities to aide the user in common cases.
