### ISSUE TITLE
Role#getPosition() returns -1

### ISSUE THREAD

**Issue by jerzabek** [Discord4J/Discord4J#437]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/Discord4J/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
Whenever I call the getPosition method it returns -1, even though the getRawPosition method works as intended

### Steps to Reproduce
1. Start a basic bot, even the example will do
2. Get access to some Member
3. Subscribe to getRoles()
4. try to log the value of getPosition()

**Expected behavior:** Expected the correct position number for that role

**Actual behavior:** the method just returns -1

**Stacktrace (if applicable):** https://pastebin.com/DgwhYrZ8

**Version affected:** aa78f82
### Additional Information
Already talked to the devs on the discord servers, this is just formality.

**Comment by danthonywalker** [comment]
216106f should fix this problem as indexOf should never return -1 now because of unequal instance matching
