### ISSUE TITLE
Audit Log Reasons

### ISSUE THREAD

**Issue by danthonywalker** [Discord4J/Discord4J#451]
## The Problem
https://discordapp.com/developers/docs/resources/audit-log#audit-logs
> Whenever an admin action is performed on the API, an entry is added to the respective guild's audit log. You can specify the reason by attaching the `X-Audit-Log-Reason` request header. This header supports url encoded utf8 characters.

This issue is present in v2 and v3, but v2 will be ignored for this discussion.

## Alternatives
The only solution I can think of currently is to allow reasons to be specified in all relevant specs, and for actions which do not have specs (`Member#kick`), provide an additional overload to allow specifying a reason. API wise for the user, this isn't terrible, but implementing it can be a problematic for us.

Currently, there is no way to add/remove/override headers for individual requests, so this should also be discussed.

## Audit log actions
- [ ] GUILD_UPDATE
- [ ] CHANNEL_CREATE
- [ ] CHANNEL_UPDATE
- [ ] CHANNEL_DELETE
- [ ] CHANNEL_OVERWRITE_CREATE
- [ ] CHANNEL_OVERWRITE_UPDATE
- [ ] CHANNEL_OVERWRITE_DELETE
- [ ] MEMBER_KICK
- [ ] MEMBER_PRUNE
- [ ] MEMBER_BAN_ADD
- [ ] MEMBER_BAN_REMOVE
- [ ] MEMBER_UPDATE
- [ ] MEMBER_ROLE_UPDATE
- [ ] ROLE_CREATE
- [ ] ROLE_UPDATE
- [ ] ROLE_DELETE
- [ ] INVITE_CREATE
- [ ] INVITE_UPDATE
- [ ] INVITE_DELETE
- [ ] WEBHOOK_CREATE
- [ ] WEBHOOK_UPDATE
- [ ] WEBHOOK_DELETE
- [ ] EMOJI_CREATE
- [ ] EMOJI_UPDATE
- [ ] EMOJI_DELETE
- [ ] MESSAGE_DELETE

**Comment by quanticc** [comment]
I think it should be made simple: new method to specs for reason and adding a header parameter to Rest service methods, without overload.

**Comment by danthonywalker** [comment]
Assuming you mean adding a `@Nullable String reason` parameter, I'm ok with this.
