### ISSUE TITLE
Bot only receieves audio when connected to Central Europe

### ISSUE THREAD

**Issue by Olical** [Discord4J/Discord4J#452]
### Prerequisites
* [ ] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/Discord4J/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description

I have a voice activated bot relying on the v2 (I think) API for receiving and sending audio. This works absolutely fine when the Discord server in question is hosted in Central Europe. If it's hosted anywhere else my IAudioReceiver/receive method is never called. [Source here](https://github.com/Olical/snowball/blob/a65c8f9219874456863747380456672c9f5ff87d/src/clojure/snowball/discord.clj#L130-L135) (it's Clojure but it makes no difference).

### Steps to Reproduce
1. Connect the bot to my server in Central Europe, say "hey snowball" and get a response.
2. Move the server to Western Europe (or South Africa etc) and observe that the receive method is _never_ called despite the subscription being called.

...

**Expected behavior:** Receive should be called regardless of server region.

**Actual behavior:** Audio is only received when connected to Central Europe.

**Stacktrace (if applicable):** No errors are observed, the lines for subscription are called in all cases though.

**Version affected:** `2.10.1`

### Additional Information

I had another user try it with their own server and their own bot, it only works in Central Europe for them too. If you think this is definitely my code's fault (I have no idea how, it's not aware of regions at all) do you have any tips on diagnosing the issue?

I contacted Discord to see if they had any issues with sending audio to bots in some regions but they said they don't offer help with anything to do with bots, as kind of expected.

Thanks a lot.

**Comment by BenjaminUrquhart** [comment]
These may be of interest
https://github.com/DV8FromTheWorld/JDA/issues/789
https://github.com/discordjs/discord.js/issues/2929

**Comment by GrandPanda** [comment]
Discord has made it clear that they do not support bots receiving audio. See the corresponding v3 information: #479
