### ISSUE TITLE
Queue Requests When Rate Limited

### ISSUE THREAD

**Issue by Selim042** [Discord4J/Discord4J#458]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [X] This issue specifically has something to do with Discord4J
* [X] I have attempted to [look for similar issues](https://github.com/Discord4J/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
Would it be possible to add a queue for outgoing messages to be sent when the bot is no longer being rate limited with an optional extra paramater to functions to ignore if limited?

**Expected behavior:** Sends message when no longer limited

**Actual behavior:** Message fails to send

**Version affected:** Latest

**Comment by xaanit** [comment]
Have you read [this](https://discord4j.readthedocs.io/en/latest/RateLimitExceptions-and-you/) page?

**Comment by Selim042** [comment]
Oh, sorry
