### ISSUE TITLE
ArrayIndexOutOfBoundsException when retrieving Audit Log

### ISSUE THREAD

**Issue by jerzabek** [Discord4J/Discord4J#460]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/Discord4J/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
When trying to retrieve audit log entries for a specific guild, no matter how the AuditLogQuerySpec is set up, after emitting all the entries an ArrayIndexOutOfBoundsException is thrown.

### Steps to Reproduce
1. Create a bot from the basic example in the README
2. Attempt to call Guild#getAuditLog, for example when the GuildCreateEvent is fired

**Expected behavior:** Requested audit log entries to be emitted and the flux should complete successfully.

**Actual behavior:** After all audit log entries are emitted the getAuditLog Flux throws an ArrayIndexOutOfBoundsException

**Stacktrace (if applicable):** [stacktrace - the error is at the bottom of the file f.y.i.](https://pastebin.com/5X1ymQQT)

**Version affected:** ```2754b2d6b3```

**Comment by GrandPanda** [comment]
Can you confirm fe58c1d fixes this?

**Comment by GrandPanda** [comment]
That's not related to this issue. I've opened a new one.
