### ISSUE TITLE
V3 gateway is monotonically inaccurate

### ISSUE THREAD

**Issue by koyagami** [Discord4J/Discord4J#464]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY) - this is not really discussable as much as it is a potential issue regarding timing internally.
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/Discord4J/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
The gateway ack timestamp is set using a non-monotonic time source, which can potentially lead to zero or negative acknowledgement timestamp differences.

### Steps to Reproduce
1. Have the system send an ACK
2. Have a leap second occur or have the system clock adjust
3. Receive the response
4. The duration between the start and end may potentially be inaccurate.

### Why?

https://github.com/Discord4J/Discord4J/blob/v3/gateway/src/main/java/discord4j/gateway/GatewayClient.java#L139
```java
lastAck.set(System.currentTimeMillis());
```
[Java's documentation for this call](https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#currentTimeMillis--) defines this as the time that has passed since Unix epoch, __NOT__ the monotonic system time. This means that if the System clock goes back, then the timestamp will also go back, which makes it unsuitable for timing.

Additionally, operating systems are not guaranteed to have a decent granularity for this value. If we are using this to measure time periods, this may have an error of the order of ±10ms.

This is an unlikely issue to occur, and most of the time will work without issue, but we might as well ensure that it always functions correctly!

### Solution

My proposed solution is to switch to using `System.nanotime` for ack measurements, since this will always attempt to use the highest precision standard system clock resource. Quoting the documentation (since this is easier than rewording what is already explained well): `This method can only be used to measure elapsed time and is not related to any other notion of system or wall-clock time [...] This method provides nanosecond precision, but not necessarily nanosecond resolution (that is, how frequently the value changes) - no guarantees are made except that the resolution is at least as good as that of currentTimeMillis().`

This brings along three additional things that need to be looked into:

1. The current implementation expects this ack to be in milliseconds. The new solution will be in nanoseconds and will thus be breaking to anything existing that relies on this.
    - Solution: divide by 1 million to ensure this is in the correct unit.
2. The current implementation expects this ack to be based from Unix epoch. The new solution will
    be relative to some arbitrary epoch instead. Quoting the documentation again: `The value returned represents nanoseconds since some fixed but arbitrary origin time (perhaps in the future, so values may be negative). The same origin is used by all invocations of this method in an instance of a Java virtual machine; other virtual machine instances are likely to use a different origin.` 
    - Proposed solution: keep the existing call to millis for backwards compatibility if desired. Implement the monotonic solution internally and provide new accessors for this. Migrate the gateway logic to use this value instead.
    - This would also remove the need for the extra calculations produced by (1)
3. Does anywhere else in this API have this issue?
    - Proposed solution: I will take a look and see if I can find anywhere else, then report back :)

**Version affected:** [The version of Discord4J] v3-SNAPSHOT

Hope I have included the correct information, and that I haven't missed anything! Thanks :)

**Comment by quanticc** [comment]
Are you open to make a PR? There are no assumptions at the moment for the acks to be based off unix epoch, we only care about measuring elapsed time or comparing values so we could just replace with nanoTime + adding the proper conversion as we log in milliseconds in a couple of places.

@Discord4J/members what do you think?

**Comment by koyagami** [comment]
@quanticc already on it, just about to push the changes! Watch this space.

**Comment by quanticc** [comment]
I patched one of the issues so we can focus on the specific nanoTime related modifications here.
