### ISSUE TITLE
Presence is empty when a member is offline

### ISSUE THREAD

**Issue by Techtony96** [Discord4J/Discord4J#470]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [x] This issue specifically has something to do with Discord4J
* [x] I have attempted to [look for similar issues](https://github.com/Discord4J/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
When getting the presence of a user the returned value is an empty Mono when the user is offline. The default behavior should be that the user is Offline.

### Steps to Reproduce
1. Query an offline user's (not invisible) presence.

**Expected behavior:** Mono<Presence> is returned with Offline status

**Actual behavior:** Mono<Presence> is empty

**Stacktrace (if applicable):** [PASTEBIN or HASTEBIN link to the stacktrace]

**Version affected:** v3 6252e8f94d11d63790530519e7c14df525151d19

### Additional Information
Will try to follow up with a test requested by @danthonywalker 
Go offline after the bot has started, what is the Presence value?

**Comment by danthonywalker** [comment]
Something to consider is the Javadoc warning on the presence methods (and this could equally apply to VoiceStates). For no-op store users, or if the bot is offline, then defaulting to an offline presence can potentially be an incorrect value.

So we have 2 solutions. The first is just do nothing, letting users handle it in their own way (.defaultIfEmpty even if it can potentially be incorrect), or we can set a default presence for members on member receives, but this will consume quite a bit more memory.

**Comment by danthonywalker** [comment]
be57c36 provides a proper fix, works for both chunk and non-chunking scenarios.
Please test.

**Comment by quanticc** [comment]
@Techtony96 Please re-open if you still have issues.
