### ISSUE TITLE
Bot's presence is not updated using Member#getPresence

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#475]
### Prerequisites
* [X] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [X] This issue specifically has something to do with Discord4J
* [X] I have attempted to [look for similar issues](https://github.com/Discord4J/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
The bot's presence is not updated when using `Member#getPresence` but the presence of the other members are updated.
This is because Discord does not send an event when the bot updates its own presence, Discord4J has to handle it itself.

### Steps to Reproduce
1. Connect with an initial presence
2. Update this presence
3. Get the bot presence

**Expected behavior:** The new presence is returned.

**Actual behavior:** The old presence is returned.

**Version affected:** 3.0.7

**Comment by GrandPanda** [comment]
The problem with this is that there's no way to really know what the bot's own presence is because it can be changed from another client on the same shard.

**Comment by darichey** [comment]
Perhaps a more relevant issue with supporting this is that we get no feedback from Discord if we try to status update but are ratelimited. The request is simply ignored. Therefore, we would have to try to keep track of that ratelimit in order to accurately know what the current self presence is. This isn't necessarily completely a bad thing, as it would mean we could provide feedback in `DiscordClient#updatePresence()`.

**Comment by Shadorc** [comment]
This issue could be fixed by checking if the member is the current user in `Member#getPresence` and then request a guild member using https://discordapp.com/developers/docs/topics/gateway#request-guild-members-guild-request-members-structure with presences set to true (if GUILD_PRESENCES intent is enabled, otherwise returns empty).

**Comment by quanticc** [comment]
I think that suggestion makes sense. what do you think @danthonywalker @darichey
