### ISSUE TITLE
PortUnreachableException with voice

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#477]
### Prerequisites
* [X] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [X] This issue specifically has something to do with Discord4J
* [X] I have attempted to [look for similar issues](https://github.com/Discord4J/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
After a few hours, a PortUnreachableException is thrown when using voice.
This doesn't seem to come from a prolonged sending of audio data or a prolonged pause.

### Steps to Reproduce
1. Join a voice channel
2. Unknown

**Expected behavior:** No error

**Actual behavior:** A PortUnreachableException  is thrown

**Stacktrace (if applicable):**
https://pastebin.com/wD6tbHp3: recvfrom() failed
https://pastebin.com/51uG2Cni: readAddress(..) failed: Connection refused

**Version affected:**
3.0.2

### Additional Information
I have updated this issue multiple times so the comments below may not be related to the current description.

**Comment by GrandPanda** [comment]
Not sure if related but thought I would mention it: in v2, we have a keep alive thread which sends data on the udp socket periodically. This isn't currently present in v3.

Do you know if this exception occurs after long periods of no transmission?

**Comment by Shadorc** [comment]
I tried to reproduce this issue, I started a music and stopped it during 1 hour, no error shown.
I have also tried to send silence instead of nothing using this code:
```java
@Override
public boolean provide() {
	boolean didProvide = this.audioPlayer.provide(this.frame);
	if (!didProvide) {
		this.getBuffer().put(new byte[] {(byte) 0xF8, (byte) 0xFF, (byte) 0xFE});
	}
	this.getBuffer().flip();
	return true;
}
```

This did not work.
I don't know if it's relevant but in 15 hours I got this error 13.436 times.
Also, but I'm not sure if it is linked, my shards stop reconnecting after a while, getting stuck on `Retry attempt ... in ... ms` but I keep getting this error.

**Comment by GrandPanda** [comment]
Can you update the paste, it's gone.

**Comment by Shadorc** [comment]
Stacktrace updated.

**Comment by Shadorc** [comment]
It seems that this error happens only after a client reconnection (due to WebSocket closed: 1000 in my case but I don't know if it is only with this code)

**Comment by Shadorc** [comment]
I was not able to reproduce this issue since the default shedulers for `Flux#interval` and `Mono#delay` have been changed to elastic. 
I will close this issue and re-open if it happens again.
