### ISSUE TITLE
Proposal: Create a Spec for DiscordClient#login

### ISSUE THREAD

**Issue by danthonywalker** [Discord4J/Discord4J#483]
Issue #421 is hard to implement because it requires having a `RestClient` available before a `DiscordClient` is built *and* do a request for the shard count, which is currently impossible. A way to go about this issue is create a factory `DiscordClientBuilder` method that returns a `Mono<DiscordClientBuilder>` which builds the `RestClient` and does the request and sends that information to `DiscordClientBuilder`.

This is *fine*, but not very clean, in my opinion.

I think a better way to approach this problem is to create a Spec for `login` that accepts shard index, shard count, presence, and whatever other properties now or in the future the user wants to provide for an identify.

`DiscordClientBuilder` is currently designed the way it is because it models almost exactly as v2. However, logically, it makes no sense for an user to provide the identify properties at the builder level as that information isn't really required until we need to identify, which happens at `login`. `DiscordClient` in v3 unlike in v2 can operate without being connected to the gateway, so it can act as an abstracted `RestClient`. It logically follows we can provide an endpoint to retrieve the recommend shard count in `DiscordClient` which users may optionally use when wanting to login. Something like this:
```java
DiscordClient client = new DiscordClientBuilder(token).build();
client.getRecommendedShardCount()
    .flatMap(shardCount -> client.login(spec -> {
        client.setShardIndex(someIndex);
        client.setShardCount(shardCount);
    })).block();
```
Or, even better, is we can have the Spec define a property to automatically obtain that information.
```java
client.login(spec -> spec.useRecommendedShardCount(true)).block();
```
Which will do the above automatically.

This proposal of course means we remove some methods in `DiscordClientBuilder`. Shard count, shard index, and presence most notable.

**Comment by quanticc** [comment]
The changes implemented in #564 should satisfy this proposal. If not please reopen for more discussion.
