### ISSUE TITLE
Core Javadocs

### ISSUE THREAD

**Issue by SizableShrimp** [Discord4J/Discord4J#489]
Many of the classes in `core` have methods that are undocumented. This issue is meant to track which classes still need methods documented. As development of v3 continues, classes on this list can be removed from this list. This list is subject to change with the addition/removal of classes to v3 and each subsequent commit which finishes javadocs for a class.

The list is ordered with specs as the first priority, then events, entities, and miscellaneous. For each package category, the classes are then ordered from the most methods undocumented to the least.

Updated list as of commit `25c833d`.

- discord4j.core.spec.VoiceChannelJoinSpec.java (1)
- discord4j.core.spec.Spec.java (1)
- discord4j.core.event.domain.lifecycle.ReadyEvent.java (2)
- discord4j.core.event.domain.channel.TypingStartEvent.java (1)
- discord4j.core.event.domain.VoiceServerUpdateEvent.java (1)
- discord4j.core.event.domain.message.ReactionRemoveAllEvent.java (1)
- discord4j.core.event.domain.role.RoleDeleteEvent.java (1)
- discord4j.core.event.domain.channel.VoiceChannelCreateEvent.java (1)
- discord4j.core.event.domain.VoiceStateUpdateEvent.java (1)
- discord4j.core.event.domain.guild.GuildUpdateEvent.java (1)
- discord4j.core.event.domain.channel.CategoryDeleteEvent.java (1)
- discord4j.core.event.domain.message.MessageCreateEvent.java (1)
- discord4j.core.event.domain.role.RoleCreateEvent.java (1)
- discord4j.core.event.domain.guild.MemberUpdateEvent.java (1)
- discord4j.core.event.domain.lifecycle.ReconnectStartEvent.java (1)
- discord4j.core.event.domain.lifecycle.GatewayLifecycleEvent.java (1)
- discord4j.core.event.domain.guild.GuildCreateEvent.java (1)
- discord4j.core.event.domain.PresenceUpdateEvent.java (1)
- discord4j.core.event.domain.WebhooksUpdateEvent.java (1)
- discord4j.core.event.domain.message.ReactionAddEvent.java (1)
- discord4j.core.event.domain.channel.PrivateChannelDeleteEvent.java (1)
- discord4j.core.event.domain.channel.PinsUpdateEvent.java (1)
- discord4j.core.event.domain.channel.TextChannelDeleteEvent.java (1)
- discord4j.core.event.domain.channel.VoiceChannelDeleteEvent.java (1)
- discord4j.core.event.domain.UserUpdateEvent.java (1)
- discord4j.core.event.domain.guild.MemberJoinEvent.java (1)
- discord4j.core.event.domain.guild.BanEvent.java (1)
- discord4j.core.event.domain.role.RoleUpdateEvent.java (1)
- discord4j.core.event.domain.message.MessageBulkDeleteEvent.java (1)
- discord4j.core.event.domain.lifecycle.ResumeEvent.java (1)
- discord4j.core.event.domain.guild.MemberLeaveEvent.java (1)
- discord4j.core.event.domain.guild.MemberChunkEvent.java (1)
- discord4j.core.event.domain.guild.GuildEvent.java (1)
- discord4j.core.event.domain.channel.TextChannelUpdateEvent.java (1)
- discord4j.core.event.domain.lifecycle.DisconnectEvent.java (1)
- discord4j.core.event.domain.channel.CategoryUpdateEvent.java (1)
- discord4j.core.event.domain.message.ReactionRemoveEvent.java (1)
- discord4j.core.event.domain.lifecycle.ReconnectFailEvent.java (1)
- discord4j.core.event.domain.role.RoleEvent.java (1)
- discord4j.core.event.domain.guild.IntegrationsUpdateEvent.java (1)
- discord4j.core.event.domain.message.MessageEvent.java (1)
- discord4j.core.event.domain.channel.PrivateChannelCreateEvent.java (1)
- discord4j.core.event.domain.message.MessageDeleteEvent.java (1)
- discord4j.core.event.domain.message.MessageUpdateEvent.java (1)
- discord4j.core.event.domain.lifecycle.ConnectEvent.java (1)
- discord4j.core.event.domain.guild.UnbanEvent.java (1)
- discord4j.core.event.domain.guild.EmojisUpdateEvent.java (1)
- discord4j.core.event.domain.channel.ChannelEvent.java (1)
- discord4j.core.event.domain.channel.VoiceChannelUpdateEvent.java (1)
- discord4j.core.event.domain.channel.TextChannelCreateEvent.java (1)
- discord4j.core.event.domain.lifecycle.ReconnectEvent.java (1)
- discord4j.core.event.domain.channel.CategoryCreateEvent.java (1)
- discord4j.core.event.domain.guild.GuildDeleteEvent.java (1)
- discord4j.core.object.presence.Presence.java (11)
- discord4j.core.object.audit.AuditLogEntry.java (7)
- discord4j.core.object.reaction.ReactionEmoji.java (4)
- discord4j.core.object.presence.Activity.java (4)
- discord4j.core.object.audit.AuditLogChange.java (3)
- discord4j.core.object.presence.Status.java (2)
- discord4j.core.object.entity.Role.java (2)
- discord4j.core.object.audit.ActionType.java (2)
- discord4j.core.object.audit.ChangeKey.java (1)
- discord4j.core.object.audit.OptionKey.java (1)
- discord4j.core.StateHolder.java (13)
- discord4j.core.shard.ShardingStoreRegistry.java (4)
- discord4j.core.shard.ShardingJdkStoreService.java (1)
- discord4j.core.ConnectedObserver.java (1)
- discord4j.core.ServiceMediator.java (1)
- discord4j.core.StoreInvalidator.java (1)
- discord4j.core.shard.ShardAwareStore.java (1)

**Comment by quanticc** [comment]
Thanks! We want to focus on specs first.

**Comment by quanticc** [comment]
@SizableShrimp Can you provide an updated list?

**Comment by SizableShrimp** [comment]
@quanticc Updated to match the most recent commit on master, `25c833d`.

**Comment by quanticc** [comment]
Regarding missing or incomplete javadocs in the future, we're always happy to accept documentation PRs.

I'm closing this for now due to inactivity.
