### ISSUE TITLE
Docs for V2

### ISSUE THREAD

**Issue by TheDutchMC04** [Discord4J/Discord4J#502]
Hello,

I am working on a bot, but cannot find the docs for V2.10.1, I know V3 is out, but friends who are helping me do not know V3, thats why I am sticking with V2.
Could anyone point me to the docs of V2?

Thanks

**Comment by danthonywalker** [comment]
https://javadoc.jitpack.io/com/github/austinv11/Discord4j/2.10.1/javadoc/
Also we are always willing to help with v3 on our Discord. We will no longer provide any support for v2.

**Comment by TheDutchMC04** [comment]
Totally understand that there's no support anymore for V2, but are there still docs?

**Comment by danthonywalker** [comment]
Are you talking about this? https://discord4j.readthedocs.io/en/latest/

**Comment by TheDutchMC04** [comment]
Those are for V3 no?

**Comment by xaanit** [comment]
Please click the links that are provided to you. We understand you what v2. We would not provide you v3 links since you didn’t ask for them.

**Comment by TheDutchMC04** [comment]
I have misread it then, apologies
