### ISSUE TITLE
GuildMemberEditSpec::setNickName not work with null param

### ISSUE THREAD

**Issue by Doc94** [Discord4J/Discord4J#519]
**To Reproduce:**
1. Get a member object
2. Try to edit member nickname using null param in GuildMemberEditSpec

**Expected Behavior:** The nickname of guild reset to the username and put log in audit log

**Actual Behavior:** The nickname of guild not reset, and not make any request

**Version:** 3.0.3

**Other:** the javadoc/code show you can use use null for reset, and in my test the code work with string param but dont with null.

**Comment by danthonywalker** [comment]
Need more information. Not set as in it does nothing? An error?

**Comment by Doc94** [comment]
Nothing, and trigger the "doOnSuccess" with no errors, but if i check the audit log o the user nothing happen, if use a string param work normally.

**Comment by quanticc** [comment]
Use `setNickname("")` for now. We'll change it for next version.
