### ISSUE TITLE
Entity Refactor

### ISSUE THREAD

**Issue by darichey** [Discord4J/Discord4J#522]
# Entity Refactor
Explore our options for providing high level abstractions for http-only use cases and the implications thereof.

## Background
Discord4J v3 was designed in such a way to allow for pluggable store implementations. This includes the possibility for a NOOP store where all lookups will instead fallback to HTTP. Even though it is technically possible to use `core` today with a NOOP store, it is very difficult to do so in an efficient way without backing into lower level modules.

As a real world example, in [GithubBot](https://github.com/GrandPanda/GithubBot), I only listen to events and react in the same channel. This is a perfect candidate for using a NOOP store. However, it is difficult to do efficiently. Say I wrote something like this for responding to a received message in a channel:
```java
private Mono<Message> sendMessage(DiscordClient client, Snowflake channel, String content) {
    return client.getChannelById(channel).ofType(MessageChannel.class).flatMap(c -> c.createMessage(content))
}
```
This works even if I have a NOOP store, but there is a serious performance degredation stemming from the fact that I am actually making *two* HTTP requests in this code. Obviously, one to send the message, but there is another in `getChannelById()` because the store doesn't have the channel.

Today, the only way to fix this is to fall all the way back to the `rest` module:
```java
private Mono<MessageResponse> sendMessage(ServiceMediator serviceMediator, long channel, String content) {
    MultipartRequest request = new MultipartRequest(new MessageCreateRequest(content, null, false, null));
    return serviceMediator.getRestClient().getChannelService().createMessage(channel, request);
}
```
Direct interaction with ServiceMediator like this is the only way to send a message to a channel with only one http request. This is because, currently, you cannot construct a `MessageChannel` without data that can only be acquired on the gateway (and then stored) or by requesting it. But obviously sending a message only requires the ID which makes that request useless. It would be much nicer to be able to write something like:
```java
private Mono<Message> sendMessage(DiscordClient client, Snowflake channel, String content) {
    return client.getRestMessageChannel(channel).createMessage(content);
}
```
In this code, I was able to move up to the level of abstraction we're used to in `core`. Obviously, the black box in that snippet is `getRestMessageChannel()`. This is what this proposal explores.

For reference, here's today's entity hierarchy:
![](https://cdn.discordapp.com/attachments/210938552563925002/566272976077586434/Entities.png)

## Proposal
The `getRestMessageChannel()` would probably return something like `RestMessageChannel` which does not have any data associated to it, but still has all of the behavior which can be achieved over HTTP with only an ID. This implies an entire `Rest*` entity hierarchy. Obviously, this is a massive change that requires a lot of thought.

The proposal has three parts: pure http behavior representations of entities, pure data representations of entities, and a refactoring of the existing entities to use these latter two. 

### HTTP Behavior
HTTP behavior should be extracted to separate http-only entities. This is the `RestMessageChannel` and `Rest*` entities. This is the core of the proposal whose reasoning was explained previously. 

#### Note
I am explicit in *HTTP* behavior and not just behavior in general. I think it would be counterproductive to require that things such as utility methods must delegate to a separate behavior service. In addition, some entities have behavior which is implemented with gateway components. Requiring those to be delegated away as well would require answering an immense number of questions whose answers I don't believe will be beneficial to any use case.

### Data
The example I showed exhibited the need for http behavior without data. However, I think it would also be beneficial to provide for the reverse: data without http behavior. 

We mostly do this already with our `*Bean` classes. However, we can't safely expose this to users because they are mutable. We already [treat them as immutable internally](https://github.com/Discord4J/Discord4J/pull/499), so this change could simply be going all the way with that. It wouldn't impose the need for external changes.

### Composition
To weave the previous two changes together, we refactor today's entities to be ([mostly](#Note)) a composition of HTTP Behavior and Data. 

For example, `Role` may look something like this:
```java
public final class Role implements Entity {
    private final RoleData data;
    private final RestRole rest;
    private final long guildId;

    ...

    public String getName() { 
        return data.getName(); 
    }

    ...

    public Mono<Role> edit(final Consumer<? super RoleEditSpec> spec) {
        return rest.edit(spec);
    }

    ...

    public Mono<Guild> getGuild() {
        return getClient().getGuildById(getGuildId());
    }

    public Mono<Integer> getPosition() {
        return getGuild().flatMapMany(Guild::getRoles).collectList().map(list -> list.indexOf(this));
    }
}
```
* Data methods like `getName()` delegate to `RoleData`
* Behavior methods like `edit()` delegate to `RestRole`
* We still allow for non-delegate methods like `getGuild()` and `getPosition()`

## Notes and Open Questions
This proposal is in its very early stages. There are many things to figure out. I have provided my initial thoughts/answers for some of the questions. Please respond with your ideas.

### Are the two hierarchies related?
This question revolves around the idea of `Role <: RestRole` or some other relation between the hierarchy of http-only entities and the hierarchy of complete entities.

Personally, I think it will be best if these two hierarchies aren't closely related. It might be useful to still have some shared root. I can see how the relation `Role <: RestRole` makes sense in terms of implementation, but I think the types are so different in terms of semantics that they shouldn't be close.

### Are we willing to break things?
These changes will most definitely target 3.1+. Technically, we have the right to make breaking changes. As I have laid out the changes here, I believe this can be accomplished without breaking anything user-facing. However, this would be a good time to make any other possibly-breaking changes we want to entities. While I don't personally have any in mind, should we consider breaking changes if they arise?

### Naming
This is something mostly unimportant at the moment, but I am open to suggestions of alternative naming for anything mentioned in this document.

**Comment by quanticc** [comment]
Now that #564 is merged, we can resume work on this story. We decided to get rid of the Response pojos and instead map from JsonNode to the appropriate Data object.

Once those *Data objects are done, the entities can begin to be refactored to include them as fields instead of the current *Bean objects.

**Comment by darichey** [comment]
Work on `XData` has begun in #584 .

**Comment by quanticc** [comment]
This project will provide the immutable objects https://github.com/Discord4J/discord-json

Work is being done to integrate them to Discord4J in the https://github.com/Discord4J/Discord4J/tree/change/data branch
