### ISSUE TITLE
Unknown message received: GIFT_CODE_UPDATE

### ISSUE THREAD

**Issue by Nikos410** [Discord4J/Discord4J#527]
Our bot threw this exception, it seems like it received a message type that is not supported by Discord4J: https://sentry.io/share/issue/bd066a68ed1a495d848ab0391922d490/

We are still using Version 2.10.1, maybe this is already supported in version 3.x ?

**Comment by Shadorc** [comment]
Hi, V2 is no longer maintain, you should migrate to V3, there is some useful guides for this in the wiki
