### ISSUE TITLE
Supporting HTTP and SOCKS proxies for connecting to the Discord API

### ISSUE THREAD

**Issue by kb-1000** [Discord4J/Discord4J#537]
**Feature Description:** Support for connecting to the Discord API through a HTTP or SOCKS proxy, as well as a possibility to let it automatically take the value of the `https_proxy`/`HTTPS_PROXY` environment variable

**Justification:** I can sometimes only connect to the internet through a HTTP proxy, but I still want to test my Discord4J bot.

**Comment by quanticc** [comment]
Tried SOCKS proxy support and it works so it will be added. I've been unable to make an HTTPS proxy work though, unless it's set at the OS/adapter level.

**Comment by quanticc** [comment]
v3.1 introduces `ReactorResources` to customize reactor netty's HttpClient. It can be configured with a proxy.
