### ISSUE TITLE
LEAK: ByteBuf.release() was not called before it's garbage-collected.

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#545]
Sometimes an error is thrown saying `LEAK: ByteBuf.release() was not called before it's garbage-collected.`
Quantic has confirmed that this error was related to Discord4J.

**To Reproduce:** Unknown.

**Expected Behavior:** No error.

**Actual Behavior:** An error is thrown: <https://pastebin.com/KQiS8VSw> 
(obtained with JVM arg `-Dio.netty.leakdetection.level=PARANOID`)

**Version:** 3.0.7

**Comment by quanticc** [comment]
To be fixed by #608 . Changing milestone to 3.1

**Comment by quanticc** [comment]
Please report if you encounter this issue again

**Comment by Doc94** [comment]
I found this issue two times in random tests (not sure if was for event or for the clearchannel command chain).
Log: https://pastebin.com/BSckaj6R
