### ISSUE TITLE
Permission Sets for Channel

### ISSUE THREAD

**Issue by FortusHD** [Discord4J/Discord4J#550]
I am now working a few months with Discord4J 3 and I don't get how to create a Voice-Channnel with special permissions for an explicit user. I got how to create a channel and set the name etc., but how do I set permissions?
I hope this question belongs here, because I am new at GitHub and did not found a category for this.

**Comment by darichey** [comment]
You can use `VoiceChannelCreateSpec#setPermissionOverwrites()` to set the permission overwrite for a member when creating the channel. For example,

```java
Guild guild = ...;
Mono<VoiceChannel> createVoiceChannel = guild.createVoiceChannel(vc -> {
  PermissionSet allowed = PermissionSet.of(Permission.CONNECT);
  PermissionSet denied = PermissionSet.of(Permission.USE_VAD);
  PermissionOverwrite overwrite = PermissionOverwrite.forMember(Snowflake.of(84766711735136256L), allowed, denied);

  vc.setPermissionOverwrites(Collections.singleton(overwrite));
})
```
This will create a voice channel with a single overwrite for the member with the ID `84766711735136256` explicitly allowed `CONNECT` and explicitly denying `USE_VAD`.

Feel free to join our [Discord server](https://discord.gg/NxGAeCY) for further help.
