### ISSUE TITLE
ReactionEmoji.Custom "isAnimated" Inconsistencies

### ISSUE THREAD

**Issue by HunterCop224** [Discord4J/Discord4J#552]
After the first reaction to a message with an animated guild emoji is added D4J indicates that the emoji is **not** animated when it actually is. When the first reaction is added it is correct. This creates issues when attempting to compare `ReactionEmojis` from other sources.

**To Reproduce:** Have someone add an **animated** reaction emoji to a message, the `ReactionEmoji` provided by `ReactionAddEvent` will have the `isAnimated` field set to true, which is correct. Have a second account react with the same emoji on the same message (bring the number of users reacted to two) and the `ReactionEmoji` produced will have `isAnimated` set to false.

**Expected Behavior:** No matter how many people react with the same animated emoji all ReactionEmoji objects should have `isAnimated` set to true.

**Actual Behavior:** Only the first person who reacts with an animated emoji will have `isAnimated` set to true, all subsequent reactions with the same emoji have `isAnimated` set to false.

**Version:** v3.0.8

**Other:** `ReactionRemoveEvent` emojis will always have `isAnimated` set to false.

**Comment by Shadorc** [comment]
This is not related to Discord4J, Discord API does this "intentionaly" : https://github.com/discordapp/discord-api-docs/issues/812

**Comment by HunterCop224** [comment]
Ah I see, this does however cause issues with at least one part of D4J. `ReactionEmoji.equals()` is unusable in a situation like this when comparing to one where `isAnimated` is correctly set.

Since it's known that these fields will be incorrect in those situations, perhaps dropping the equality checks on the name and ID since they *can* be incorrect, and changing `isAnimated` from `boolean` to `Optional<boolean>`? And maybe something similar for name as well.

**Comment by Shadorc** [comment]
For the record, Discord is fixing a lot of issues these days and this one is part of them https://github.com/discordapp/discord-api-docs/issues/812
`Emoji#isAnimated` should now be consistent.
This also introduces a breaking change because `Emoji#name` is now optional, I will open a PR for this.
