### ISSUE TITLE
Enums representing discord values should accept unknown IDs

### ISSUE THREAD

**Issue by tterrag1098** [Discord4J/Discord4J#571]
Discord recently introduced a new enum value for activity types, for custom statuses. Any bot consuming this new API value will crash when attempting to get the `Activity.Type` from the presence. To resolve this, D4J enums representing discord values should be made with forwards compatibility in mind, and accept IDs that could be future additions to the Discord API. This could be done with a dedicated `UNKNOWN` constant in all enums (perhaps with ID -1), or by using `Optional` as a return value.

**To Reproduce:** `Activity.Type.of(4)`

**Expected Behavior:** The method should return some sentinel value for unknown, or use `Optional`.

**Actual Behavior:** `UnsupportedOperationException` is thrown.

**Version:** `33bf52b`, but the code in question is unchanged since then.

**Other:** N/A

**Comment by kvnxiao** [comment]
+1 for UNKNOWN

**Comment by quanticc** [comment]
We will track progress of it in #575
