### ISSUE TITLE
Drag / Move user in voice channels?

### ISSUE THREAD

**Issue by Uraxys** [Discord4J/Discord4J#573]
**Feature Description:** A way to move users to another channel.

**Justification:** It is missing from Discord4J, or I didn't find a method for it.

**Comment by danthonywalker** [comment]
Do not ask questions like this here. Go to our Discord
https://static.javadoc.io/com.discord4j/discord4j-core/3.0.10/discord4j/core/spec/GuildMemberEditSpec.html#setNewVoiceChannel-discord4j.core.object.util.Snowflake-
