### ISSUE TITLE
Use unknown value in our enums for forward-compatibility

### ISSUE THREAD

**Issue by quanticc** [Discord4J/Discord4J#575]
**Motivation**: Avoid error spamming when Discord rolls out new features that we can't process due to D4J throwing `UnsupportedOperationException` from enums.

Since docs for these new features come after (sometimes long after) these features are live, we cannot implement them right away and as such we need a temporary solution while a permanent fix/feature is implemented in D4J.

**Proposal**: To add an "UNKNOWN" value to our enums, where it makes sense.

These are the places where do enums that could **throw** exceptions if met with an unknown value:

- [x] Embed.Type [(source)](https://github.com/Discord4J/Discord4J/blob/master/core/src/main/java/discord4j/core/object/Embed.java#L193)
- [x] PermissionOverwrite.Type [(source)](https://github.com/Discord4J/Discord4J/blob/master/core/src/main/java/discord4j/core/object/PermissionOverwrite.java#L117)
- [x] ActionType [(source)](https://github.com/Discord4J/Discord4J/blob/master/core/src/main/java/discord4j/core/object/audit/ActionType.java)
- [x] Channel.Type [(source)](https://github.com/Discord4J/Discord4J/blob/master/core/src/main/java/discord4j/core/object/entity/channel/Channel.java#L67)
- [x] Guild.ContentFilterLevel [(source)](https://github.com/Discord4J/Discord4J/blob/master/core/src/main/java/discord4j/core/object/entity/Guild.java#L1096)
- [x] Guild.MfaLevel [(source)](https://github.com/Discord4J/Discord4J/blob/master/core/src/main/java/discord4j/core/object/entity/Guild.java#L1149)
- [x] Guild.NotificationLevel [(source)](https://github.com/Discord4J/Discord4J/blob/master/core/src/main/java/discord4j/core/object/entity/Guild.java#L1198)
- [x] Guild.PremiumTier [(source)](https://github.com/Discord4J/Discord4J/blob/master/core/src/main/java/discord4j/core/object/entity/Guild.java#L1248)
- [x] Guild.VerificationTier [(source)](https://github.com/Discord4J/Discord4J/blob/master/core/src/main/java/discord4j/core/object/entity/Guild.java#L1305)
- [x] Message.Type [(source)](https://github.com/Discord4J/Discord4J/blob/master/core/src/main/java/discord4j/core/object/entity/Message.java#L549)
- [x] Activity.Type (done in #572) [(source)](https://github.com/Discord4J/Discord4J/blob/master/core/src/main/java/discord4j/core/object/presence/Activity.java#L229)
- [x] Status [(source)](https://github.com/Discord4J/Discord4J/blob/master/core/src/main/java/discord4j/core/object/presence/Status.java)
- [x] Image.Format (throws `IllegalArgumentException` instead) [(source)](https://github.com/Discord4J/Discord4J/blob/master/core/src/main/java/discord4j/core/object/util/Image.java#L141)

Any objections to having UNKNOWN in any of the enums above?

**Comment by danthonywalker** [comment]
Agree. Basically this would remove `EntityUtil.throwUnsupportedDiscordValue`.
