### ISSUE TITLE
discord4j v3 MessageReceivedEvent stops dispatching after a few minutes

### ISSUE THREAD

**Issue by alexpmorris** [Discord4J/Discord4J#579]
**To Reproduce:** minimal message loop, always seems to die after a few minutes without any sign of error or completion.

**Expected Behavior:** message loop keeps streaming messages for life of application

**Actual Behavior:** discord4j v3 client remains connected, but chat messages no longer stream after several minutes (give or take).  However, other events such as `MemberJoinEvent`/`MemberLeaveEvent` continue to stream.  If I break into the timer loop and create another instance of the event dispatcher, events start streaming again, so it seems for some reason the event dispatcher terminates without any visible error.

**Version:** 3.0.10 core, running on Windows 10

**Other:** I just upgraded my discord bot from discord4j v2 to v3, and it all seems to work so far, except for this one issue.  The bot account services around 70 chat servers with relatively low levels of traffic, at least during the time of testing.  `doOnError` and `doOnComplete` were added to see if I could find some sort of error or completion state.  Here is the minimal implementation I was using that still gives me the issue:

```
DiscordClient client = new DiscordClientBuilder(token).build();

Disposable onMsg = client.getEventDispatcher().on(MessageCreateEvent.class)
                .doOnError(error -> {
                    System.out.println(error.getMessage());  // never triggers
                })
                .doOnComplete(() -> {
                    System.out.println("done");  // never triggers
                })
                .subscribe(event -> {
                    System.out.println("<-- "+event.getMessage().getContent().get().toString());
                });

```

**Comment by xaanit** [comment]
The `doOnError` will never be called due to the error handler being upstream. You'd need to use either the second part of the callback for subscribe or use flatMap or similar methods. The flux dying is intended behaviour.

Also `doOnComplete` will never trigger due to event fluxes never completing.

**Comment by alexpmorris** [comment]
thanks @xaanit, just wanted to let you know that solved it, been running over a day now without a glitch! 😅 

for future reference in case anyone else gets stuck with this...

```
        Disposable onMsg = client.getEventDispatcher().on(MessageCreateEvent.class)
                .subscribe(event -> {
                    if (event.getMessage().getContent().isPresent() && 
                        event.getMessage().getAuthor().isPresent()) {
                        System.out.println("<-- "+event.getMessage().getAuthor().get().getUsername()+": "+event.getMessage().getContent().get());
                        }
                    }
                },
                error -> {
                    System.err.println("subscribe_error: "+error);
                });
```

btw, I had checked discord first but only `DiscordAPI` channel, I had totally forgotten about the much more active `DiscordJ` server.  Thanks again!

**Comment by danthonywalker** [comment]
For more reference, this isn't specific to Discord4J, but to Reactor. And as far as I can tell you still aren't exactly handling errors, you're just printing it out.

Error Handling in Reactor:
https://projectreactor.io/docs/core/release/reference/#error.handling

But yeah, you were straight using `get` on an `Optional`. For Java in general, that isn't good. Even `isPresent` check then `get` is still not an optimal paradigm. See:
https://m.youtube.com/watch?v=Ej0sss6cq14

**Comment by alexpmorris** [comment]
Thank you for that video, I watched the whole thing, and while I see how it can be useful in certain cases, for the sake of clarity, and given my use case, isPresent/get seems to make the most sense. 

My message handler does try/catch for any errors, so it was actually my debug `println()` that was throwing the exception and killing the stream, go figure... lol

**Comment by kvnxiao** [comment]
Since you are checking the message contents, to guarantee that downstream operations are only valid existent string values and authors you can also make use of `flatMap` with `Mono.justOrEmpty()` and `Mono.zip()`
