### ISSUE TITLE
Reaction emoji name is now nullable

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#590]
**Feature Description:** 
Discord has recently fixed a bug linked to emoji name and animated fields being inconsistents (https://github.com/discordapp/discord-api-docs/issues/812). 
To fix this, emoji name field is now nullable (https://github.com/discordapp/discord-api-docs/commit/a2b0342ad4341b63e62fb9d764f949fbf273cfa5) which is not currently the case in Discord4J (https://github.com/Discord4J/Discord4J/blob/3.0.x/common/src/main/java/discord4j/common/json/EmojiResponse.java#L24). 
I didn't opened a pull request myself because it's a bit more complex than just adding `Optional` and `@Nullable` annotations, store and some core logics are using the name to process equality checks and so on. 

**Justification:** 
Reaction emoji name is now nullable and it should be updated before it causes exceptions.

**Comment by quanticc** [comment]
Thanks for the heads up!

**Comment by quanticc** [comment]
Superseded by the discord-json project and its data objects so not something we want to explore fixing for 3.0
