### ISSUE TITLE
Support Activity#created_at field

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#611]
**Feature Description:** Currently, Activity is represented by the `ActivityBean` data class. However, since the recent addition of an `Activity#created_at` field, this class cannot represent Activity received and sent to Discord anymore. In the first case, this field is not optional nor nullable and, in the second case, the field does not have to be send.

It would be beneficial to split this class in order to correctly support both case.

**Justification:** Support for `Activity#created_at` field is missing: https://github.com/discordapp/discord-api-docs/pull/1208

**Reference:** https://github.com/Discord4J/Discord4J/pull/601

**Comment by quanticc** [comment]
@darichey wdyt

**Comment by quanticc** [comment]
Are you open to make a PR now that we have integrated https://github.com/Discord4J/discord-json?
