### ISSUE TITLE
How can I directly send an HTTP post request?

### ISSUE THREAD

**Issue by Jire** [Discord4J/Discord4J#614]
For example, I want to send an HTTP post request to redeem a Nitro gift code.

This is done by a POST request to `/entitlements/gift-codes/XXXXXX/redeem` where _XXXXXX_ is the Nitro code.

How can I submit these types of simple requests using this API? Thanks.

**Comment by danthonywalker** [comment]
Use the any of the thousand HTTP clients that exist for Java including the one packaged with D4J (reactor-netty) or even the built-in one from the JDK (Java 11+).

We don't expose endpoints that are either not documented nor should be used by bots (this is a *bot* library).

**Comment by quanticc** [comment]
To showcase how to use reactor-netty directly you can check this link: https://projectreactor.io/docs/netty/snapshot/reference/index.html#_adding_headers_and_other_metadata_2

You could also build a custom client using discord4j-rest module (included in core)
3.0.x: https://github.com/Discord4J/Discord4J/blob/3.0.x/rest/src/test/java/discord4j/rest/http/WebClientTest.java
3.1.x: https://github.com/Discord4J/Discord4J/blob/master/rest/src/test/java/discord4j/rest/http/WebClientTest.java#L77-L88
