### ISSUE TITLE
Guild#leave returns 400: Bad request

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#615]
**To Reproduce:** 
    **1.** Join a Guild with a bot
    **2.** Use Guild#leave

**Expected Behavior:** The bot leaves the Guild without exception because it is not the owner of the Guild.

**Actual Behavior:** An exception is thrown: `discord4j.rest.http.client.ClientException: DELETE /users/@me/guilds/XXXX returned 400 BAD REQUEST with response {code=0, message=400: Bad Request}`

**Version:** 3.1-SNAPSHOT (prototype/voice-for-3.1 branch)

**Other:** This issue is thrown because DAPI expects either content-type set to application/json and an empty JSON body OR no content-type set.

**Comment by quanticc** [comment]
This also affects 3.0.x - thanks for reporting this. I wonder if also affects endpoints like deleting a guild.

I will patch both

**Comment by quanticc** [comment]
Initial tests seem to indicate it's only affecting `Guild::leave`. `Guild::delete` works fine.
