### ISSUE TITLE
[3.1.0] The new Invite Create event throws NPE

### ISSUE THREAD

**Issue by Alex1304** [Discord4J/Discord4J#617]
**To Reproduce:** 
Get someone on Discord to fire an invite create event. Not 100% sure if it happens in all cases or only in specific ones, but I let you judge by the logs
**Expected Behavior:** 
Event is dispatched normally
**Actual Behavior:** 
NullPointerException upon instanciating UserBean
**Version:** 
3.1.0-SNAPSHOT

**Other:** 
[d4j_npe.log](https://github.com/Discord4J/Discord4J/files/4271215/d4j_npe.log)

**Comment by Alex1304** [comment]
sorry I pressed Send too early, let me edit

**Comment by Alex1304** [comment]
Here we go

**Comment by quanticc** [comment]
Thanks, inviter is nullable so this bug affects 3.0.x as well. https://github.com/discordapp/discord-api-docs/pull/1309/files#diff-b307d936b736f302bc7cc153f0d8a0a3R831

Hopefully we can patch it to indicate the proper return types. @Doc94 can you help us with that?

**Comment by Doc94** [comment]
i see now Inviter can return null... well then need change the return to Optional.
