### ISSUE TITLE
[Feature Request] Allowed mentions

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#629]
**Feature Description:** Discord has implemented a way to allow mentions or not when sending messages.

**Justification:** https://github.com/discordapp/discord-api-docs/commit/ebc53c45a42904230b63e8e60844ac7b149e9207

**Comment by Shadorc** [comment]
`allowed_mention` is now also supported in edit: https://github.com/discord/discord-api-docs/pull/1483

**Comment by quanticc** [comment]
Resolved via #673

cc @tterrag1098
