### ISSUE TITLE
An exception is thrown when the bot logout while being connected to a voice channel

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#634]
**To Reproduce:** 
1. The bot joins a voice channel
2. Use `GatewayDiscordClient#logout()`

**Expected Behavior:** The bot gets disconnected from the voice channel then logs out.

**Actual Behavior:** The bot gets disconnected from the voice channel, throws an exception (https://pastebin.com/LSvNG3yk) then logs out.

**Version:** 3.1.0-SNAPSHOT

**Comment by quanticc** [comment]
Fix is to handle incoming disconnected payload as a "STOP" disconnect behavior to avoid that long exception and exit gracefully.
