### ISSUE TITLE
Cache Layer in Rest Module

### ISSUE THREAD

**Issue by ByteAlex** [Discord4J/Discord4J#636]
**Feature Description:** 
In a RestX class, e.g. RestChannel you have the option to retrieve ChannelData, which will be a rest call.
I'd like to have a method overload with the option to provide a caching layer, which makes it possible to read from a store first, in case you want to check local cache first.

**Justification:**
When running the rest-module separated from the core-module, you'll have unnecessary rest-calls which reduces your global rate limit, when you can't access core easily.

**Comment by darichey** [comment]
You get live updates to data from the gateway. Storing results from rest seems useless because there's 0 guarantee the data is still good.

**Comment by ByteAlex** [comment]
Exactly, I get live updates from the gateway and can't access them from the rest module without additional layer.
I'm talking about a distributed architecture, where different applications build the whole discord bot.
For scheduled tasks I have a separate worker which only has rest-actions to do.
But if I need a ChannelData for computing something (e.g. nsfw), I'd have to do a rest call to get the data or I'd have to add an additional API layer which checks the store first and then requests from rest.
This additional API layer should be included in rest: The option to have a (read only) store which is checked on getData via method overload.
Default method remains a rest-call, overload gives the opportunity to read from a store first.

**Comment by darichey** [comment]
> I have a separate worker which only has rest-actions to do.
But if I need a ChannelData for computing something (e.g. nsfw)
Imo, this means your worker does more than just rest. You need access to live data which requires the gateway and a store.

**Comment by ByteAlex** [comment]
It does a bit of computing around it. Probably member permissions and stuff aswell. I have a gateway running providing live data to the store (redis store in my case). Now I want to check something, where I should have live data in the store, but I can't access them from the existing rest module already.

I'd have to build an addtional API layer which asks my store first and the uses the rest-module to retrieve data if not found.

I'm not sure if you get my point. There is no way I can have a gateway in this application there.

**Comment by quanticc** [comment]
Combining Rest and Store modules is the way to solve this. However we need to relocate [some classes](https://github.com/Discord4J/Discord4J/tree/8d5a80f21d81eb929f609144fa62c628d07a569f/core/src/main/java/discord4j/core/state) for it to work without heavy lifting on your end.

Maybe after that starting point we shed some light on following improvements to your use case.

**Comment by ByteAlex** [comment]
Well, basically what I'm asking for is some method overload in the RestX classes to hook into the getData with a provided readonly store. So I can read from a store, via overload, in case I believe to have live data.

**Comment by quanticc** [comment]
I don't think we'll add such a method, but providing an easier way to pull data from Store API, like `StoreView` from core module available to you.

**Comment by Alex1304** [comment]
I do see one important use case for using cache with REST.
Remember in Discord4J v2, there was a system where the 100 last messages of all channels the bot was in would be cached automatically on startup. Discord4J v3 provides methods like getMessageAfter, etc, but there is no way to use these methods to populate the message cache.
For REST-only bots that mainly do message processing, having a cache layer in REST can be very useful.
