### ISSUE TITLE
VoiceChannel#join gets stuck if the bot doesn't have permission to view channel

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#638]
**To Reproduce:** 
1. Remove `VIEW_CHANNEL` permission to the bot
2. Try to join the voice channel

**Expected Behavior:** An error is thrown.

**Actual Behavior:** Nothing happens, the `VoiceChannel#join` gets stuck indefinitively.

**Version:** 3.1.0-SNAPSHOT

**Comment by Shadorc** [comment]
Discord API server confirmed that when the bot can't connect to a voice channel (it can be due to lack of permissions for example), Discord does not respond to the join request.
It can be avoided by:
1. Pre-checking permissions but that's not in the philosophy of Discord4J V3 and it's prone to race conditions.
2. Setting a timeout to the join request.

Both solution are not very good, I don't know which is the less worst but this is the way Discord is working, we sadly can't do much better.

**Comment by darichey** [comment]
The second option should already be possible with `Mono#timeout()`, right? I don't think it will be obvious to users that they must do that, though.

**Comment by quanticc** [comment]
we would have to add it

**Comment by quanticc** [comment]
@Shadorc Are you OK with the timeout? We can add a configurable Duration but we need a default. Can you give us some hint about what should it be

**Comment by Shadorc** [comment]
I'm fine with a timeout. It should be explained in the documentation that a missing permission will result in a TimeoutException.
I really have no clue what a good default value could be, it often takes less than a second to join but I don't really know what an average join time is. I would say 5 seconds but that's purely arbitrary. I can make a pull request to change the default value if I find a more interesting value somedays.
