### ISSUE TITLE
Improve API for setting a client's status and activity

### ISSUE THREAD

**Issue by quanticc** [Discord4J/Discord4J#644]
Finalize the API for this topic, considering our 3.0 static factories as starting point:

- Presence#online
- Presence#idle
- Presence#doNotDisturb
- Presence#invisible
- Activity#playing
- Activity#streaming
- Activity#listening
- Activity#watching

These currently yield discord-json types such as `StatusUpdate` and `ActivityUpdateRequest`.

This ticket is to decide whether to move forward with such types or create dedicated core types for setting a client's status and activity, for example: `ClientStatus` / `ClientActivity`.

**Comment by quanticc** [comment]
Interested in your feedback @darichey and @danthonywalker

**Comment by darichey** [comment]
I think core types are necessary for API discoverability, even if they might be a bit redundant. There's been more than a couple instances of people trying to build the discord-json types because they see those are the parameters.

**Comment by quanticc** [comment]
The current core API for this feature is this:

```java
GatewayBootstrap#setInitialPresence(Function<ShardInfo, StatusUpdate>)
GatewayBootstrap#setInitialStatus(Function<ShardInfo, StatusUpdate>) // alias

GatewayDiscordClient#updatePresence(StatusUpdate)
GatewayDiscordClient#updatePresence(StatusUpdate, int) // for shard specific status
```

They need a `StatusUpdate` instance now, and `ActivityUpdateRequest` for activities. We have two options:

- Create core types: And create new API that points to a new type that will be the new entry point for factories, either `ClientStatus` or `ClientPresence` comes to mind
- Create factories at StatusUpdate and ActivityUpdateRequest so they match the current API

```java
@Value.Immutable
@JsonSerialize(as = ImmutableStatusUpdate.class)
@JsonDeserialize(as = ImmutableStatusUpdate.class)
public interface StatusUpdate extends PayloadData {

    static ImmutableStatusUpdate.Builder builder() {
        return ImmutableStatusUpdate.builder();
    }

    static StatusUpdate online() {
        return StatusUpdate.builder()
                .status("online")
                .game(Optional.empty())
                .afk(false)
                .since(Optional.empty())
                .build();
    }

    static StatusUpdate online(ActivityUpdateRequest activity) {
        return StatusUpdate.builder()
                .status("online")
                .game(activity)
                .afk(false)
                .since(Optional.empty())
                .build();
    }

    // .....

    Optional<Long> since();
    Optional<ActivityUpdateRequest> game();
    String status();
    boolean afk();
}
```

```java
@Value.Immutable
@JsonSerialize(as = ImmutableActivityUpdateRequest.class)
@JsonDeserialize(as = ImmutableActivityUpdateRequest.class)
public interface ActivityUpdateRequest extends Activity {

    static ImmutableActivityUpdateRequest.Builder builder() {
        return ImmutableActivityUpdateRequest.builder();
    }

    static ActivityUpdateRequest playing(String name) {
        return ActivityUpdateRequest.builder()
                .name(name)
                .type(0)
                .build();
    }

    // ....

    Optional<String> url();
}
```

Let me know what you think

**Comment by darichey** [comment]
I'm personally partial to the first choice. It's a bit more code duplication, but I think those discord-json types confuse users who don't want to work with the "low level" stuff.
