### ISSUE TITLE
Can I join to group with this api using my client?

### ISSUE THREAD

**Issue by Katakurinna** [Discord4J/Discord4J#647]
Hello, I wanted to know if with this api I can access a group and join the call, to put music. Thank you!

**Comment by danthonywalker** [comment]
Bots cannot join group chats.

**Comment by Katakurinna** [comment]
yea, but if i use personal account?

**Comment by Doc94** [comment]
> yea, but if i use personal account?

D4J its for BOT accounts only.

**Comment by Katakurinna** [comment]
> > yea, but if i use personal account?
> 
> D4J its for BOT accounts only.

okey thanks!

**Comment by danthonywalker** [comment]
Self bots are against Discord TOS, *will* get you banned, so we will never support them.
