### ISSUE TITLE
VS.getGuildID throws NoSuchElementException

### ISSUE THREAD

**Issue by JasonTheKitten** [Discord4J/Discord4J#658]
**To Reproduce:** Enter a vc before booting up your bot, run voicestate.getGuildId() after booting up bot (The error only occurs if you are in a vc BEFORE starting your bot)

**Expected Behavior:** The guild ID of the current voice channel should be return

**Actual Behavior:** A NoSuchElementException is thrown until you switch to a different voice channel

**Version:** 3.1.0-SNAPSHOT

**Other:** Quantic told me to open an issue here

**Comment by quanticc** [comment]
The solution is to make sure we store the guild_id in voice states during guild creates. Are you willing to submit a PR fixing it?

**Comment by JasonTheKitten** [comment]
I'll try to make one later today
If I can't (e.g have troubles), I'll tell you

**Comment by Shadorc** [comment]
When 3.1 will be out, it should be noted that without the GUILDS intent, this bug will still happen

**Comment by JasonTheKitten** [comment]
Would it even recognized that the VoiceState exists? The initial Voice States come from the Guild Create Event ("voice_states"), so I would assume that it would fail to even recognize the voice states

**Comment by Shadorc** [comment]
Oh, you're right, if voice_states comes from GUILD_CREATE, my message is wrong
