### ISSUE TITLE
DiscordClientBuilder has been depreciated 

### ISSUE THREAD

**Issue by chriscn** [Discord4J/Discord4J#666]
What are we meant to use instead, the README example is now seemingly out of date.

**Comment by quanticc** [comment]
If you use 3.0, the constructor will keep working. However, in the javadocs we point to the new method.

You have these options:
```
DiscordClient.builder()
DiscordClientBuilder.create()
```

While it's mentioned in the release notes https://github.com/Discord4J/Discord4J/releases/tag/3.0.14
I'll update the README to avoid confusion.
