### ISSUE TITLE
Add Automatic-Module-Name property in build manifest

### ISSUE THREAD

**Issue by Alex1304** [Discord4J/Discord4J#672]
**Feature Description:**

Add an `Automatic-Module-Name` attribute in the project's manifest for each d4j module, it can easily be done via `build.gradle`

**Justification:** 

I wanted to make my bot into a Java module but then Maven complains when I build it
```
[WARNING] ********************************************************************************************************************************************************************************************************
[WARNING] * Required filename-based automodules detected: [discord4j-core-3.1.0.M1.jar, discord-json-1.0.2.jar, discord4j-rest-3.1.0.M1.jar]. Please don't publish this project to a public artifact repository! *
[WARNING] ********************************************************************************************************************************************************************************************************
```
I believe it's important to give basic support for modular projects, even if D4J is a Java 8 project the manifest attribute exists to address this.

**Comment by quanticc** [comment]
Do you know if this upcoming gradle feature is going to help us? https://docs.gradle.org/6.4-rc-2/release-notes.html
> Building, testing and running Java Modules
With this release, Gradle supports the Java Module System with everything you need to compile and execute tests for Java modules. You can also build Javadoc and run applications.

**Comment by Alex1304** [comment]
I don't think so, I believe this is specifically for projects that uses actual Java modules. Discord4J cannot use Java modules because it is a Java 8 project.

Automatic-Module-Name is a property that can be added to the JAR MANIFEST of Java 8 and lower projects, which will allow it to be added to the module path even if it doesn't have a module-info.java.

If Automatic-Module-Name is absent, it will generate a module derived from the name of the JAR file, so something that is not stable. Requiring a such module will give warnings, as I showed in the original post. It's really all about adding this property in the MANIFEST of each Discord4J's module, no extra knowledge of the Java module system is needed. For the `core` module for example, you can add this to its `build.gradle`:

```java
jar {
    manifest {
        attributes 'Automatic-Module-Name': 'discord4j.core'
    }
}
```

**Comment by quanticc** [comment]
@Alex1304 can you tell me if it works after the change?

Then I figure, should we also apply it to other Discord4J projects?

**Comment by Alex1304** [comment]
@quanticc Yep, it works! Now I only have warnings for `discord-json` and `stores-api`, so I guess you can go ahead for these projects
