### ISSUE TITLE
Add option to get total shard count from the GatewayDiscordClient

### ISSUE THREAD

**Issue by ByteAlex** [Discord4J/Discord4J#676]
**Feature Description:** There's no way to find out the current shard count on the gateway, just a hacky way to read the ShardingStrategy during build. When using recommended() you may want to know how many shard were recommended after the client was build.

**Justification:** Lavalink-Server requires to know the shard-count for state-handling.

**Comment by Shadorc** [comment]
For the record, it can be done using `GatewayDiscordClient#getGatewayClientGroup().getShardCount()`

**Comment by Alex1304** [comment]
> For the record, it can be done using `GatewayDiscordClient#getGatewayClientGroup().getShardCount()`

Nope that doesn't work. It gives the number of shards connected, so the count given by this method might be inaccurate if some shards are disconnected.
