### ISSUE TITLE
List messages on channels

### ISSUE THREAD

**Issue by mattadamson** [Discord4J/Discord4J#681]
Hi

Is it possible to use the API to set a list of messages / write them to a file as they arrive? e.g. consider I'm in a discord group with a channel and wanted to send a text message for certain messages which have regular expression text matches in them. I could use the API to do this and then use Twillio to notify myself for important messages

Thanks

**Comment by ByteAlex** [comment]
You're probably looking for EventDispatcher#on(Class<? extends Event> event), place MessageCreateEvent.class there and you'll get a next signal for each message dispatch from discord.
All logic for the stuff you want to do can be put behind that.
