### ISSUE TITLE
Pre-check GUILD_MEMBERS intent

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#684]
**Feature Description:** Pre-check for intents each time a request needs a specific intents.

**Justification:** When requesting resources not permitted by intents (either because they are not enabled or allowed), Discord will never answer to the request, making the thread waits forever for a response without signaling it to the user. For example, without the `GUILD_MEMBERS` intent, this code will always timeout.

```java
client.requestMembers(Snowflake.of("1234"))
    .timeout(Duration.ofSeconds(5))
    .subscribe(System.out::println, Throwable::printStackTrace, () -> System.err.println("Done!"));
```

There are two solutions to avoid this, either set a default timeout or pre-checking intents. The second option seems more viable and is not prone to race-conditions (as opposed to permissions) because they are set when logging in and cannot be modified after, either client or server side.

**Comment by quanticc** [comment]
is this currently only affecting `requestMembers` ? Maybe we should rename the issue

**Comment by Shadorc** [comment]
Yes, it seems to only concern this intent.
Also, looking at the documentation (https://discordapp.com/developers/docs/topics/gateway#request-guild-members):
- GUILD_PRESENCES intent is required to set presences = true. Otherwise, it will always be false
- GUILD_MEMBERS intent is required to request the entire member list—(query=‘’, limit=0<=n)
- You will be limited to requesting 1 guild_id
- Requesting a prefix will return a maximum of 100 members
- Requesting user_ids will continue to be limited to returning 100 members

It could be interesting to add pre-checks / docs for these conditions too.

**Comment by TheNumberOne** [comment]
I can take a look into working on this

**Comment by TheNumberOne** [comment]
would it be better for the error to be returned within the flux? or for the error to be returned as soon as the function is called?

**Comment by quanticc** [comment]
Errors should always be emitted through the chain

**Comment by TheNumberOne** [comment]
Note that I didn't add code for validating the following because the `limit` property of RequestGuildMembers is an upper bound.

- Requesting a prefix will return a maximum of 100 members
- Requesting user_ids will continue to be limited to returning 100 members

It might be a good idea to validate that the number of passed user_ids isn't greater than `min(100, limit)`. I can add that if you want.
