### ISSUE TITLE
Update music bot tutorial for 3.1

### ISSUE THREAD

**Issue by quanticc** [Discord4J/Discord4J#685]
https://github.com/Discord4J/Discord4J/wiki/Music-Bot-Tutorial

**Comment by danthonywalker** [comment]
Should the new tutorial cover more topics?

**Comment by danthonywalker** [comment]
Since it's asked a lot, maybe a video series would also be of benefit? Should it supplement or replacement? Though I don't know if I can followup on it quite yet.

**Comment by quanticc** [comment]
I think we should go for small increments first. I believe much of the current page can be reused, although we might want to copy it for 3.1 instead of replacing the current one

**Comment by quanticc** [comment]
The differences weren't large, so I added code showing key differences in steps 11 and 19.
