### ISSUE TITLE
VoiceChannel#join is sometimes empty

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#689]
**Description:** This issue follows https://github.com/Discord4J/Discord4J/issues/523 where two issues were occurring:
1. `VoiceChannel#join` was sometimes never completed (fixed here: https://github.com/Discord4J/Discord4J/pull/678)
2. `VoiceChannel#join` was sometimes empty

This issue concerns the second point. 

**To Reproduce:** It seems that **Leiryl** has been able to reproduce this issue by making the bot joined quickly after a user: https://discordapp.com/channels/208023865127862272/278314058422157320/700195479866048603
However, I can't reproduce even by making the bot joins instantly on a `VoiceStateUpdateEvent`.
It happened to me in production, quickly after the bot has been fully connected, I've triggered a join with this code
```java
LOGGER.info("{Guild ID: {}} Joining voice channel...", guildId.asLong());
return client.getChannelById(voiceChannelId)
    .cast(VoiceChannel.class)
    .flatMap(voiceChannel -> voiceChannel.join(spec -> spec.setProvider(audioProvider)).log(guildId.toString()))
    .doOnNext(ignored -> LOGGER.info("{Guild ID: {}} Voice channel joined", guildId.asLong()))
```
which produces this log: https://pastebin.com/wvYUfejG
We can see the first log, the request, the request completed and then the bot joining the voice channel but the second log has never been displayed even after more than 30 seconds, showing that the voice connection object was empty.

**Expected Behavior:** This can either be fixed smoothly making the bot joins the voice channel and returns the voice connection object or an error can be thrown making the bot leaves the voice channel.

**Actual Behavior:** `VoiceChannel#join` returns empty.

**Version:** 3.1.0-SNAPSHOT

**Comment by quanticc** [comment]
Can you verify this patch? The problem is that our code that waited for a VoiceStateUpdate was not capable of handling multiple events in case the 1st one arriving wasn't from the bot.
