### ISSUE TITLE
Discord4j using outside of discord server for client access

### ISSUE THREAD

**Issue by mattadamson** [Discord4J/Discord4J#690]
Hi 

I'd like to use the library to mimic the operations I get when logged into the discord web app or desktop app i.e. with a given user name / password when I log in and access multiple servers I'm not an admin but have access to.  I want to automatically send messages to certain servers / channels and read messages.  

I'm not clear if this is even possible with the API as it refers to using a bot user which I presume needs to be installed in one of the discord servers I'm in.  If I'm just a standard user ( not admin in any discord server ) is this possible? If so how do I also obtain my discord log in token?  I don't want to write a bot which sits inside a discord server monitor but rather as a client outside the server just mimicing operations the web app does for some very focused searches e.g. using reg ex matches  

Many Thanks

**Comment by ByteAlex** [comment]
Hi,

although this would be possible, what you want to do is forbidden by Discord ToS, so the library does not - and most likely will not support that.

I'd recommend you to use a bot-user and asking an admin to add the bot.

**Comment by mattadamson** [comment]
thanks @ByteAlex ah I didn't realise.  I wonder why its forbidden as it's not different to scraping / checking a web page in the web app if a message is present and parsing e.t.c.  I didn't want to add to add the bot to each server but just a general client on all servers I used for message text.
