### ISSUE TITLE
Bot can't disconnect from voice channel the second time

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#692]
**To Reproduce:** https://pastebin.com/SMQKJ0AC
Send !join then !leave two times in a row, the bot will not disconnect the second time.

**Expected Behavior:** The bot joins then disconnects two times in a row.

**Actual Behavior:** The bot joins, disconnects then joins and get stuck.

**Version:** 3.1.0-SNAPSHOT

**Comment by quanticc** [comment]
Currently investigating. thanks

**Comment by quanticc** [comment]
Let me know if you still have issues to reopen

**Comment by Shadorc** [comment]
Thanks! It works like a charm.

Anyway, I still have a question.
With this code https://pastebin.com/FHPyJ5jp, everything works has expected (yeah, clearly, I try to push Discord4J to its limits but I know that users will do the same haha). But, if I remove the `onErrorResume`, the bot will not be able to disconnect.

It may be intended (I don't manage the error on my side so everything goes wrong), this is why I'm speaking about it here and not in a new issue, but maybe it's a bug.

Anyway, thanks for your amazing work! 3.1 will be amazing <3
