### ISSUE TITLE
Future of Spec Strawman

### ISSUE THREAD

**Issue by darichey** [Discord4J/Discord4J#693]
"Yet another proposal for an alternative to Spec"

# The Status Quo
In D4J 2, there was no way for a user to build up a single http PATCH of multiple fields for an entity, forcing multiple http requests which could have been one. Because that's obviously inefficient, we wanted an elegant solution in D4J 3. The problem essentially decays into having some kind of named, default parameters in Java. From there, we realized that whatever solution we came up with could potentially be applied to other methods as well (even those not doing PATCH). This is traditionally solved with a Builder, but we didn't like forcing `new Builder()....build()` on common interactions with the user-facing api. Thus, [Spec was born](https://github.com/Discord4J/Discord4J/commit/e85ba3ed87051474188f327f7c4d3c500051f3fa).

Spec was just a mutable builder pattern without a finishing method (i.e., a builder without `build()`). Additionally, we realized that most people would simply construct these objects inline, so we provided `Consumer<Spec>` variants which would do that construction for you. Eventually, the "non-consumer variants" were [removed](https://github.com/Discord4J/Discord4J/commit/f92cf79a974dd29d5d8fca00e41eb8bed11544d7#diff-2c826afdc00bda17ee4e8944f741a496).

Specs have been somewhat of a pain point in D4J usage since 3.0. While they solved the aforementioned issues, they have many of their own. Namely,
1. They can still be verbose for simple things. (See #440)
2. They are mutable. (See #585)
3. Templating isn't very intuitive (See [Specs#Templates](https://github.com/Discord4J/Discord4J/wiki/Specs#templates))
4. Admittedly wrong usage can have weird behavior (See #646)

# Goals
To recap, the ideal solution...
1. Allows for a single request interacting with multiple properties
2. Is concise in both simple and complex cases
3. Plays nicely with Reactor
4. Can be templated intuitively

After seeing a [very similar solution](https://github.com/reactor/reactor-core/pull/1979) to a very similar problem in the community, we tentatively decided to move to immutable specs (#585). This solution achieves all but one goal: being concise. It is still very verbose to do simple things.

# Proposal
While working on transitioning to immutable specs, we came up with a new solution. At this point, we would like to receive community feedback. 

## API
```java
Mono<Role> editRole = role.edit()
  .withName("New Name")
  .withPermissions(PermissionSet.of(KICK_MEMBERS))
  .withReason("Because I want to");
```
Goal 1 is accomplished by the fact that this yields only one `Mono<Role>` representing the edit. ✔️ 

It is clearly concise, allowing for fluent chaining and not introducing new scopes. Goal 2 ✔️ 

It might be surprising that the type of this expression is actually `Mono<Role>`. How this is achieved will be exampled in Implementation. For now, note that this allows in-place chaining and direct integration with Reactor, accomplishing goal 3. ✔️ 

Finally, the template story:
```java
static RoleEditMono roleEditTemplate(Role role) {
  return role.edit().withColor(0x7289DA);
}
// ...
roleEditTemplate(role).withColor(override)
```
This could even potentially be altered to work in a `transform()` op to work better in a chain. Goal 4. ✔️ 

## Implementation
The API is accomplished by (potentially abusing?) implementing an "operator" on Mono. After [enabling copy methods](https://github.com/Discord4J/discord-json/commit/7eed123ef0f72ff0f1869a23a5abb8a8637f5a4f) on our json data classes, it is simple to make an immutable wrapper around that. Here is an example implementation:
```java
public class RoleEditMono extends Mono<Role> {

    private final GatewayDiscordClient gateway;
    private final long guildId;
    private final long roleId;

    private final ImmutableRoleModifyRequest request;
    @Nullable
    private final String reason;

    public RoleEditMono(GatewayDiscordClient gateway, long guildId, long roleId) {
        this(gateway, guildId, roleId, RoleModifyRequest.builder().build(), null);
    }

    // ... constructor ...

    public RoleEditMono withName(String name) {
        return withRequest(request.withName(name));
    }

    public RoleEditMono withPermissions(PermissionSet permissions) {
        return withRequest(request.withPermissions(permissions.getRawValue()));
    }

    // ... other properties ...

    private RoleEditMono withRequest(ImmutableRoleModifyRequest request) {
        return new RoleEditMono(this.gateway, this.guildId, this.roleId, request, this.reason);
    }

    @Override
    public void subscribe(CoreSubscriber<? super Role> actual) {
        gateway.rest().getGuildService()
                .modifyGuildRole(guildId, roleId, request, reason)
                .map(data -> new Role(gateway, data, guildId))
                .subscribe(actual);
    }
}
```
With a very straightforward implementation in `Role`:
```java
public RoleCreateMono edit() {
  return new RoleCreateMono(gateway, guildId, Snowflake.asLong(data.id()))
} 
```

As mentioned previously, we feel that this idea is ready for feedback. What are your comments, questions, concerns? 😄

**Comment by danthonywalker** [comment]
I personally approve.

**Comment by austinv11** [comment]
Is it best practice to extend things such as Monos? It seems best practice is to wrap things with custom operators as in [reactor-extra](https://github.com/reactor/reactor-addons/tree/master/reactor-extra). For example, see [MathFlux](https://github.com/reactor/reactor-addons/blob/master/reactor-extra/src/main/java/reactor/math/MathFlux.java)

**Comment by darichey** [comment]
All Mono operators extend `Mono` (more precisely, `MonoOperator`). While this is kind of a very weird "operator", I think it still qualifies. We verified that this passes the TCK.

**Comment by ByteAlex** [comment]
This looks quite promising. I'd like these changes, I guess.

**Comment by quanticc** [comment]
I like this idea. let's ship it! :shipit:

**Comment by nikammerlaan** [comment]
This is way better than the spec consumers

**Comment by Shadorc** [comment]
It's easier to use than spec, it fixes the 4 issues if specs and everyone seems to like it. Go for it!

**Comment by quanticc** [comment]
After some thinking, I realized we need to make sure error handling is not too complicated for this due to the nested subscribe call.

**Comment by quanticc** [comment]
^ Turns out there's no issue, the same `actual` subscriber is passed so no chance of missing a potential error signal. Also works with context propagation.

**Comment by darichey** [comment]
There was one problem with the potential implementation which has recently been resolved. `RoleModifyRequest.builder().build()` works because none of the fields of `RoleModifyRequest` are required. However, this doesn't work in general for requests with required properties. For example, `ChannelCreateRequest.builder.build()` would throw an exception because `name` is unset.

To solve this, Dannie suggested deferring the builder execution with a `Supplier`. Adding a simple wrapper on top of that for a bit more concision gets us this, which works well, as far as I can tell:
```java
@FunctionalInterface
public interface LazyBuilder<T> extends Supplier<T> {
    default LazyBuilder<T> andThen(Function<T, T> f) {
        return () -> f.apply(this.get());
    }
}
```
```java
public final class RoleEditMono extends Mono<Role> {

    private final GatewayDiscordClient gateway;
    private final long roleId;
    private final long guildId;
    private final LazyBuilder<ImmutableRoleModifyRequest.Builder> requestBuilder;
    @Nullable
    private final String reason;

    public RoleEditMono(GatewayDiscordClient gateway, long roleId, long guildId) {
        this(gateway, roleId, guildId, RoleModifyRequest::builder, null);
    }

       // ... constructor ...

    public RoleEditMono withName(String name) {
        return new RoleEditMono(gateway, roleId, guildId, requestBuilder.andThen(it -> it.name(name)), reason);
    }

    // ... other properties ...

    @Override
    public void subscribe(CoreSubscriber<? super Role> actual) {
        gateway.getRestClient().getGuildService()
                .modifyGuildRole(guildId, roleId, requestBuilder.get().build(), reason)
                .map(data -> new Role(gateway, data, guildId))
                .subscribe(actual);
    }
}
```
An alternative solution may come out of https://github.com/immutables/immutables/issues/1202, but we'll go with this for now.

**Comment by danthonywalker** [comment]
I don't think the LazyBuilder is necessary. I find it no more difficult or easier to read `() -> requestBuilder.get().name(name)` than `requestBuilder.andThen(it -> it.name(name))`. Personal taste though.

Also that Function<T, T> can be a UnaryOperator<T>! :D

**Comment by darichey** [comment]
Work has begun in #750. Let's continue any further discussion there.

**Comment by qwbarch** [comment]
I've created a EmbedCreateMono, example usage:
```java
channel.createEmbed()
		.withDescription("description")
		.withColor(Color.CYAN)
```
This returns a Mono\<Message\> on completion.

The issue I'm having is when creating the MessageCreateMono. 
ImmutableMessageCreateRequest#Builder#embed takes an EmbedData argument, which EmbedCreateMono does not expose.
While it's normal for the current consumer specs to return its underlying data, most of the new specs have no need to. 
What's your opinions on having a method to retrieve it?

From EmbedCreateSpec:
```java
public EmbedData asRequest() {
	requestBuilder.fields(this.fields);
	return requestBuilder.build();
}
```
