### ISSUE TITLE
Parse self ID from Discord token

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#695]
**Feature Description:** This issue is more of an idea of optimization than a feature request.

As explained in this picture, the Discord token contains the self ID of the bot concerned.
![image](https://user-images.githubusercontent.com/6506416/81051916-dd8c9900-8ec2-11ea-8794-daf12d6f31f0.png)

It could then be possible to parse the self ID when the client is created by doing something like this (which does not check if the token contain dot).

```java
public static long extractSelfId(String token) {
    return Long.parseLong(new String(Base64.getDecoder().decode(token.split("\\.")[0]), StandardCharsets.UTF_8));
}
```

**Justification:** 
This have several benefits:
- It provides a way to know the self ID instantly without any requests or without waiting for any events.
- It does not need a custom store for the self ID to be stored from events.
- `getSelfId` will now only return `Snowflake` instead of `Mono<Snowflake>`.
- It could be a fast way to check if the token *seems* valid (if it contain at least one dot) or at least not invalid at all.

This have two potential inconvenients:
- If the token provided is invalid (does not contain any dot for example), an exception needs to be handled.
- If, for some reason, someday, Discord changes the way tokens are created, this method will not work anymore.

**Comment by ByteAlex** [comment]
Self-ID comes with the very first discord event received - session ready. What else are you going to do before you received a session ready?

More than that, are you sure that it contains the bot-user's id? I had in mind that it conains the creators user-id.

**Comment by Shadorc** [comment]
I'm sure it contains the bot-user's ID, I've been using this method for some times.
The only benefit that I see is not concerning the timing when you can get this info but more of the way you store it and it's accessibility. With the parsing solution, you're sure to have it at any times so you don't need a `Mono` anymore.

I don't have a preference but this issue was discussed yesterday in the Discord4J server and I've found that it was interesting enough to open an issue about it.

**Comment by ByteAlex** [comment]
I just made a test for that and I can agree that it contains the bot-user id for all of my tokens.

**Comment by Alex1304** [comment]
It can also be useful to get self-id when using a REST-only configuration. It doesn't seem possible currently to get self id without making a REST request in case the gateway is not used.

**Comment by ByteAlex** [comment]
@quanticc 
This could save us a lot of redis calls in distributed structure.
Overall I'd say we can take this option to parse it and construct the selfId, and in case we receive an ReadyEvent, we take that id, just to make sure we have that "fallback" in case discord decides to silently change something.

**Comment by quanticc** [comment]
Even though redis calls shouldn't be affected as we have a custom store to cache the id, I'm open to look at a PR for this feature.

**Comment by nicholaslz** [comment]
> **Feature Description:** This issue is more of an idea of optimization than a feature request.
> 
> As explained in this picture, the Discord token contains the self ID of the bot concerned. ![image](https://user-images.githubusercontent.com/6506416/81051916-dd8c9900-8ec2-11ea-8794-daf12d6f31f0.png)
> 
> It could then be possible to parse the self ID when the client is created by doing something like this (which does not check if the token contain dot).
> 
> ```java
> public static long extractSelfId(String token) {
>     return Long.parseLong(new String(Base64.getDecoder().decode(token.split("\\.")[0]), StandardCharsets.UTF_8));
> }
> ```
> 
> **Justification:** This have several benefits:
> 
> * It provides a way to know the self ID instantly without any requests or without waiting for any events.
> * It does not need a custom store for the self ID to be stored from events.
> * `getSelfId` will now only return `Snowflake` instead of `Mono<Snowflake>`.
> * It could be a fast way to check if the token _seems_ valid (if it contain at least one dot) or at least not invalid at all.
> 
> This have two potential inconvenients:
> 
> * If the token provided is invalid (does not contain any dot for example), an exception needs to be handled.
> * If, for some reason, someday, Discord changes the way tokens are created, this method will not work anymore.

I don't think that '_' is a valid character in Base64. How did you get the value from the second part of the token?

**Comment by NovaFox161** [comment]
Aside from necro'ing a 2 year old closed issue, `_` is in fact a valid character. Base64 *generally* uses A-Za-z0-9 and `-` `_` since they are URL-safe. And `_` is commonly seen in discord's tokens, meaning whatever Base64 they use, it includes `_` as a valid character.

**Comment by nicholaslz** [comment]
> Aside from necro'ing a 2 year old closed issue, `_` is in fact a valid character. Base64 _generally_ uses A-Za-z0-9 and `-` `_` since they are URL-safe. And `_` is commonly seen in discord's tokens, meaning whatever Base64 they use, it includes `_` as a valid character.

Also when I converted the base 64 to decimal it gave 12202749152

**Comment by NovaFox161** [comment]
I'll be honest, I'm not sure how this has any relevance to this issue. Again, a 2 year old issue that was already closed for a long time. 

Furthermore, everything after the first `.` should be ignored by a library (and indeed is), because the timestamp doesn't matter to a bot's normal operation. And Discord has already hinted at everything after `.` possibly changing. For all intents and purposes, it does not matter. All that matters is the first several characters of the token, which is a base64 encoded string of the bot's user ID.
