### ISSUE TITLE
Dropping the dependency on java.awt by using a custom Color class

### ISSUE THREAD

**Issue by utybo** [Discord4J/Discord4J#696]
**Feature Description:** Stop having a dependency on `java.awt` for colors and use a class specific to Discord4J.

**Justification:** In the modular world (and especially when using "new" tools like `jlink` that allow you to create a custom, smaller JRE specifically for your application), Discord4J requiring `java.awt` solely for colors is very cumbersome, as it makes Discord4J depend on the `java.desktop` module. Thus, any reduced JRE made specifically for projects that use Discord4J have a transient dependency on `java.desktop`, which heavily increases the size of the resulting JRE.

Using a custom Color class would solve this and stop this awkward and useless dependency on `java.awt`. While this made sense a few years ago (because you could always assume that you have the entire JRE available), nowadays that becomes problematic for projects which want to use Discord4J *and* things like `jlink` for making trimmed down JREs.

I know this is a lot to ask for though, because doing that would probably be a big breaking change.

**Comment by danthonywalker** [comment]
We were already planning this. Though not replacing with a custom Color class, just returning an int. What benefits would a custom color class do?

**Comment by utybo** [comment]
Great news and thanks for the quick response!

I admit a custom color class would only be for quality of life things like making RGB colors out of individual int values for the R, G and B channels (something like AWT's Color constructors) -- but static methods could do the job perfectly fine.

**Comment by danthonywalker** [comment]
We'll observe some possibilities and see if there's a design that can work. This is a feature that will most certainly come in 3.1.x sonce it's a breaking API change.

**Comment by darichey** [comment]
I think a custom Color class is beneficial for api discoverability.

**Comment by Shadorc** [comment]
It seems that one awt.Color dependency has been missed here: https://github.com/Discord4J/Discord4J/blob/0417e12eae764a197541b0088b182736d0507575/core/src/main/java/discord4j/core/object/audit/ChangeKey.java#L92

**Comment by darichey** [comment]
Addressed in #862
