### ISSUE TITLE
Inviter can sometimes be null

### ISSUE THREAD

**Issue by jbonnici94** [Discord4J/Discord4J#701]
**To Reproduce:** A website bot creates an invite every now and then and discord will have no inviter attached

**Expected Behavior:** Should still be able to get the invite with an `Optional` inviter

**Actual Behavior:** Null pointer exception

**Version:** 3.0.13

**Other:**
[Exception backtrace](https://github.com/Discord4J/Discord4J/files/4595233/message.txt)
![Invite on discord](https://user-images.githubusercontent.com/55535619/81335667-45500900-90a8-11ea-8fda-b770c7b15e4f.png)

**Comment by Doc94** [comment]
Well i check https://discord.com/developers/docs/resources/invite#invite-object and the Inviter can be null... 

if you need a fast patch you can try use the branch in the PR with the fix.

**Comment by jbonnici94** [comment]
Thanks! 🙇
