### ISSUE TITLE
False concurrent voice handshakes detected if a voice socket setup error occurred

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#703]
**To Reproduce:** Try to join a voice channel, generate a voice socket setup error (for example, by setting the timeout value to 0s) then try to reconnect without error.

**Expected Behavior:** The bot joins the voice channel the second time.

**Actual Behavior:** https://pastebin.com/wSW79v1D

**Version:** 3.1.0-SNAPSHOT

**Comment by quanticc** [comment]
I reworked some of the concurrent edge cases.

If some combination of timeout parameters are still causing issues, let us know to keep a record of them, and we can maybe set a validation on them.
