### ISSUE TITLE
OAuth2 module

### ISSUE THREAD

**Issue by quanticc** [Discord4J/Discord4J#715]
Implement this using D4J ecosystem https://discord.com/developers/docs/topics/oauth2

I have a question though, should this exist in a new module, in a new package inside core, or a separate repository?

In case you're interested @WinteryFox

**Comment by WinteryFox** [comment]
I am interested in starting the OAuth2 initiative for D4J, yep. I am kind of on the fence as to what it should be, since I think some people would prefer to use this as a standalone thing and would probably not use any of the bot features. So maybe it should be separate or maybe not...

**Comment by darichey** [comment]
Which existing components in D4J would this module (separate repo or not) be able to reuse?

**Comment by WinteryFox** [comment]
Well mostly the objects I assume

**Comment by darichey** [comment]
Which objects? Aren't most of the entities different because you get access to different fields depending on scopes?

**Comment by WinteryFox** [comment]
Honestly, I'm not entirely sure right now. I would have to look into it more in-depth, which I will do later.

**Comment by austinv11** [comment]
I personally see this as being a nice sister project (so maybe it should get its own repo?), even if code reusability isn't totally possible. Especially since D4J doesn't necessarily imply a bot API but rather a Discord API. I think this could have similar scope as a potential webhook and/or rpc client.

**Comment by WinteryFox** [comment]
I've been making a start on this over at https://github.com/WinteryFox/DiscordOAuth2

**Comment by CeH9** [comment]
> I personally see this as being a nice sister project (so maybe it should get its own repo?), even if code reusability isn't totally possible. Especially since D4J doesn't necessarily imply a bot API but rather a Discord API. I think this could have similar scope as a potential webhook and/or rpc client.

Well, code reusability will be possible in case of 3+ repo(artifacts) where common stuff (e.g. entities) extracted into sole repo which then used as dependency for other two:

```
com.discord4j:discord4j-entities
  - no deps

com.discord4j:discord4j-core
   -  include "com.discord4j:discord4j-entities"
  
com.discord4j:discord4j-oauth
  -  include "com.discord4j:discord4j-entities"
```
