### ISSUE TITLE
Add a function to get the latest messages sent in a MessageChannel

### ISSUE THREAD

**Issue by l0c4lh057** [Discord4J/Discord4J#720]
**Feature Description:**
The `MessageChannel#getLatestMessages` function should return the last messages sent in the channel in reverse chronological order.

**Justification:**
Currently there is no good way to get the latest messages sent in a channel. In a conversation on the D4J discord server I asked if there is a better way than `getMessagesBefore(Instant.now())` and I pointed out that it is a bad way since there can be a difference between the time of the bot and discord's time which could result in missing messages that were sent in the last few seconds. As a workaround we found something like `Instant.now().plus(Duration.ofSeconds(30))` but that is just a hacky way to fix this issue without actually fixing the underlying problem. Looking at the MessageChannel class I found another way which would `getLastMessage` and then request message before the id of that message but that would require two API requests.
After that I looked up how to request messages from a channel in the discord docs and found out that [**all** the query parameters are optional](https://discord.com/developers/docs/resources/channel#get-channel-messages). I tested requesting messages without any of those parameters and, as I expected, I got the last messages in the channel beginning with the newest message.

**Comment by danthonywalker** [comment]
By the time you receive the response from Discord a message could already have been sent. There is no atomic way to retrieve messages as you're asking them to.

**Comment by l0c4lh057** [comment]
Of course you can't solve the problem with the delay. But it fixes the problem that comes with times not being exactly the same between discord and bot. And it might be irritating if you requested all messages before `Instant.now()` and all the messages sent within the last 10 seconds are missing. And always adding a few seconds to the current time is a bad way too, not only because it looks weird requesting messages sent in the future but also because most D4J users would probably not do it.

I don't want you to fix the problem of response time as you said in the general channel but the issue of not being able to request the last messages. And then it would not be `awful lot of work` as you said but just a request with neither `before` nor `after` parameter.

**Comment by danthonywalker** [comment]
`And it might be irritating if you requested all messages before Instant.now() and all the messages sent within the last 10 seconds are missing.` This should never happen. If you're doing a `take(1)` to `take(100)` (or really any type of filtering that'd terminate the Flux before the next batch) then the time is always the same as these types of requests are done in batches (of 100).

**Comment by danthonywalker** [comment]
Additionally the only true use case for this would be for `bulkDelete` to have a guarantee you are deleting the most recent messages of the channel.
You cannot atomically guarantee between the time you receive those messages to the time you send out the bulk delete request that you will hit every message and I don't think it is up to D4J to help with this as there are many strategies.

My suggestion would be for extremely sensitive operations like this where if you must require this amount of precision to gather messages to lock the channel for users to send messages before attempting.

**Comment by l0c4lh057** [comment]
If I change the time of my computer back by one minute and then request all messages before `Instant.now()` I would not get any message sent within the last minute. And while I would not change the time like this by myself this can happen.

**Comment by danthonywalker** [comment]
I personally do not think we should be compensating for poorly configured system clocks. Our own rate limiting systems would fail even if this was done, I don't think it's a valid argument.

**Comment by l0c4lh057** [comment]
Another reason why I think it should get added: You are saying that you try to mirror the discord API as good as possible. And I think that this includes making everything possible that the API allows you to do.

**Comment by quanticc** [comment]
Right now the way of performing this operation would be to call this method in [ChannelService](https://www.javadoc.io/doc/com.discord4j/discord4j-rest/latest/discord4j/rest/service/ChannelService.html):

```java
getMessages(long channelId, Map<String,Object> queryParams) 
```

Are there any issues with exposing this method to `RestChannel` and the core module?

**Comment by danthonywalker** [comment]
Counterargument: We don't do that, really. We don't have an OAuth2 module (yet) and if we wanted to support every usage of the API then that means also including the `between` option, but I don't think anyone would ever use that (I don't even know what it does). Additionally, the varying combinations of these parameters would require them to become specs and even more of a burden to initiate requests.

I think something like this is too niche. It's asking for a level of precision that ultimately cannot be satisfied even if implemented into the core API.

**Comment by darichey** [comment]
I don't find this to be too niche if simply sending no query params accomplishes the task. My only concern is that the behavior of doing so isn't documented as far as I can tell.
