### ISSUE TITLE
VOICE_SERVER_UPDATE endpoint can be null and it should be ignored

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#725]
**To Reproduce:** Inconsistent and not really important.

**Expected Behavior:** null `endpoint` field should be ignored according to this issue: https://github.com/discord/discord-api-docs/issues/1739

**Actual Behavior:** 
```Error while decoding JSON (com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of discord4j.discordjson.json.gateway.ImmutableVoiceServerUpdate, problem: Cannot build VoiceServerUpdate, some of required attributes are not set [endpoint] at [Source: UNKNOWN; line: -1, column: -1]): {"t":"VOICE_SERVER_UPDATE","s":477069,"op":0,"d":{"token":"f8eb804ee40ebf3d","guild_id":"691022703368601651","endpoint":null}}```

**Version:** 3.1.0-SNAPSHOT

**Other:** If I remember well, it was already ignored in 3.0.X

**Comment by Shadorc** [comment]
Official response from Jake: `Hmmm. This hasn't been documented as nullable I guess. But a null means that the voice server you were allocated has gone away and we are trying to reallocate the server on our backend.`

**Comment by quanticc** [comment]
Thanks. This is a regression from migrating to discord-json project. Internally we already acknowledge for nullable endpoint.

Closed after Discord4J/discord-json#23
