### ISSUE TITLE
TimeoutException on every voice connection

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#738]
**To Reproduce:** Simply try to connect to any voice channel.

**Expected Behavior:** The bot succeeds to connect.

**Actual Behavior:** `reactor.core.Exceptions$ErrorCallbackNotImplemented: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms`

**Version:** 3.1.0.RC3

**Comment by quanticc** [comment]
Thanks for reporting it. We're trying to use [virtual fields](https://immutables.github.io/encoding.html#virtual-fields) for our `Possible`-based objects to reduce memory usage and applied this change recently at https://github.com/Discord4J/discord-json/commit/24fdc366b6673eac3ac1532b2eb55c8e10b7bd08

This meant we had to adapt Jackson default mapper to not use field-based serialization (as `Possible` virtual fields are stored as 2 fields). https://github.com/Discord4J/Discord4J/commit/a67ad1c7f9750f596a37c6af4bc6635008882edb

However the voice Json objects have not migrated to the discord-json project and were still exposing their fields directly. The commit changes that.

Can you try with latest snapshot?

**Comment by Shadorc** [comment]
Thanks for the explanations, this is fixed!
