### ISSUE TITLE
Support for tags in Roles

### ISSUE THREAD

**Issue by Doc94** [Discord4J/Discord4J#741]
**Feature Description:** Add support in Role class to get tags if available, this need be documented but in test actually find two, 
- bot: this tag have the snowflake of the BOT if the role is created when BOT join.
- premium_subscriber: this tag are null but identify the role how to the BOOSTER role of guild.

`
{
        "id": "563400424527364117",
        "name": "Fortnite Hispano BOT",
        "permissions": 8,
        "position": 18,
        "color": 6323595,
        "hoist": false,
        "managed": true,
        "mentionable": false,
        "tags": {
            "bot": "544316641425489925"
        },
        "permissions_new": "8"
    },
    {
        "id": "572856761917243412",
        "name": "Silenciado [texto]",
        "permissions": 0,
        "position": 7,
        "color": 0,
        "hoist": false,
        "managed": false,
        "mentionable": false,
        "permissions_new": "0"
    },
    {
        "id": "585558309558550529",
        "name": "Nitro Booster",
        "permissions": 67108864,
        "position": 4,
        "color": 7658737,
        "hoist": false,
        "managed": true,
        "mentionable": false,
        "tags": {
            "premium_subscriber": null
        },
        "permissions_new": "67108864"
    },
`

**Justification:** https://github.com/discord/discord-api-docs/issues/1537#issuecomment-656308581

**Comment by quanticc** [comment]
Alright, but it's not a deployed feature yet so we shall wait

**Comment by Shadorc** [comment]
This feature has been documented : https://github.com/discord/discord-api-docs/pull/2230

**Comment by quanticc** [comment]
Thanks for the heads up
