### ISSUE TITLE
Simpler formatting of ClientException::toString

### ISSUE THREAD

**Issue by quanticc** [Discord4J/Discord4J#746]
Remove not so useful information like headers from the `toString` method of `ClientException` and give relevance to the ErrorResponse field if present.

This *should be* as simple as removing `toString` method override from `ClientException`. The message of it should be enough as it includes:

- Endpoint
- Status code
- Error Response

**Comment by darichey** [comment]
Would it be possible to get some different details depending on the log level? Couldn't be done in `toString` though.
