### ISSUE TITLE
Embed fields such as author icon are considered non-optional

### ISSUE THREAD

**Issue by PaleoCrafter** [Discord4J/Discord4J#747]
I have encountered a bug in Discord4J that appears to have been introduced with the upgrade to 3.1.0. Namely, it concerns (to my knowledge) embeds and their properties:

**To Reproduce:**
 * Generate a message with an embed without e.g. author icon
 * Read that message using Discord4J and look at the embed

**Expected Behavior:**
 * `Embed.Author#getIconUrl` returns an empty `Optional<String>`, `null` or similar

**Actual Behavior:**
 * A `java.util.NoSuchElementException` exception is thrown

**Version:** 3.1.0

**Other:** I've only come across the issue with the author icon out in the wild so far, but I'd expect more fields to actually be optional.

**Comment by darichey** [comment]
There's a few `Possible::get()` uses in `Embed` that were overlooked. Ideally they would've been mapped to `Optional` and the return types would be changed. Not sure what the best course of action is here since 3.1 is released.

**Comment by darichey** [comment]
quanticc pointed out we can annotate these methods as `@Nullable` and change the implementation to fallback to `null`. While we generally try to avoid that in `core`, I think it's the best option here until 3.2. That was the previous behavior anyways, we just didn't know.

**Comment by darichey** [comment]
Will be fixed in 3.1.1 with the `@Nullable` solution and with some incompatible `Optional` changes in 3.2. If you need the fix before release, you can [use a snapshot](https://github.com/Discord4J/Discord4J/wiki/Using-latest-snapshots) of either branch.

**Comment by PaleoCrafter** [comment]
Thanks for the speedy solution @darichey! I've worked around the issue for now by manually catching the exception and mapping it to `null` (which is fine by me, as I'm using it from Kotlin, anyway), so looking forward to the fixed version!
