### ISSUE TITLE
Voice 4014 Disconnected sometimes considered as an error

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#760]
This issue has been created to gather more feedbacks from other users because I don't have any way to reproduce this.

**To Reproduce:** Unknown, this issue is inconsistent.

**Expected Behavior:** The voice connection should be closed without error.

**Actual Behavior:** https://pastebin.com/dZq7jUYq

**Version:** 3.1.0

**Other:** This exception has been catched by the last `.onErrorResume` of my chain, this is why it shows `An unknown error occurred`

**Comment by quanticc** [comment]
Haven't explored this in depth, but the only way we could output an error signal is when the status code is specifically not 4014. So this is a head scratcher for now, I hope to find more instances of this issue.

https://github.com/Discord4J/Discord4J/blob/48f6304d8d9f143227ab57ce5504427a8637d540/voice/src/main/java/discord4j/voice/DefaultVoiceGatewayClient.java#L417-L418

**Comment by Shadorc** [comment]
It seems to be similar to the bug where 404 IS thrown even with EmptyOnNotFound set

**Comment by quanticc** [comment]
Will reopen if we find a way to reproduce
