### ISSUE TITLE
Restructure context-dependent properties such as Message#getGuildId

### ISSUE THREAD

**Issue by UnderMybrella** [Discord4J/Discord4J#762]
Certain properties such as Message#getGuildId are only present in certain scenarios, such as when provided as part of an event. This is not properly conveyed to the end user, and can result in very confusing errors (Guild ID not being present on a message sent in a guild).

While having these properties be available through the Message object is definitely ideal, I do think it merits a rethink as to *how* these should be exposed - is it a problem that can be solved just through documentation, or would a separate interface be better to make it concrete that the property will be missing?

I'm not sure if there are other properties that would require this - as far as I know, the others only affect events, so they're always present.

**Comment by quanticc** [comment]
@Discord4J/members for context https://discordapp.com/channels/208023865127862272/278314058422157320/746290662273712190

**Comment by quanticc** [comment]
Going to update the docs for this method to cover potential confusion. Since this is the only field (so far), I don't think we should look at a different type for now.
