### ISSUE TITLE
Add a convenience method for unicode codepoints

### ISSUE THREAD

**Issue by qwbarch** [Discord4J/Discord4J#765]
**Feature Description:** 
Provide a convenience method for unicode codepoints.

**Justification:**
Currently, the way to represent codepoints as a ReactionEmoji looks verbose.
For example, 😂 has a codepoint of U+1F602. To represent this as a **ReactionEmoji** you could use the following:
`ReactionEmoji.unicode(Character.toString(0x1F602))` - Works only in Java 11+
`ReactionEmoji.unicode(new String(Character.toChars(0x1F602)))`
This was suggested by Dannie & Troposphere during a discord [discussion](https://discordapp.com/channels/208023865127862272/451125724766535710/743170968285085796).

**Comment by darichey** [comment]
Another option is `ReactionEmoji.unicode("\uD83D\uDE02")` which you can get by just copy and pasting :joy: into IntellIJ. Is it really any worse?

**Comment by danthonywalker** [comment]
I think it's a matter of discoverability. Most sites notoriously Emojipedia only give you the codepoint. This is likely what most users copy/paste in and is sometimes wrong.

The idea should be you can just throw in a codepoint and it just works :tm:

**Comment by darichey** [comment]
Right, but isn't that even more work than just pasting the emoji itself? Why do people choose to try the codepoint in the first place?

**Comment by danthonywalker** [comment]
Because it doesn't always work. It highly depends on the editor and even in the editor it depends on settings. I know for IJ some users have problems with copy-pasting emojis and it doesn't end up working.

**Comment by JasonTheKitten** [comment]
> Right, but isn't that even more work than just pasting the emoji itself? Why do people choose to try the codepoint in the first place?

The other day I was trying to edit some code that the writer had used the actual emoji in, so when I went to save, my IDE complained about the encoding.
