### ISSUE TITLE
404 Not Found thrown with emptyIfNotFound() set

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#771]
This issue has been created to gather more feedbacks from other users because I don't have any way to reproduce this.

**To Reproduce:** Unknown, this issue is inconsistent but `DiscordClientBuilder#onClientResponse(ResponseFunction.emptyIfNotFound())` is set.

**Expected Behavior:** An empty Mono is propagated.

**Actual Behavior:** https://pastebin.com/ztdq2BQC

**Version:** 3.1.0

**Other:** This issue *may be* similar to https://github.com/Discord4J/Discord4J/issues/760

**Comment by quanticc** [comment]
So far I've been unable to reproduce this. I thought delete having a Mono<Void> return could have something with it but apparently it doesn't.

What puzzles me is that your stack trace doesn't have any checkpoint information. Normally you should see this on top of the stack trace:

discord4j.rest.http.client.ClientException: DELETE /channels/384091456408911870/messages/752962756671701122 returned 403 Forbidden with response {code=50003, message=Cannot execute action on a DM channel}
	at discord4j.rest.http.client.ClientResponse.clientException(ClientResponse.java:171)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Apply discord4j.rest.response.EmptyResponseTransformer@18271936 to DELETE /channels/384091456408911870/messages/752962756671701122 [RequestStream]
	|_ checkpoint ⇢ Request to DELETE /channels/384091456408911870/messages/752962756671701122 [RequestStream]
	|_ checkpoint ⇢ Request to DELETE /channels/384091456408911870/messages/752962756671701122 [DefaultRouter]
Stack trace:
		at discord4j.rest.http.client.ClientResponse.clientException(ClientResponse.java:171)
		at discord4j.rest.http.client.ClientResponse.lambda$createException$13(ClientResponse.java:149)
...
```

**Comment by quanticc** [comment]
Will reopen if we find a way to reproduce
