### ISSUE TITLE
LEAK: ByteBuf.release() was not called before it's garbage-collected

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#772]
This issue has been created to gather more feedbacks from other users because I don't have any way to reproduce this.

**To Reproduce:** Unknown, this issue is inconsistent.

**Expected Behavior:** No error.

**Actual Behavior:** https://pastebin.com/G9rGbsvx

**Version:** 3.1.0

**Comment by quanticc** [comment]
> reactor.netty.channel.MonoSendMany$SendManyInner.run(MonoSendMany.java:317)

I'm going to add debugging information to our gateway sending in case that's the reason. Normally the framework (reactor-netty, netty) should release outbound objects as they go beyond Discord4J control towards the wire.

**Comment by quanticc** [comment]
I'm not sure this is an upstream issue, but as a heads up: v3.1.1 pulls latest reactor-netty that addresses some mem leak sources.

**Comment by quanticc** [comment]
Let me know if you encountered more of these since 3.1.1 release

**Comment by Shadorc** [comment]
I still encounter the two other inconsistent issues but this one seems to be rarer... (or fixed?)
