### ISSUE TITLE
Creating a webhook results in a NullPointerException when not setting the avatar as an Image

### ISSUE THREAD

**Issue by HeyItsMeNobody** [Discord4J/Discord4J#779]
**To Reproduce:** Create a webhook without using setAvatar and an image

**Expected Behavior:** Create the webhook as documented by Discord and Discord4J

**Actual Behavior:** It throws a NullPointerException saying it requires an avatar. https://pastebin.com/raw/USE8DN7W

**Version:** 3.1.1

**Comment by quanticc** [comment]
Duplicate of #777. This is fixed in the development version `3.1.2-SNAPSHOT`. For instructions on how to use this version check this page: https://wiki.discord4j.com/en/latest/Using-latest-snapshots/
