### ISSUE TITLE
Proposal for a new cache model

### ISSUE THREAD

**Issue by Alex1304** [Discord4J/Discord4J#782]
I came up with a concept for a new cache model, solving many problematics we have with the current Stores API. That new model would have the following features:
* A simple API with only one elementary method for each operation (`save`, `find`, `delete`, maybe `count` as well)
* A single cache instance for all type of data
* An harmonized format for keys so we don't need a separate API for simple-Long keys and double-Long keys (members, messages, voice states)
* Metatags attached to cached data that will allow proper handling of shard invalidation, and support for REST caching (could be a solution for issue #636). Essentially REST calls would be able to populate the cache, useful when loading message history, or whatever entity you don't have the gateway intents enabled for.

## The key model

Currently all cached entities are indexed by their ID. This forces to have special treatment for entities that require two IDs (members, messages, voice states). My idea was to identify data with a path instead. The path could have a format similar to how REST routes are formatted (see examples below). When saving an entity, you just specify at which path to save it, and the implementation will do the necessary to organize the data following the path (a tree data structure would be adapted).
A few examples of how paths can be powerful:
* `.find("channels")` - retrieves all cached channels
* `.find("channels/123456789")` - retrieves data for channel ID 123456789
* `.find("channels/123456789/messages")` - retrieves all cached messages for channel ID 123456789
* `.find("channels/123456789/messages/987654321")` - retrieves a specific cached message in the channel

Of course there might be better ways to implement the idea, for example I think we can have a more sophisticated `Path` object instead of just a string with a `/` separator. We could also imagine a Class parameter to get the entities in the correct type (or include the type parameter directly in the path object). 

## Metatags

In addition to paths, we could add metatags to the data that is being cached. Those tags can indicate the source of the data (whether it's been obtained via an event, via a member request, via REST... can be useful for shard invalidation and to add rules to invalidate data from REST), or could be user defined, when we need to filter the content of the cache for a specific purpose.
Examples:
* `.delete("guilds", "shard0")` - deletes (invalidates) all cached guilds which data was obtained via GuildCreateEvents on shard 0
* `.save(data, "guilds/123456789/members/987654321", "shard2")` - saves a new member that was obtained via a MemberChuckEvent on shard 2
* `.save(data, "channels/123456789/messages/987654321", "REST")` - saves a new message that was obtained from REST
* `.find("channels/123456789/messages", "pinned")` - retrieve data for all cached pinned messages in channel 123456789

It's up to the implementation to manage internally the indexing of tags so that the retrieval can be fast.

## API

We would have a single interface that looks like this:

```java
public interface Store {
    Mono<Void> save(Object data, Path path, Tag... tags);
    Flux<Object> find(Path path, Tag... tags);
    Mono<Void> delete(Path path, Tag... tags);
    Mono<Long> count(Path path, Tag... tags);
}
```
(maybe `Path` and `Tag` could be wrapped in a single object since there's repeating parameters, but what I give here are indications, everything is open to discussion). 

## Implementation

Discord4J would provide at least 1 default implementation for standard bots, and ideally 1 another default implementation for distributed bots. We wouldn't need to have several implementations like jdk, caffeine, etc, as everything is unified. What will require the most work is defining how to configure the store, and deciding what could be the default values when creating a Discord bot without any customization in the Core module.

From my point of view the configuration will mostly consist of defining rules on specific path prefixes and tags. For example, if we want to disable cache for voice states, currently we need to use NoOpStore, with this new model we would just need to add a rule saying not to save if the path starts with "voicestate". Another example : if we want all entities obtained from REST to expire after 2 hours, we would need to add a rule on the "REST" tag that schedules invalidation after 2 hours. In the end, configuring a `Store` would be as simple as:
```java
Store store = DefaultStore.builder()
        .addRule(condition, action)
        .addRule(condition, action)
        .addRule(condition, action)
        .addRule(condition, action)
        //...
        .build();
```
A more direct method `DefaultStore.create()` would create a Store with predefined rules to use by default when the user does not provide a custom `Store`. Note that the concept of rules is decoupled from the Stores API itself, it is purely an implementation thing.

I'd be happy to hear your feedback on this, I truly think it can work but I also might have missed a few important points (for example I haven't talked about the specifics of how to integrate this new API to the existing core, rest and gateway modules). If in the end we manage to consolidate this proposal, I'd also be happy to start drafting a PR for this.

**Comment by ByteAlex** [comment]
For large scale bots this will probably stll not work.
Instead of Paths, I'd recommend using a column based nosql solution like cassandra for modelling the cache.
As always - the snowflake is the uuid - but some fields can be retrieved individually. 
This saves a lot of traffic between the cache server and the D4J application(s).

Also I'd recommend not using (too) generic stores.
We have like 6 or 7 different caches. Just have an own implementation per cache which is abstracted from some super class, but define the details down there. That'd give way more options to fine-tune per cache.

I don't know the exact details, but @quanticc and I were discussion about that in DMs iirc. 
Quote me on that tomorrow again. It's 1 am and I just wanted to give my opinion to this. :P

**Comment by Alex1304** [comment]
Well the whole idea is to have only one Store instance for everything, with potentially the ability to have a totally different and adapted behavior depending on the prefix of the path (if you prefer breaking it down to 6-7 caches you'd be always free to do so in your implementation, but at the API level you only need to say "hey give me all cached members for guild x")
I'm not really sure what you mean by
> As always - the snowflake is the uuid - but some fields can be retrieved individually.
Are there any other special kind of queries that you wouldn't be able to make that way?

**Comment by Alex1304** [comment]
I'm closing this since I've come up with a completely different proposal, any further discussion should preferably be done on the draft PRs https://github.com/Discord4J/Stores/pull/9 and https://github.com/Discord4J/Discord4J/pull/788.
