### ISSUE TITLE
Support Server Templates

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#791]
**Feature Description:** Bots are now fully allowed to manipulate guild templates.

**Justification:** 
https://github.com/discord/discord-api-docs/pull/1712
https://github.com/discord/discord-api-docs/pull/2144

**Comment by quanticc** [comment]
v8 only?

**Comment by Shadorc** [comment]
I don't think. There is no mention of it, and no reason why it could not be retrocompatible.

**Comment by p4czyk** [comment]
Just began working on that issue. 🚀

**Comment by quanticc** [comment]
@Redstoneguy129 is already on this

**Comment by p4czyk** [comment]
Oh okay. Sorry. :-/

**Comment by Redstoneguy129** [comment]
Done this issue should prob be closed after my PR is merged.
