### ISSUE TITLE
Automatically retry on CloudFlare's error 520

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#802]
**Feature Description:** Automatically retry on CloudFlare's error 520

**Justification:** I've recently received some of these errors in the last days (https://pastebin.com/JfeZVMUE). It's probably a temporary issue with the discord API but it could be interesting to automatically retry on Discord4J side when receiving them.

**Comment by quanticc** [comment]
OK, this status can be added to RequestStream::serverErrorRetryFactory method list of status codes that are auto retried.

It should target 3.1.x branch

**Comment by quanticc** [comment]
Closed via #804
