### ISSUE TITLE
No longer receiving events

### ISSUE THREAD

**Issue by Katzen48** [Discord4J/Discord4J#805]
**To Reproduce:** Run a bot for a couple days with following events subscribed: MessageCreateEvent, MemberJoinEvent, MemberLeaveEvent, BanEvent, UnbanEvent, VoiceStateUpdateEvent, ReactionAddEvent, ReactionRemoveEvent.
Discord will close the connection during that time and the bot will print the following message: 
```
[ERROR] (reactor-http-epoll-4) [G:516a50a0, S:0] discord4j.common.close.CloseException: WebSocket closed: -1 caused by discord4j.gateway.retry.GatewayException: Inbound close status
[ INFO] (reactor-http-epoll-4) [G:516a50a0, S:0] Reconnected to Gateway
```

**Expected Behavior:** Bot reconnects and continues receiving events.

**Actual Behavior:** After a while, the events are no longer received. No stacktrace.

**Version:** 3.1.1

**Comment by danthonywalker** [comment]
Very likely you have an error in your event stream and you don't habdle the error and thus it cancels the subscription. Discord4J automatically reconnects and those logs are elsewhere. Discord will occasionally disconnect, that is expected and that is what those logs indicate, but reconnection is happening.

Ask on our Discord for reviewing your event code and how to nullify errors cancelling streams.
