### ISSUE TITLE
Multiple "on" listeners

### ISSUE THREAD

**Issue by dragneelfps** [Discord4J/Discord4J#815]
If I have multiple `client.on(Event::class.java)` , for example
```
client.on(MessageCreateEvent::class.java).{ foo() }
client.on(MessageCreateEvent::class.java).{ bar() }
```
Only foo works. Shouldn't all listeners get the event ?

**Comment by quanticc** [comment]
Fixed in our Discord support channel https://discord.com/channels/208023865127862272/451125724766535710/782188062179590154
