### ISSUE TITLE
Migrate wiki to our documentation repository

### ISSUE THREAD

**Issue by quanticc** [Discord4J/Discord4J#816]
We didn't like the limited theme options when using read the docs, so we're switching to [Docusaurus](https://v2.docusaurus.io/) for our documentation.

In the future we might migrate the whole website to be based off this tool, so we created a new repo instead of using this one.

Pending tasks:

- [x] Setup [new repo](https://github.com/Discord4J/documentation)
- [x] Copy markdown files in [docs](https://github.com/Discord4J/Discord4J/tree/master/docs) to our new repo
- [x] Update frontmatter and rename-according-to-standards.md
- [x] Move images to `static/img`
- [x] Deploy docusaurus somewhere (pending open-source plan from Netlify/Vercel, backup is to self-host)
- [ ] Apply for Algolia DocSearch for searchable docs pages
- [x] Update our DNS (wiki subdomain)
- [x] Consider moving docs subdomain too instead of it pointing to javadoc @austinv11 what do you think?
- [ ] Update link to documentation in https://discord4j.com/
- [x] Turn off read the docs and remove docs folder from this repo
- [x] Update our wiki pages pointing to new documentation

**Comment by kvnxiao** [comment]
@quanticc Can we come up with a standardized way of naming our `.md` docs and the frontmatter within them? Docusaurus v2 supports the following frontmatter, for example:

```
---
id: basic-bot-tutorial
title: Basic Bot Tutorial
sidebar_label: Basic Bot Tutorial
slug: /basic-bot-tutorial
---
```

`id` -> used to identify the markdown file from within the docusaurus config
`title` -> big title header displayed at the top of the page when loaded
`sidebar_label` -> title of the page on the left sidebar (typically the same as `title`, but can be set to something different)
`slug` -> the url following `hostname.domain/docs/`

For conformity I think the id entry should always be lowercase and be alphanumeric + hyphens only (like CSS class naming).

**Comment by kvnxiao** [comment]
Also let's remove all references to imgur and third party image hosting websites, and upload the screenshots to the documentation repository itself.

**Comment by quanticc** [comment]
I agree with the frontmatter standards recommended by the tool. Current naming is just a leftover from GH wiki, files were extracted directly from the repo and had that naming scheme

OK about images, to `/static/img`

**Comment by kvnxiao** [comment]
Here's an example docs folder of .md files that Facebook uses for their create-react-app https://github.com/facebook/create-react-app/tree/master/docusaurus/docs
