### ISSUE TITLE
TextChannel sends requests too long

### ISSUE THREAD

**Issue by AdisAlagic** [Discord4J/Discord4J#820]
I have a music bot that changes topic of the channel every 3 seconds.

To get `TextChannel` class I use this:
`textChannel = event.getMessage().getChannel().cast(TextChannel.class).block();`

Then I start another thread, which has `TextChannel` and use it like this:
```java
textChannel.edit(textChannelEditSpec -> textChannelEditSpec.setTopic(currentTopic.toString()))
                                .doOnError(e -> {
                                    logger.info("Something broke: " + e.getMessage());
                                })
                                .doOnSuccess(textChannel1 -> {
                                    delivered.getAndIncrement();
                                })
                                .subscribe();
```
Where `delivered` is `AtomicInteger` and `currentTopic` is a `StringBuilder`. 

For example, I have a сounter for requests that I sent and received. 
I started a video with length 4:13.  The counter said: Sent: 85; Delivered: 0;

**Expected Behavior:** Requests are being sent and the topic is changing.

**Actual Behavior:** Requests are being sent and topic doesn't change (or changes in 3, 5 or more minutes). 

**Version:** `discord4j-core:3.1.3`

**Other:** I think I am using the wrong approach for creating the class

**Comment by Shadorc** [comment]
Changing something every x seconds seem like a behaviour that Discord will not really like. Also, you're probably getting rate limited, explaining the delay.

**Comment by AdisAlagic** [comment]
I decided to use a message to make it do the same. It works great

**Comment by Shadorc** [comment]
Sending messages is not the same rate limit as editing a text channel (cf https://discord.com/developers/docs/topics/rate-limits#rate-limits). If you enable debug logs, you will see if this is due to rate limit or no.

**Comment by AdisAlagic** [comment]
Yes, it is limits. Thank you.
