### ISSUE TITLE
Get permissions on interaction.member

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#833]
**Feature Description:** Member object from interaction events now contains a permissions string. I didn't made a pull request because I'm not sure if two separate member objects should be created or if the field should be marked as possible.

**Justification:** https://github.com/discord/discord-api-docs/pull/2408

**Comment by quanticc** [comment]
Let's go for the new `Possible` field option for now

**Comment by quanticc** [comment]
When using this data from a rest-only perspective, besides just returning `MemberData`, we should add access to their fields using Discord4J classes to the `Interaction` interface, or create a new `InteractionMember` object.

Interactions from gateway can also benefit from this object, considering the permission value in the payload is more powerful than `Member::getBasePermissions`. I'm not sure yet if we should change `Member` implementation considering this feature is still a WIP from Discord side.

**Comment by quanticc** [comment]
Closing, this is already implemented in the slash command branch
