### ISSUE TITLE
Dependency 'com.discord4j:discord4j-core:3.1.3' not found 

### ISSUE THREAD

**Issue by EnergixCoding** [Discord4J/Discord4J#847]
Im using IntellIJ with Maven and when I try to import the discord4j dependency, IntellIJ cant find it.

pom.xml: https://paste.gg/p/anonymous/cd57e4c513df49b2b2a3054b8d96eee9
iml file (incase thats needed): https://paste.gg/p/anonymous/d62c3690569345bb80d9b8c029af5607

Knowing me I probably forgot to do something

**Comment by quanticc** [comment]
You might need to hit auto-import IntelliJ after adding the dependency. This process is not specific to Discord4J

https://www.jetbrains.com/help/idea/work-with-maven-dependencies.html#generate_maven_dependency

You're welcome to join our discord if this doesn't help: [![Support Server Invite](https://img.shields.io/discord/208023865127862272.svg?color=7289da&label=Discord4J&logo=discord&style=flat-square)](https://discord.gg/NxGAeCY)

**Comment by EnergixCoding** [comment]
> You might need to hit auto-import IntelliJ after adding the dependency. This process is not specific to Discord4J
> 
> https://www.jetbrains.com/help/idea/work-with-maven-dependencies.html#generate_maven_dependency
> 
> You're welcome to join our discord if this doesn't help: [![Support Server Invite](https://camo.githubusercontent.com/ed10a01b006ddafe1ef78d4e56e80a7c0773821b3e0e469fbfc71e849aee85b3/68747470733a2f2f696d672e736869656c64732e696f2f646973636f72642f3230383032333836353132373836323237322e7376673f636f6c6f723d373238396461266c6162656c3d446973636f7264344a266c6f676f3d646973636f7264267374796c653d666c61742d737175617265)](https://discord.gg/NxGAeCY)

Ah yes, that seems to of worked. Thank you.
