### ISSUE TITLE
ResourceLeakDetector in random cases when BOT start.

### ISSUE THREAD

**Issue by Doc94** [Discord4J/Discord4J#859]
**To Reproduce:** Unknow, not happen all the time when BOT start.

**Version:** 3.1.3

**Log:** https://gist.github.com/Doc94/f7fff3ba8cd90a9343e1be382f3deaf7

**Comment by quanticc** [comment]
Log unfortunately doesn't help identifying if the last access is from within D4J or provide a way to reproduce so we can work with it. 

Please try again with our latest snapshots and if the problem persists, run with [advanced/paranoid detection mode](https://netty.io/wiki/reference-counted-objects.html#leak-detection-levels) to identify accessors of that leaked buffer, try to provide extra details like a specific API call you make and reopen this.
