### ISSUE TITLE
Avatar URL is not updated for PresenceUpdateEvent

### ISSUE THREAD

**Issue by HunHage** [Discord4J/Discord4J#861]
I've noticed that when retrieving the `User` instance from a `PresenceUpdateEvent` after the user removes their avatar that the `User#getAvatarURL()` method continues to return the URL for their previous profile picture and not the URL for their default avatar. However when retrieving this information via a `MessageCreateEvent` the `User` instance does have the correct avatar URL.

The Username/Discriminator do correctly update, and the `PresenceUpdateEvent#getNewXXX()` methods do work correctly for Username, Discriminator, and Avatar URL.

After a restart the cache is corrected, I am not sure if this still happens when setting an avatar but.

**To Reproduce:** Start a bot (example with output attached) then remove your avatar and get the link from the `User` instance provided with a `PresenceUpdateEvent`.

The code and output I used to determine this issue:
<https://controlc.com/489c6d65>
<https://controlc.com/02eef052>

**Expected Behavior:** The user's avatar should be updated to reflect what it currently is.

**Actual Behavior:** The user's avatar is not updated and the information becomes stale.

**Version:** 3.1.3

**Comment by quanticc** [comment]
I pushed a fix for this issue, can you try our latest `3.1.4-SNAPSHOT` to confirm?

https://docs.discord4j.com/using-latest-snapshots

**Comment by HunHage** [comment]
All seems to work as expected using `3.1.3-25-gc57794d`, thank you for the fix!
