### ISSUE TITLE
Tracking discord-json changes into Discord4J

### ISSUE THREAD

**Issue by quanticc** [Discord4J/Discord4J#894]
## Implemented in 3.1.x

- #888
    - Add: RestGuild#searchMembers

- Discord4J/discord-json#56
    - Type change: IntegrationData#subscriberCount from `int` to `Possible<Integer>`
    - Type change: IntegrationData#revoked from `boolean` to `Possible<Boolean>`

- Discord4J/discord-json#58
    - Type change: AttachmentData#height and #width from `OptionalInt` to `Possible<Optional<Integer>>`

- Discord4J/discord-json#60
    - Add: InviteCreateRequest#targetType, #targetUserId and #targetApplicationId
    - Add: InviteData#targetType, #targetUserId
    - Remove: InviteData#targetUserType
    - Type change: InviteCreate#targetUser from `Possible<PartialUserData>` to `Possible<UserData>`
    - Remove: InviteCreate#targetUserType
    - Pending: InviteData#targetApplication
    - Pending: InviteCreate#targetApplication

- Discord4J/discord-json#61
    - Add: WebhookData#sourceGuild and #sourceChannel
    - Add: WebhookPartialChannelData
    - Add: WebhookPartialGuildData

- Discord4J/discord-json#63
    - Type change: AuditLogEntryData#userId from `Id` to `Optional<Id>`

- Discord4J/discord-json#64
    - Type change: GuildModifyRequest#region from `Possible<String>` to `Possible<Optional<String>>`
    - Type change: GuildModifyRequest#verificationLevel from `Possible<Integer>` to `Possible<Optional<Integer>>`
    - Type change: GuildModifyRequest#defaultMessageNotifications from `Possible<Integer>` to `Possible<Optional<Integer>>`
    - Type change: GuildModifyRequest#explicitContentFilter from `Possible<Integer>` to `Possible<Optional<Integer>>`
    - Type change: GuildModifyRequest#systemChannelId from `Possible<String>` to `Possible<Optional<String>>`
    - Add: GuildModifyRequest#discoverySplash
    - Add: GuildModifyRequest#systemChannelFlags
    - Add: GuildModifyRequest#rulesChannelId
    - Add: GuildModifyRequest#publicUpdatesChannelId
    - Add: GuildModifyRequest#preferredLocale
    - Add: GuildModifyRequest#features
    - Add: GuildModifyRequest#description

- Discord4J/discord-json#65
    - Add: MessageReferenceData#failIfNotExists

- Discord4J/discord-json#67
    - Add: AttachmentData#contentType

- Discord4J/discord-json#68
    - Add: ChannelData#rtcRegion and #videoQualityMode
    - Add: ChannelModifyRequest#rtcRegion and #videoQualityMode

- Discord4J/discord-json#69
    - Add: ApplicationInfoData#termsOfServiceUrl and #privacyPolicyUrl

- Discord4J/discord-json#70
    - Rename: UpdateSelfVoiceStateRequest to UpdateCurrentUserVoiceStateRequest
    - Rename: UpdateOthersVoiceStateRequest to UpdateUserVoiceStateRequest

- Discord4J/discord-json#72
    - Type change: EmbedProviderData#url from `Possible<Optional<String>>` to `Possible<String>`
    - Type change: GuildFields#premiumSubscriptionCount from `Possible<Optional<Integer>>` to `Possible<Integer>`
    - Type change: GuildUpdateFields#preferredLocale from `Optional<String>` to `String`

- Discord4J/discord-json#73 (implemented in #906)
    - Add: GuildFields#nsfw

## Implemented in 3.2.x

- Discord4J/discord-json#59
    - Remove: Identify#guildSubscriptions

**Comment by Shadorc** [comment]
`Invite#getTargetUser` and `Invite#getInviter` could use the whole `UserData` instead of returning a mono.

**Comment by quanticc** [comment]
Closing this, future changes to discord-json that need Discord4J changes will be tracked here: https://github.com/orgs/Discord4J/projects/2
