### ISSUE TITLE
Improve Region usage in specs

### ISSUE THREAD

**Issue by cameronprater** [Discord4J/Discord4J#910]
**Feature Description:** When using GuildCreateSpec or GuildEditSpec, it is possible to set the Region of the created or edited Guild. However, acquiring an instance of Region requires interacting with RegionData or calling GatewayDiscordClient::getRegions. Instead of requiring an instance of Region to be passed into the spec, a string of the region ID or a RegionId enum could be passed into the spec instead which could be used to construct a Region instance in a manner transparent to the user.

**Justification:** Acquiring an instance of Region via GatewayDiscordClient::getRegions isn't immediately obvious to the user, and interacting with the JSON builder to set correct properties for each field is inconvenient to the user.

**Comment by darichey** [comment]
+1 to a `RegionId` enum. This is also relevant to https://github.com/Discord4J/discord-json/pull/68 and its `core` implementation in https://github.com/Discord4J/Discord4J/pull/895. `VoiceChannel#getRtcRegion()` and its related methods deal in `String`s.
