### ISSUE TITLE
Support DAPI v9

### ISSUE THREAD

**Issue by Shadorc** [Discord4J/Discord4J#916]
**Feature Description:** Start implementing Discord API v9

**Justification:** https://github.com/discord/discord-api-docs/commit/478af37a04672671d0279d5f4d63e5481f0ec2ae

**Comment by quanticc** [comment]
Discord4J team is able to experiment with this since we can test it internally. Targeting v3.2

**Comment by darichey** [comment]
Closing in favor of #958.
