### ISSUE TITLE
Make "WebhookMultipartRequest" not deprecated

### ISSUE THREAD

**Issue by MandarinSmell** [Discord4J/Discord4J#918]
**Feature Description:** 

Make `WebhookMultipartRequest` not deprecated, so we can use it without any warnings (even though we can use it)

**Justification:** 

I found that we can use "WebhookMultipartRequest" when we create follow up message for interactions.

```java
        client.on(new ReactiveEventAdapter() {

            @NotNull
            @Override
            public Publisher<?> onInteractionCreate(@NotNull InteractionCreateEvent event) {
                String command = event.getCommandName();

                if(command.equals("test") {
                    //I can call only this
                    return event.acknowledge().then(event.getInteractionResponse().createFollowupMessage("Test");
                    //But I want to put embed or files in followup message
                    //return event.acknowledge().then(event.getInteractionResponse().createFollowupMessage(webhook, wait));
                }

                return Mono.empty();
            }
        }).blockLast();
```
Well, actually, it seems that I can create followup message which contains only plain text by calling `createFollowupMessage(String content)`, or... create followup message which can contains more data by calling `createFollowupMessage(WebhookMultipartRequest request, boolean wait)`.

Problem is that `WebhookMultipartRequest` is deprecated, so I get warning whenever I use this class. But I want to create embed when user calls slash command for better visuals, and so on. Can we have non-deprecated `WebhookMultipartRequest`, or have some *better* `createFollowupMessage` method?

If we go for latter, I suggest that we can have `createFollowupMessage` which can take lambda function whose argument is class which can provide embed creating methods, or file adding, more rich data supports just like `MessageCreateSpec`.

Or I may be missing proper way to create followup messages. If so, can you tell the way to put embed or files in followup message?

**Comment by darichey** [comment]
As the javadoc on the class indicates,
> This is a hold-over class to backport webhook execute functionality from 3.2.x
i.e., the story for this method is already improved on 3.2. You can either upgrade to 3.2 snapshots or suppress the warning for now.

**Comment by MandarinSmell** [comment]
Ah, I read that message about 3.2.x. I might misunderstand its meaning because I didn't know this class is already a thing in 3.2 snapshot.

and about 3.3 plan, that's really good! I may make my own wrapper for now, but I will wait for it. Thanks for fast reply.
