### ISSUE TITLE
Add support for markdown timestamps

### ISSUE THREAD

**Issue by darichey** [Discord4J/Discord4J#941]
**Feature Description:**
Support Discord's new format for timestamps in messages. See https://github.com/discord/discord-api-docs/pull/3135

I'm not sure exactly how this should look. Perhaps a `Timestamp` class with factory methods for each flag?

**Comment by darichey** [comment]
On second though, it might be better to just have `Timestamp.xxxflag(Instant): String`. I can't think of a reason to actually have a `Timestamp` object. All useful manipulation you could do with it can instead be done with `Instant`. These are just methods to render the instant to Discord's markdown format for them.

**Comment by Masterzach32** [comment]
I can work on this.

Do we want to have utilities for getting an instance of Instant from a timestamp in a message as well?

**Comment by darichey** [comment]
I think that would be part of https://github.com/Discord4J/Discord4J/issues/751.
