### ISSUE TITLE
Improved stage channel support (and stage instances)

### ISSUE THREAD

**Issue by darichey** [Discord4J/Discord4J#954]
**Feature Description:** 
We currently support stage channels by treating them as voice channels. This works, but we will likely want a (related) channel type once we also support [stage instances](https://discord.com/developers/docs/resources/stage-instance) (since those operations are only related to stage channels).

**Comment by Azn9** [comment]
Hello, I started working on this issue 👀
If someone else started too or want to do something on it, let me know !
