### ISSUE TITLE
Add programmatic slash command creation/update

### ISSUE THREAD

**Issue by N-Silbernagel** [Discord4J/Discord4J#961]
**Feature Description:** Add a way to programmatically add/update slash commands to the application/guild. This could look something like:
```java
guild.createCommand("favorite_animal", "choose your favorite animal")
  .addOption(
    OptionBuilder.create("animal", 3)
      .setRequired(true)
      .addChoice("Dog", "animal_dog")
      .addChoice("Cat", "animal_cat")
      .build()
  )
.block()
```
when a command already exists, it updates it

**Justification:** Managing slash commands separately is tedious. A way to manage slash commands via code to be able to check them into version control would be really nice. 

First Issue here so please let me know if I'm missing something.

**Comment by Laarryy** [comment]
Slash commands can already be managed through D4J, here's some example code: https://github.com/Discord4J/Discord4J/blob/3.1.x/core/src/test/java/discord4j/core/ExampleSlashCommandEvent.java

**Comment by N-Silbernagel** [comment]
My bad, thanks for the clarification.
