### ISSUE TITLE
Can't get message object from ephemeral InteractEvents

### ISSUE THREAD

**Issue by MennoMax** [Discord4J/Discord4J#963]
I've stumbled into an issue which LatvianModder already encountered in the [Discord guild](https://discord.com/channels/208023865127862272/451125724766535710/864587910657605632), but couldn't find an issue for this yet.

**To Reproduce:** 
1. Create a ephemeral Message with either a Button or SelectMenu
2. Interact with the component
3. Attempt to retrieve the Message from the SelectMenuInteractEvent

**Expected Behavior:** 
Ability to retrieve a Message object from a SelectMenuInteractEvent in a ephemeral message.

**Actual Behavior:** 
This is the log and image from LatvianModder (which can also be found by following the Discord link above), as I already removed the ephemeral Message and didn't want to revert the changes.

![Image showing a successful interaction in a non-ephemeral message and a failed interaction in a ephemeral message.](https://media.discordapp.net/attachments/451125724766535710/864588009461907496/unknown.png)

`
16:25:38 :green_square:[reactor-http-epoll-3] WARN discord4j.gateway.payload.JacksonPayloadReader - Error while decoding JSON (com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of discord4j.discordjson.json.ImmutableMessageData, problem: Cannot build MessageData, some of required attributes are not set [author, content, timestamp, tts, mentionEveryone, pinned, type]
`

`
22:20:57 Custom command: ??testing_buttons
22:20:57 [reactor-http-epoll-3] WARN discord4j.gateway.payload.JacksonPayloadReader - Error while decoding JSON (com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `discord4j.discordjson.json.ImmutableMessageData`, problem: Cannot build MessageData, some of required attributes are not set [author, content, timestamp, tts, mentionEveryone, pinned, type]
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: discord4j.discordjson.json.ImmutableInteractionData$Json["message"])): 
`

`
{"t":"INTERACTION_CREATE","s":7002,"op":0,"d":{"version":1,"type":3,"token":"<longass token here>","message":{"id":"864587226629013555","flags":64},"member":{"user":{"username":"LatvianModder","public_flags":640,"id":"143142144469762048","discriminator":"0001","avatar":"028941d99332e5cef721dc8b749b22fb"},"roles":["166631522516992000","220243391936462849","217332124628287490","254797435359068160","261205946695417856","370349110571827200","412803404109447168","829500528407871489","764218451597852745","765995096642158602","763489207716675597","748075791790637078"],"premium_since":null,"permissions":"137438953471","pending":false,"nick":null,"mute":false,"joined_at":"2017-10-15T19:01:31.134000+00:00","is_pending":false,"deaf":false,"avatar":null},"id":"864587236251140146","guild_id":"166630061217153024","data":{"custom_id":"macro/lfgo","component_type":2},"channel_id":"397702104204050434","application_id":"712800443566260316"}}
`

**Version:** 
Discord4J 3.2.0-RC1

**Other:** 
\-

**Comment by darichey** [comment]
The problem is that Discord sends an incredibly-partial message object for interactions on ephemeral messages:
```json
{"id":"864587226629013555","flags":64}
```
This is, of course, completely undocumented.

I don't know what to do about this. By any practical definition, this is _not_ a message object. We can't go and make every method of `Message` return `Optional`. We also can't duplicate everything in `Message` for interactions. I guess we could have `Message extends InteractionMessage`, but I can see us being painted into a corner with that.

**Comment by MennoMax** [comment]
What is required (at least in my case) is some way to identify which message the interaction belongs to. The only way I currently see to do this is by setting a unique custom id across every command execution for the component. A way to access just the message id from the ephemeral message would be sufficient for me.

**Comment by MennoMax** [comment]
I guess that's the best workaround for now - to append the interaction id to the custom id of the component.
