### ISSUE TITLE
New specs don't have proper nullability annotations

### ISSUE THREAD

**Issue by darichey** [Discord4J/Discord4J#966]
New specs' `propertyOrNull` methods don't have their parameters annotated as `@Nullable`. For example, all of these snippets will result in warnings about passing `null` to a parameter annotated as `@NotNull`.
```java
GuildMemberEditSpec.builder().newVoiceChannelOrNull(null);

GuildMemberEditSpec.create().withNewVoiceChannelOrNull(null);

GuildMemberEditMono.of(getMember()).withNewVoiceChannelOrNull(null);
```
This was pointed out in the original new specs PR here: https://github.com/Discord4J/Discord4J/pull/927#issuecomment-851036631. As pointed out there, this seems to be a limitation with immutables. We should consider trying to contribute a fix to the issue https://github.com/immutables/immutables/issues/1307.

**Comment by quanticc** [comment]
Thanks a lot, your upstream fix was merged https://github.com/immutables/immutables/pull/1320 so we can apply this on their next (pre)release
