### ISSUE TITLE
MessageChannel#getLastMessageId should return an empty optional if there is no message in the channel

### ISSUE THREAD

**Issue by Azn9** [Discord4J/Discord4J#979]
**Feature Description:** 
When using the MessageChannel#getLastMessageId method, the returned optional is always present, even if there is no message in the channel.
If there is at least one message, its ID is provided, 0 otherwise, which is not really what an Optional is designed for.
If there isn't any message in the channel, calling MessageChannel#getLastMessageId should return an empty optional.

**Justification:** That should be the correct use of Optionals, and it is easier to check for an `optional.isEmpty()` rather than `optional.get().getAsLong() == 0`

**Comment by darichey** [comment]
This is actually an issue with every `Possible<Optional<Id>>` field. `PossibleOptionalIdEncoding` in discord-json doesn't properly handle the `null` case.

**Comment by darichey** [comment]
Fixed by https://github.com/Discord4J/discord-json/commit/3f7ad17d1534784de7cbb0511d5169a85ebb9c64
