### ISSUE TITLE
Unknown event type : GUILD_SCHEDULED_EVENT_DELETE

### ISSUE THREAD

**Issue by Azn9** [Discord4J/Discord4J#989]
**To Reproduce:** In a community guild, create a scheduled event (might throw another unknown event, I haven't tested it), then delete it.

**Expected Behavior:** /

**Actual Behavior:** This event is not tracked

**Version:** All versions

**Comment by darichey** [comment]
This can be tracked by https://github.com/Discord4J/Discord4J/issues/1000
