### ISSUE TITLE
Application commands created with Interactions class don't appear to function

### ISSUE THREAD

**Issue by NovaFox161** [Discord4J/Discord4J#997]
**To Reproduce:**
```java
/* Login with gateway logic */

ApplicationCommandRequest pingCmd = ApplicationCommandRequest.builder()
            .name("ping")
            .description("A simple ping pong command.")
            .build();

Interactions.create()
            .onGlobalCommand(pingCmd, (restInteraction) -> restInteraction.replyEphemeral("Pong!"))
            .createCommands(client.getRestClient())
            .subscribe();
```

**Expected Behavior:**
"Pong!" should be received as an ephemeral reply message.

**Actual Behavior:**
Absolutely nothing happens. Discord sends the data and no action is taken in code. After 3 seconds discord says the interaction has failed since no ack or reply was sent.

OR

Discord will immediately error with "Invalid interaction application command" and I am unable to find an answer to what the exactly means since no errors are seen in the logs.

I'm not sure what leads to either of these cases appearing.

**Version:**
D4J 3.2.0-RC3

**Other:**
Logging with trace revealed nothing unfortunately, I see the payload for the application command is received, but there appears to be no handling of it.

**Comment by JoaaoVerona** [comment]
Facing the exact situation; posted the comment below on Discord server but will replicate it here.

After some commands are created in an `Interactions` instance, it seems their handlers are never called whenever a command/interaction is received (commands are correctly registered and sent to Discord successfully; but their handlers are never called).

From what I've seen in the `Interactions` source, they are added to a private `commands` list, but this list is only referenced in `Interactions#findHandler`, which is called by `Interactions#buildReactorNettyHandler`, which is never called. Should I call `buildReactorNettyHandler` and use it somewhere in my application code?

**Comment by quanticc** [comment]
Sorry for the lack of clarity, we're missing documentation around this feature. Make sure you have built a handler for interactions in endpoint mode. See this example:

https://github.com/Discord4J/Discord4J/blob/3.1.x/rest/src/test/java/discord4j/rest/example/ExampleRestCommand.java#L64-L72

You still need to setup a validator, which can be done with a proxy. https://github.com/Discord4J/Discord4J/issues/818 for more details (see Using webhook based Interactions API with a Reactor Netty server)
